### ISSUE TITLE
Support multiple Dockerfile FROM lines

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1011]

**Comment by reicheltp** [comment]
I can take a look on this

**Comment by rarkins** [comment]
Great. The existing logic is a little hacky. Good to support case insensitive FROM too

**Comment by reicheltp** [comment]
Hi @rarkins 

I've played around this weekend with the multiple from support and ended with a very solid regex to extract the tag / digest and image name from a Dockerfile. (See https://github.com/reicheltp/renovate/blob/docker-mulitple-from/lib/workers/dep-type/dockerfile.js)

Then I discovered that the whole Dockerfile logic is broken, as we can have only digest OR tag. (see https://docs.docker.com/engine/reference/builder/#from)

Shall I wait for #796 and #1027 or should we start a new approach for Dockerfile renovation?

**Comment by rarkins** [comment]
> we can have only digest OR tag

We discussed that [here](https://github.com/singapore/renovate/issues/780#issuecomment-328136372) and I decided to use it due to this comment in the moby repository: https://github.com/moby/moby/issues/33165#issuecomment-300907297

Given that it works currently I propose to stick with this approach, but maybe we should proactively build the alternative approach (encoding tag into a comment in the Dockerfile) so that it can be switched on in case Docker change their behaviour without notice.

**Comment by rarkins** [comment]
FYI I am actively working on #796 right now

**Comment by reicheltp** [comment]
Didn't know that tag and digest work together. But, if the moby guys say this works we should stay with that.

OK I will definitely wait for #796. 

Depending on the priorities, I would like to wait for #1030 until I continue this.

**Comment by rarkins** [comment]
@reicheltp as mentioned [here](https://github.com/singapore/renovate/issues/1030#issuecomment-339251840), I think that enough of the docker logic has been moved into lib/manager/docker that you can hopefully proceed now. Happy to help - ping me on gitter for anything real-time.

**Comment by reicheltp** [comment]
@rarkins Looks very promising! I'm busy today but will take a look on it tomorrow.
