### ISSUE TITLE
Onboarding does not detect renovate config in package.json

### ISSUE THREAD

**Issue by wopian** [renovateapp/renovate#1159]
Recently added Renovate to one of the projects i'm in the process of rewriting, so the Configure Renovate PR was left open. I preemptively cherry-picked the custom configuration to `package.json` in the rewrite branch for when it's merged.

Just switched the base branch of the repo to the rewrite branch and allowed renovate to re-create the [Configure Renovate PR][hibari]. The PR body is correctly using the existing configuration in *What to Expect*. However it also created the default `renovate.json` file, which according to the PR body should be deleted if using renovate in `package.json`.

The expected behaviour if renovate configuration already exists in `package.json` is for a PR with an empty commit.

This would also apply if a repo was removed and re-added in the renovate bot settings.

[hibari]:https://github.com/wopian/hibari/pull/370

**Comment by rarkins** [comment]
I have renamed the issue "Onboarding does not detect renovate config in package.json" as that's actually the exact issue. Renovate *does* detect existing configuration if there's a `renovate.json`.

Renovate considers a repository to be onboarded if it has either:
- A closed "Configure Renovate" PR
- A `renovate.json` or `.renovaterc` or `.renovaterc.json`

In your case, you didn't need to delete the `renovate.json` and merge, you could have just closed the PR unmerged.

> This would also apply if a repo was removed and re-added in the renovate bot settings.

Actually it wouldn't. Such a repo would have a closed Configure Renovate PR or a `renovate.json` or both. This only applies to this very rare case of yours where you moved config to `package.json` before closing the original PR, then you changed base branches.

I will leave this issue open at low priority in case anyone from the community wishes to submit a PR for it.
