### ISSUE TITLE
Move repository to `renovateapp` org

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1213]
https://github.com/renovateapp

Before I do that, any "gotchas" to think of? Apart from never recreating a `singapore/renovate` repository that is.

**Comment by rarkins** [comment]
@olstenlarck any advice? I think you were moving repos around a lot lately

**Comment by olstenlarck** [comment]
Heya! Good idea to do that.

As about my experience... Yea moved and renamed a lot of things few times. And it seems that GitHub is just amazing and i don't have any problems.

In my cases, @tunnckoCore was my personal profile for a long long time, for years. When I renamed my profile and created @tunnckoCore org i didn't have any problems. Redirects works brilliant too, until repository with same existing name in @olstenlarck is created.

But yea, you should not worry about anything more.

**Comment by rarkins** [comment]
Well, I did it but some things are broken :(

e.g.

```
Pushing to https://rarkins@github.com/renovateapp/renovate.git
remote: Permission to renovateapp/renovate.git denied to rarkins.
fatal: unable to access 'https://rarkins@github.com/renovateapp/renovate.git/': The requested URL returned error: 403
```

Also CI can't see it for now.

**Comment by olstenlarck** [comment]
Ah.. i forgot about that, yea. CIs are a bit tricky and depends. You should reactivate it from `renovateapp` "account". I mean https://circleci.com/gh/renovateapp, it should appear there now, instead of in `singapore`.

As about the Git, you should update the remote. But most easier is to just clone it again with the new url.
