### ISSUE TITLE
Enhancement: support local packages

### ISSUE THREAD

**Issue by jycouet** [renovateapp/renovate#1215]
When I renovate a repo with some local packages like this:
```
"dependencies": {
   ...
   "svg-gauge": "file:../localRegistry/packed/svg-gauge-1.0.4.tgz",
   ...
}
```

I get an error:
`error "../localRegistry/packed/svg-gauge-1.0.3.tgz": Tarball is not in network and can not be located in cache (["XXXXXX\\tmp-164ZPSW1lrL3mBf\\packages\\localRegistry\\packed\\svg-gauge-1.0.3.tgz","XXXXXX\\AppData\\Local\\Yarn\\cache\\v1\\.tmp\\33a03e363289df78d21979a259adbe1f\\.yarn-tarball.tgz"])`

When in a `package.json` we find a `file:` we should try to copy the source in the tmp folder for yarn to resolve everything.

What do you think?

**Comment by rarkins** [comment]
It doesn't look like the type of thing I'd *want*, but I can see why you need it. If it can be done elegantly, then I'll accept a PR for it. You'd probably want to add it around the same time we do `writeExistingFiles()`. I'm definitely trying to avoid doing a full `git clone` !

**Comment by jycouet** [comment]
I fully agree that it's not nice :(
I even tried to go away from this, but didn't find any elegant solution.
- Running a `npm install xxx` after `yarn` so that it's not part of the `package.json` & `yarn.lock`?
- Running an unzip of the local dep in `node_modules` => what about dep?!

So I'll look a bit more, but yes I think something around `writeExistingFiles()` would be a good place.

**Comment by rarkins** [comment]
What is the reason for needing local files? I've never seen it before so don't  really understand

**Comment by jycouet** [comment]
I have 2 main use cases:
- using a package not deployed yet
    - dev by another department (will come maybe in 6month... but I need it right now)
- using a package hosted on a Git repo in a Private VPN
    - I commit all files in my source code like this my build system (not in the VPN) can still work
    - Since I put it in `localRegistry`, I can keep track of it manually

**Comment by jycouet** [comment]
Hi, 
I have something here: https://github.com/jycouet/renovate/tree/feature/localtgz
But I didn't create a PR yet because I'm struggling with downloading tgz files.

Yes, as you can see here: https://github.com/jycouet/renovate/commit/11685ba625509d940585e0a846256abad025ffc6#diff-6726f798195311531fbbd84c0e638127R127
I'm using `platform.getFile` and this doesn't seems to work with these kind of file.

Here is the gitrepo where you can test: https://github.com/jycouet/tmpReno-Without-Workspace

Today there is `getFile`, we should maybe have also a `downloadFile` or something like this?

**Comment by rarkins** [comment]
Maybe getfile can be extended with optional encoding param if that's the problem?

**Comment by jycouet** [comment]
I don't think that it's encoding problem.
It's more that it's a binary.
