### ISSUE TITLE
Accidental mention spam: Is this worth fixing as a "bug"?

### ISSUE THREAD

**Issue by platinumazure** [renovateapp/renovate#1238]
Hi folks! I have an unusual issue and I'm not sure whether it's really a bug or not.

Basically, with the release of ESLint 4.12 today, the GitHub release has a commit summary which mentions me (\@platinumazure). When renovate opened PRs in all repositories which are listening for ESLint releases, I got notifications for every single one (including e-mails due to my e-mail settings, which sends e-mails in threads where I am mentioned). I expect I will be dealing with tens or hundreds more such notifications.

In some regard it's completely our fault that we wrote a commit summary with a string that could be parsed as a GitHub username. I accept that. However, given the user experience implications (i.e., mentioning, notifying, and subscribing users to repositories they may have never heard of), as well as the extra load that might unintentionally be put on the GitHub servers, I'm wondering if it would be worth escaping the GitHub release content against Markdown elements specific to GitHub user mentions? (Well, assuming it's even possible to escape/prevent a mention in the first place.)

Happy to consider writing a PR if this is accepted as a potential bug/enhancement... Thanks!

**Comment by rarkins** [comment]
Hi @platinumazure, thanks for raising this and sorry for the inconvenience. 

I definitely don't want people getting notification spam either, in fact it should have been fixed "the last time". I looked up that PR - https://github.com/renovateapp/renovate/pull/1084 - and it doesn't seem to have been regressed. 

We intend to escape every @ in the body with a zero-width space: https://github.com/renovateapp/renovate/blob/6e11cd02e311d8765dc6439a77f4b28a44a1e8b8/lib/workers/pr/index.js#L132-L133

Yet here is one of them you mentioned: https://github.com/algolia/instantsearch.js/pull/2601#issue-276798185

**Comment by rarkins** [comment]
Dev Tools lets me see that the space is preserved for the issue number but not username:
![image](https://user-images.githubusercontent.com/6311784/33237553-dbcfd006-d276-11e7-8a03-820e433c9c9a.png)

**Comment by rarkins** [comment]
Embarrassing bug. It is a replace and not replace all. Switching to replace all regex to fix. Sorry again!

**Comment by rarkins** [comment]
@platinumazure I've pushed this fix live to the app. It should replace all those mentions within the next 30 minutes or so and not generate any new ones. Unfortunately, I think GitHub might keep you subscribed to those PRs regardless of whether your @ mention has been erased or not.

**Comment by platinumazure** [comment]
Thanks so much for jumping on this so quickly! Don't worry about the
subscriptions, that's a GitHub implementation detail and something this app
couldn't have anticipated. Again, really appreciate your help in fixing
this for the future.
