### ISSUE TITLE
deactivate for specific repositories

### ISSUE THREAD

**Issue by Urigo** [renovateapp/renovate#1254]
Hi! 
I've configured renovate to run automatically on all my repositories but there are some I would like to remove manually from it.

How can I do that?

Thank you again for such a valuable tool!

**Comment by rarkins** [comment]
GitHub's installation control is pretty limited - either you pick every repository individually, or you select all (like you've done). To deactivate for any that are part of the "select all", the quickest way is to add this `renovate.json` to the repository:

```
{ "enabled": false }
```
