### ISSUE TITLE
Renovate .nvmrc files

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1270]
https://github.com/creationix/nvm#nvmrc

Related to #1243 and #320

**Comment by rarkins** [comment]
Example: https://github.com/algolia/community-project-boilerplate/blob/master/.nvmrc
Cc @vvo

**Comment by rarkins** [comment]
`nvm` supports ranges via semver-like syntax. e.g. you could specify `9`, `9.2`, or `9.2.0`. If using Renovate, I guess we should default to 'pinning' (i.e. `9.2.0`) because such pins will be kept automatically up-to-date by Renovate anyway, and doing so (pinning) will increase build reliability/reproduceability.

**Comment by vvo** [comment]
> I guess we should default to 'pinning' (i.e. 9.2.0) because such pins will be kept automatically up-to-date by Renovate anyway, and doing so (pinning) will increase build reliability/reproduceability.

That would work for me since it's so easy to install the new version (nvm install).

Also travis uses this file to setup the nodejs version by default when available, so it eases testing.

**Comment by vvo** [comment]
Node.js has always two versions, LTS and Current. Maybe we could be able to express "always latest LTS or always latest Current". WDYT?

**Comment by rarkins** [comment]
@vvo actually Node.js terminology is a little more complicated.

`Current` is always the very latest release, and there can be only one current. It might be even or odd, e.g. right now it's `9`

Multiple versions can be `LTS` at the same time, in fact right now it's `4,6,8`.

`4` is considered *Maintenance* LTS, while `6` and `8` are both *Active* LTS

Node.js don't technically use the term "latest" themselves - they use Current, LTS, Active and Maintenance.

So it gets a little complicated if you don't know whether someone wants *all* versions matching a description, or just the latest one matching. For Travis, I defined these policies:

```
const policies = {
  lts: [4, 6, 8],
  active: [6, 8, 9],
  current: [9],
  lts_active: [6, 8],
  lts_latest: [8],
};
```

Assuming you want your `.nvmrc` to use an exact version (e.g. `9.2.0`) then I need to add an extra lookup too. In the case of the repositories you listed, it looks like you would want something like:

```
  "supportPolicy": ["current"],
  "pinVersions": true
```

Look OK?

**Comment by vvo** [comment]
Yep great!

**Comment by hbetts** [comment]
It may be really beneficial to have upgrades to `.nvmrc` synchronized with upgrades to a project's `package.json` `node` `engines` property.

As explained [here](https://github.com/renovateapp/renovate/issues/320#issuecomment-365822399), developers on an application with a pinned `node` `engines` property will need to be on that version of Node, and the easiest way for that to happen is if their `.nvmrc` file was configured with the same pinned Node version.

**Comment by hbetts** [comment]
What is the behavior of Renovate if the policy is set to an option containing more than one version of Node, such as `lts`, and `pinVersions` is set to `true`?

**Comment by rarkins** [comment]
@hbetts I haven't considered that use case and there is no logic to convert from ranges to pinning currently. I guess for node we should default to pinVersions=false and if someone opts-in to it then we would pin "initially" like we do with npm.
