### ISSUE TITLE
feat: custom git commit author in gitlab

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1281]
As implemented for GitHub in #1280 - needs porting to GitLab. Should require just a few similar lines in lib/platform/gitlab/* files

**Comment by hugomarisco** [comment]
I can work on this if it's still up for grabs

**Comment by rarkins** [comment]
@hugomarisco definitely - please go ahead.

**Comment by rarkins** [comment]
@hugomarisco do you need any help on this one?

**Comment by hugomarisco** [comment]
hey @rarkins, sorry, I haven't had an opportunity to start working on this yet. I'll give it a go this week.

**Comment by hugomarisco** [comment]
I won't be able to pick this up due to the amount of work I'm dealing with right now.

I should have the time in about 2 weeks, in the meanwhile if someone else wants to pick it up, feel free to do so.

I'm sorry about this, I wasn't expecting this new project I'm working on.

**Comment by rarkins** [comment]
@hugomarisco no problem at all! Your contributions will always be welcome, whenever you get the time available

**Comment by keplersj** [comment]
I'm interested in helping out on this issue. I've been looking through the platform code and I think I understand what needs to happen. @hugomarisco mind if I pick this up?

**Comment by hugomarisco** [comment]
Not at all @keplersj , please go ahead :)

**Comment by adam-moss** [comment]
@keplersj @hugomarisco - I also have need of this feature and have started a basic MR for it.  Would be great to get your ideas / feedback (I still need to write some tests, but I'm having problems getting them running locally which is hampering me somewhat).
