### ISSUE TITLE
Bazel: Support http_archive dependencies

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1292]
Renovate currently supports git_repository dependencies, however the bazel docs recommend http_archive instead. We should support this too.

https://docs.bazel.build/versions/master/be/workspace.html#http_archive

Example from the docs:
```
http_archive(
    name = "build_bazel_rules_apple",
    strip_prefix = "rules_apple-0.1.0",
    urls = ["https://github.com/bazelbuild/rules_apple/archive/0.1.0.tar.gz"],
)
```

One nice thing Renovate can do is automate away the hassle of manually updating sha256 references too.

Cc @alexeagle

**Comment by alexeagle** [comment]
Will be nice to have. Note how rules_go suggests doing it:
https://github.com/angular/angular/blob/master/WORKSPACE#L47
where the sha is a hash of the .tar.gz, not a git commit hash.

**Comment by rarkins** [comment]
@alexeagle thanks for the rules_go example. It looks like Github *doesn't* expose the tar.gz hash through the API, so that means Renovate will need to download the tar.gz in full to calculate it. I'm pretty sure GitHub releases are not immutable either, e.g. you can even *delete* a existing release and then create it again later with an entirely different tarball. I assume that's why bazel suggests using the sha256! 

Also, seems like we should support [new_http_archive](https://docs.bazel.build/versions/master/be/workspace.html#new_http_archive) too

**Comment by mxey** [comment]
I had a quick look at the code and I think `new_http_archive` wasn't implemented after all?

**Comment by rarkins** [comment]
No, seems like it wasn’t. Could you raise a feature request issue here with an example you’re using in an actual repository?

**Comment by mxey** [comment]
@rarkins Sorry, I don't actually use Bazel yet, I'm just looking at options ;)
