### ISSUE TITLE
Not working with GitLab - that uses groups and subgroups for projects

### ISSUE THREAD

**Issue by jvetyska** [renovateapp/renovate#1293]
Unable to run renovate on gitLab. 
Using command (with gitlab token as env variable): 
renovate --platform gitlab --endpoint https://gitlab.mydomain.com/api/v4 --autodiscover --labels=renovate

It gathers the repos, but then when operating on each project, it borks with 404 for each of the GET or any other API call that uses the repo path and name.

I've spent ton of time making sure I'm doing everything correct with the command and access to gitLab.
I keep getting these 404s for each repository, such as:
ERROR: GitLab init error (repository=repogroup/reposubgroup/myproject)
       "err": {
         "name": "GitLabError",
         "host": "gitlab.mydomain.com",
         "hostname": "gitlab.mydomain.com",
         "method": "GET",
         "path": "/api/v4/projects/repogroup%2Freposubgroup/myproject",
         "protocol": "https:",
         "url": "https://gitlab.mydomain.com/api/v4/projects/repogroup%2Freposubgroup/myproject",
         "statusCode": 404,
         "statusMessage": "Not Found",
...

So I have finally decided to look at the gitLab API, and it doesn't support project names in the API, only their numerical ID.

such as https://gitlab.mydomain.com/api/v4/projects/148
And the ID is the first thing in the json response from /api/v4/projects
And is used for all other API communication, such as getting branches: /api/v4/projects/148/repository/branches

The current implementation of renovate uses the branch groups and name to access the api, which does not work. Strangely, I did see it work a few times for one repo, perhaps it kind of worked at some point or works for projects that were never moved or renamed etc. But using the ID for api access works every time and was used even in V3 from what I can tell.

**Comment by rarkins** [comment]
Do you have a reverse proxy in front of your GitLab? Eg Apache or nginx?

**Comment by jvetyska** [comment]
Looks like nginx ("headers": { "server": "nginx", ..}}

**Comment by rarkins** [comment]
GitLab recently changed to require %2F instead of forward slashes for repository and branch names. Renovate does his but most reverse proxies by default will take our %2F and converts it to / before passing on to GitLab. If so then it needs a configuration change in nginx

**Comment by jvetyska** [comment]
Ok, I'll give that a shot. Is there a reason why not just use the ids and get around all kinds of problems with the naming and paths?

**Comment by rarkins** [comment]
If you have a reverse proxy misconfiguration - and it’s “misconfigured” if it’s resolving escaped URLs to an app that needs them - then you’ll have other problems too, eg with branch names. Better to fix the proxy config.

**Comment by jvetyska** [comment]
Well, ok, I think I see the problem now. 
So the proxy works fine, but there is a problem in the renovate code, because it uses %2f only for the first group, but not for the second group. You can see that in my example above. That is why I've seen it work for a project that was inside a group, but it doesn't work for any projects that are inside a subgroup. 
If I manually change the second / into %2f, it works like a charm.

**Comment by jvetyska** [comment]
Yeah, I can see all the .replace calls in https://github.com/renovateapp/renovate/blob/master/lib/platform/gitlab/index.js
only replace the first /. It would require to use regex to replace all instances, such as .replace(/\//g, '%2F')

**Comment by rarkins** [comment]
@jvetyska thanks for this bug report, and sorry for the time it spent you. This should now be fixed in renovate@10.29.1
