### ISSUE TITLE
renovateapp.com docs typos

### ISSUE THREAD

**Issue by edmorley** [renovateapp/renovate#1311]
Hi

I spotted a couple of typos in the renovateapp.com docs (which are in the private repo, otherwise I'd open a PR). Some are pretty nit-picky so feel free to ignore them - and as with all the other issues I've opened, there is no rush - we're super happy to be able to use Renovate and just want to report anything we encounter in case it helps out the project :-)

## [dependency-pinning](https://renovateapp.com/docs/deep-dives/dependency-pinning#reducing-the-noise-of-dependency-updates)

> Therefore you should consider enabling automerge for all lint packages so save yourself the pointless click.

`s/so/to/`

> In this case you maybe wake up to 5/10 of your overnight Pull Requests already merged by themself.

`s/maybe/might/`
`s/already merged by themself/having already merged themselves/`

## [configuration-options](https://renovateapp.com/docs/configuration-reference/configuration-options)

> The downside of this aproach is that you will end up with merge commits and not a nice clean default branch!

`s/aproach/approach`

> In that case the project may prefer Pull Requests from Renovate are targetted to the next branch instead of master.

`targetted` is typoed and there's a missing that/for, however I think it might also read more clearly adjusted like so:

```In that case, the project may prefer for Pull Requests from Renovate to be opened against the `next` branch instead of `master`.```

> Extend this if you wish to configure rules specificly for dependencies and not devDependencies or optionalDependencies.

`s/specificly/specifically/`
(and in a few other places on that page)

> See http://localhost:4000/docs/deep-dives/private-modules for details on how this is used to encrypte npm tokens.

`s/encrypte/encrypt/`

**Comment by rarkins** [comment]
@edmorley thanks very much! I'm scaling down a little for a Christmas vacation but will get to these soon. I'm also thinking about moving all the markdown docs files into this repo and then importing them into the website repo as a dependency or something, so that they can be more easily editable.

**Comment by edmorley** [comment]
Many thanks for this and the others :-)

**Comment by rarkins** [comment]
BTW the non-auto generated content in renovateapp.com/docs is all now sourced from this repository so can be edited via PR
