### ISSUE TITLE
Improving the interaction between unpublishSafe and not-pending

### ISSUE THREAD

**Issue by edmorley** [renovateapp/renovate#1312]
I noticed that `prNotPendingHours` defaults to 12 hours, which means that if a project uses both `"unpublishSafe": true` and `"prCreation": "not-pending"`, then the PR will end up being created 12 hours prior to the check having transitioned from `pending` to `success` (since the check needs a full 24 hours).

This is contrary to the docs, which say [here](https://github.com/renovateapp/renovate/blob/2c6a2dd43b5d0607eae9ed7daff0338c6041dbdd/docs/status-checks.md#unpublish-safe):

> This way the PR will only be created once the upgrades in the branch are at least 24 hours old because Renovate sets the status check to "pending" in the meantime.

And [here](https://renovateapp.com/docs/configuration-reference/configuration-options#unpublishsafe):
> that way you won’t get the PR raised until after a patch is 24 hours old or more

I think there are a few ways to resolve this:

1. Increase the default of `prNotPendingHours` from 12 hours to 24 across the board.
2. Have different defaults for `prNotPendingHours` depending on whether the user has `unpublishSafe` enabled (though this would need to be clearly documented to avoid confusion).
3. Leave the default for `prNotPendingHours` as-is (ie at 12 hours), but make the [:unpublishSafe preset](https://github.com/singapore/renovate-config/blob/2fb8d65bfcf5ebf6bc010f0d129cc99833fa880c/packages/renovate-config-default/package.json#L129-L132) also adjust the value set for `prNotPendingHours` (though this might also be confusing for users and not everyone uses the presets).

Thoughts? :-)

**Comment by rarkins** [comment]
Option 1 is easiest and totally fine by me. It only happens if people change the prCreation setting AND either have no tests or indefinitely pending ones.

I used to default to not-pending but it caused too much confusion with people who had no tests.

**Comment by edmorley** [comment]
Great, I'll open a PR :-)

> I used to default to not-pending but it caused too much confusion with people who had no tests.

Looking at the GitHub API docs [here](https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref), it seems that the "no tests" vs "tests pending" case can be differentiated by checking the length of `statuses` in the response body. Perhaps [getBranchStatus()](https://github.com/renovateapp/renovate/blob/2c6a2dd43b5d0607eae9ed7daff0338c6041dbdd/lib/platform/github/index.js#L310-L329) should fake the status to eg `"none"` if `statuses` is empty?

**Comment by edmorley** [comment]
> Perhaps getBranchStatus() should fake the status to eg "none" if statuses is empty?

Hmm though if that was done, there would need to be a slight time delay (eg check at least 1-2 minutes have passed since the commit time) otherwise the PR might be created before Travis/whatever has had a chance to report the first status.

**Comment by rarkins** [comment]
> Hmm though if that was done, there would need to be a slight time delay (eg check at least 1-2 minutes have passed since the commit time) otherwise the PR might be created before Travis/whatever has had a chance to report the first status.

I had thought about this but was concerned about it being too much of a race condition. e.g. any hiccup from GitHub notifications to CI or CI's processing of them and we might merge a branch before it starts testing.
