### ISSUE TITLE
Document whether packageNames and packagePatterns can be used together

### ISSUE THREAD

**Issue by edmorley** [renovateapp/renovate#1313]
For one use-case I need to catch package names that match either `neutrino` exactly or `@neutrinojs/*`.

Looking at the docs it wasn't clear whether I could use both `packageNames` and `packagePatterns` at the same time, but from inspecting the source I see that won't work:
https://github.com/renovateapp/renovate/blob/987891ba2ec1445bbc5e0a3beefa8675c2ad2838/lib/workers/dep-type/index.js#L75-L87

This is not a problem, since I can instead do something like:

```json
{
  "packagePatterns": [
    "^neutrino$",
    "^@neutrinojs/"
  ]
}
```

...however I think it may be good to clarify this on some/all of these:
https://renovateapp.com/docs/configuration-reference/configuration-options#packagerules
https://renovateapp.com/docs/configuration-reference/configuration-options#packagenames
https://renovateapp.com/docs/configuration-reference/configuration-options#packagepatterns
https://renovateapp.com/docs/configuration-reference/configuration-options#excludedpackagenames
https://renovateapp.com/docs/configuration-reference/configuration-options#excludedpackagepatterns

...particularly since from source inspection it seems like specifying both types of either an include or exclude won't result in an error, but that property being silently ignored.

**Comment by rarkins** [comment]
I had intended that they work concurrently and I'm not convinced from the source code above that they don't. The logic of that is meant to be:

1. If there are package names and any of the packageNames have a match then apply the rule, OR
2. If any of the packagePatterns have a match then apply the rule


i.e. this is not the same as if the first if statement *returned* false.

Also the logic says "if packagenames are defined and they match..... else if package patterns are defined....."

So if you have both defined and the packageName does not match then the patterns would still be checked.

**Comment by rarkins** [comment]
Anyway even if my analysis of the above snippet is wrong, I think we should make them work together as an inclusive or, not exclusive. i.e. fix the code if necessary rather than update any docs.

**Comment by rarkins** [comment]
I just added a test to that code that seems to confirm that it supports both:
```
    it('supports inclusive or', () => {
      const nConfig = {
        packageRules: [
          {
            packageNames: ['neutrino'],
            packagePatterns: ['^@neutrino\\/'],
            x: 1,
          },
        ],
      };
      const res1 = depTypeWorker.getDepConfig(nConfig, { depName: 'neutrino' });
      expect(res1.x).toBeDefined();
      const res2 = depTypeWorker.getDepConfig(nConfig, {
        depName: '@neutrino/something',
      });
      expect(res2.x).toBeDefined();
    });
```

**Comment by rarkins** [comment]
Actually docs should still be updated though if they are currently unclear.

**Comment by edmorley** [comment]
Ah yes I didn't see the `forEach()`, which allows supporting both. Thank you for confirming via the test!

**Comment by rarkins** [comment]
Documentation for `packageRules` updated on renovateapp.com, using neutrino example

**Comment by edmorley** [comment]
Many thanks :-)
