### ISSUE TITLE
Making PR titles for grouped dependencies consistent

### ISSUE THREAD

**Issue by edmorley** [renovateapp/renovate#1314]
Currently when a monorepo group is updated, the following defaults are used (these examples are with semantic commit mode disabled):
* PR title: `Renovate react monorepo packages`
* Commit messages:
  - `Upgrades react in dependencies from 15.6.2 to 16.2.0`
  - `Upgrades react-dom in dependencies from 15.6.2 to 16.2.0`

Compare this to a non-grouped PR:
* PR title: `Update dependency popper.js to v1.12.9`
* Commit message:
  - `Upgrades popper.js in dependencies from 1.12.6 to 1.12.9`

For consistency (and since I think it makes the intent of the PR clearer), it would be good to `s/Renovate/Update/` in the default handlebar templates.

Does this sound ok?

**Comment by rarkins** [comment]
Yes, what you are suggesting sounds fine. However (this is perhaps irrelevant) I think the commit messages you mention don't look quite right - is that copy/pasted from an onboarding PR body?

**Comment by edmorley** [comment]
Yeah I copied them from the PR description in mozilla/treeherder#3025.

**Comment by edmorley** [comment]
Ah I see - what's shown in the onboarding PR isn't the commit messages - I've filed #1315 to adjust/clarify that.

In fact, that changes what I'll want to customise, since I think we'd prefer the commit message to include the `from <old version>` bit too, whereas currently only the PR body does.

**Comment by rarkins** [comment]
Don’t forget we combine all monorepo upgrades into a single commit without *any* version into though. Ie you can’t completely rely on getting versions in every case. 

However.. for monorepos that use synchronised versioning, I am thinking it’s feasible to include the version in those cases. 

Eg “Upgrade angular1 monorepo to v1.6.7” and it includes 6 packages all upgrading to 1.6.7

**Comment by edmorley** [comment]
> Don’t forget we combine all monorepo upgrades into a single commit without any version into though. Ie you can’t completely rely on getting versions in every case.

Ah I meant more in the single package case.



> However.. for monorepos that use synchronised versioning, I am thinking it’s feasible to include the version in those cases.

Good idea :-)

**Comment by edmorley** [comment]
Many thanks :-)
