### ISSUE TITLE
CLI exit code is 0 when errors occur

### ISSUE THREAD

**Issue by mymattcarroll** [renovateapp/renovate#1338]
Awesome project, extremely helpful for my team and I!

However, we are using the CLI directly in a privately hosted GitLab in a CI context and when errors occur, the exit code is still 0 and the Job reports that it successfully completes even though there were errors. 

E.g. if the token passed to the `--token` flag does have have the correct access required, this is the error we are seeing:

```
DEBUG: File config
       "config": {}
DEBUG: CLI config
       "config": {
         "repositories": ["278"],
         "logLevel": "debug",
         "platform": "gitlab",
         "endpoint": "https://git.blinkm.co/api/v4",
         "token": "***********"
       }
DEBUG: Env config
       "config": {}
 INFO: Renovating repository (repository=278)
DEBUG: assignPlatform (repository=278)
DEBUG: initRepo(278) (repository=278)
DEBUG: GET (repository=278)
       "path": "projects/278"
ERROR: GitLab init error (repository=278)
       "err": {
         "name": "GitLabError",
         "host": "git.blinkm.co",
         "hostname": "git.blinkm.co",
         "method": "GET",
         "path": "/api/v4/projects/278",
         "protocol": "https:",
         "url": "https://git.blinkm.co/api/v4/projects/278",
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "cache-control": "no-cache",
           "content-type": "application/json",
           "date": "Sun, 31 Dec 2017 11:41:59 GMT",
           "server": "nginx",
           "vary": "Origin",
           "x-frame-options": "SAMEORIGIN",
           "x-request-id": "0cbf28a6-4185-4fa8-96ba-ad8e7086e287",
           "x-runtime": "0.019600",
           "content-length": "35",
           "connection": "Close"
         }
       }
ERROR: Repository has unknown error (repository=278)
       "err": {
         "name": "GitLabError",
         "host": "git.blinkm.co",
         "hostname": "git.blinkm.co",
         "method": "GET",
         "path": "/api/v4/projects/278",
         "protocol": "https:",
         "url": "https://git.blinkm.co/api/v4/projects/278",
         "statusCode": 404,
         "statusMessage": "Not Found",
         "headers": {
           "cache-control": "no-cache",
           "content-type": "application/json",
           "date": "Sun, 31 Dec 2017 11:41:59 GMT",
           "server": "nginx",
           "vary": "Origin",
           "x-frame-options": "SAMEORIGIN",
           "x-request-id": "0cbf28a6-4185-4fa8-96ba-ad8e7086e287",
           "x-runtime": "0.019600",
           "content-length": "35",
           "connection": "Close"
         }
       }
DEBUG: Removing any stale branches (repository=278)
DEBUG: No branchList (repository=278)
 INFO: Finished repository (repository=278)
 INFO: Renovate finished
```

**Comment by rarkins** [comment]
@mymattcarroll you are right - there's no attempt in Renovate to return non-zero exit codes right now. I guess your use case is that you run it from CLI with one repository and if that repository completely fails then you want a non-zero?

Other cases, not so easy:
- Running with more than one repo and not all fail
- Errors that aren't completely fatal, e.g. a PR fails to be created but otherwise everything else is fine

**Comment by mymattcarroll** [comment]
@rarkins, apologies for the delay in my reply.

Considering the two example use cases you have specified, in my opinion, both should have a non-zero exit code.

> -   Running with more than one repo and not all fail

If one does not succeed, I was under the impression that the CLI `renovate` command was idempotent. I.e if a running on multiple repositories for the first time, PRs will be created. If running for a second time straight away, the it will not recreate the PRs. Is this correct? If so, why could this command not return a non-zero exit code to alert the user (or CI more importantly) that the command needs to be run again, or warrants investigation. If not, how would you know if PRs are not required for the repository or the `renovate` command is failing. 

> -   Errors that aren't completely fatal, e.g. a PR fails to be created but otherwise everything else is fine

Again, how would you know if PRs are not required for the repository or the `renovate` command is failing.

Surely, I am not the only person using the CLI in CI and not from the command line myself?

Please don't take my opinions the wrong way, this tool is amazing and the last thing I want is to make it sound like this tool is not useable in a CI context.

Cheers.

**Comment by rarkins** [comment]
Here's what I think we can do:
- edit the `logger.error` function to set `global.renovateError` to `true` any time we log an error
- when exiting Renovate, return exit code `1` if `global.renovateError` is `true`

**Comment by mymattcarroll** [comment]
Thanks @rarkins, awesome solution.

Just one quick thought based on the #1625.

Im not fully aware of the entire code base, but it might be better to set `process.exitCore = 1` instead of calling `process.exit(1)`.

See here: https://nodejs.org/docs/latest-v8.x/api/process.html#process_process_exitcode

> In most situations, it is not actually necessary to call process.exit() explicitly. The Node.js process will exit on its own if there is no additional work pending in the event loop. The process.exitCode property can be set to tell the process which exit code to use when the process exits gracefully.

**Comment by rarkins** [comment]
@mymattcarroll done, thanks
