### ISSUE TITLE
Configuration Error Feature Crashing Renovate

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/renovate#1339]
A recent change to Renovate (https://github.com/renovateapp/renovate/commit/eeefc3c8f3f5793bcf8392e6e212ef7604ff9407) added support for alerting a repository if their Renovate configuration is invalid.

The introduction of the feature is very timely (A configuration issue recently came up with two projects I'm responsible for renovating).

However, the feature seems to be crashing Renovate.

There are two repositories, as I mentioned earlier, that have mis-configuration. Therefore Renovate enters into the `error-config.js` code. 

It first [checks to see if the project has already been on-boarded](https://github.com/renovateapp/renovate/blob/b711e0c3aa03480a7d3b69e3e7a9346a00e3c774/lib/workers/repository/error-config.js#L15). If it has, it will submit a new issue against the project.

In both mis-configuration cases, the projects have been on-boarded (They both have a `renovate.json` file in their default branch).

However, the value of `config.repoIsOnboarded` is not set for both of those projects.

Therefore Renovate [proceeds to fetch](https://github.com/renovateapp/renovate/blob/b711e0c3aa03480a7d3b69e3e7a9346a00e3c774/lib/workers/repository/error-config.js#L26) the `renovate/configure` branch, which has been deleted on both of the mis-configured projects. As a result, the `pr` object is null, and the [line that attempts to retrieve the Pull Request number](https://github.com/renovateapp/renovate/blob/b711e0c3aa03480a7d3b69e3e7a9346a00e3c774/lib/workers/repository/error-config.js#L29) throws an exception.

**Comment by rarkins** [comment]
@destroyerofbuilds I'm unable to figure out why this is happening based on a code review. Could you help me with some more information so I can try to reproduce it?

1. Can you give an example of a misconfiguration that causes such crash?
2. Do you have any debug log you can share?

**Comment by rarkins** [comment]
Sorry never mind, I have reproduced it now
