### ISSUE TITLE
Cannot determine logic between chore and fix

### ISSUE THREAD

**Issue by kbrandwijk** [renovateapp/renovate#1340]
I'm wondering why some of the dependency updates have a `fix(deps)` PR while others have a `chore(deps)` PR. What is the logic for deciding between the two?

**Comment by rarkins** [comment]
package dpendencies are fix and devDependencies are chore. Both these are configurable though, so let me know if you want some other behaviour.

**Comment by kbrandwijk** [comment]
Minor updates to dependencies are supposed to be backwards compatible by the commit standards, so it does not make sense to me to release a new version until I actually use any of it. But if I can configure it, that's also fine.

**Comment by rarkins** [comment]
So you want fix only if it’s a major dependency update and chore for everything else?

**Comment by kbrandwijk** [comment]
Yes. Is there a way to specify this for specific dependencies too? That would be ideal.

**Comment by rarkins** [comment]
Yes it’s possible. I’ll respond with exactly how tomorrow

**Comment by rarkins** [comment]
So to begin with, the reason you are seeing the current behaviour is that Renovate's default preset for this is `:semanticPrefixFixDepsChoreOthers`. i.e. fix for dependencies and chore for others.

If you wished to reset everything to chore, you could add the preset `:semanticCommitTypeAll(chore)` to your `extends` array. It says to chore everything.

If you wish to then use `fix` only for major upgrades to `dependencies`, then you need to also add this configuration:

```json
  "dependencies": {
    "major":  {
      "semanticCommitType": "fix"
    }
  }
```

This is a more specific override than the earlier one, i.e. it essentially says "but for major updates of package.json>dependencies, use the "fix" semantic commit type".

Let's say you also have a dependency "foobar" that you think needs "fix" for minor updates too. In that case you need a packageRule:

```json
  "packageRules": [{
    "packageNames": ["foobar"],
    "minor": {
      "semanticCommitType": "fix"
    }
  }]
```

Combining all these together would look like:
```json
{
  "extends": ["config:base", ":semanticCommitTypeAll(chore)"],
  "dependencies": {
    "major": {
      "semanticCommitType": "fix"
    }
  },
  "packageRules": [
    {
      "packageNames": ["foobar"],
      "minor": {
        "semanticCommitType": "fix"
      }
    }
  ]
}
```

**Comment by kbrandwijk** [comment]
Wonderful! I'll experiment with this tomorrow.

**Comment by rarkins** [comment]
Yes, you can add `"automerge": true` in the same places where the `"semanticCommitType"` configuration options already are.

If you are making config changes feel free to always post an issue to https://github.com/renovateapp/config-help first for me to look at, or `@rarkins` me from any public PR and I should see it.
