### ISSUE TITLE
refactor: convert to monorepo

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1349]
There are probably many subcomponents of Renovate which could be spun out into their own npm modules, particularly ones like the validator which would be handy standalone.

The main reason holding this back until now has been the release process. Currently Renovate uses `semantic-release` to publish new versions to npmjs from Travis CI. I haven't seen a fully-working solution for combining semantic release and monorepos, and I prefer to not go back to a manual release process.

**Comment by rarkins** [comment]
Cc michaeltaranto

**Comment by rarkins** [comment]
An alternative - a bit hacky but maybe good enough - would be to create *separate* repositories for things like the validator and:

1. Add `renovate` as a devDependency
2. "require" deep into renovate's lib structure to use the validator
3. Use something like `rollup` to compile the resulting code
4. Publish the compiled file only to npmjs

**Comment by destroyerofbuilds** [comment]
The closest I've seen is Lerna with the [`--yes` option](https://github.com/lerna/lerna#--yes).
