### ISSUE TITLE
Bug: Docker updates do not adhere to the branchPrefix configuration

### ISSUE THREAD

**Issue by michaeltaranto** [renovateapp/renovate#1350]
[Our configuration](https://github.com/seek-oss/renovate-config-seek/blob/master/package.json#L28) specifies a `branchPrefix` as `renovate--`, which is working for our npm dependencies. However our Docker dependencies are still coming through with the default `renovate/` prefix. The `/` causes us issues with container paths in our CI (which is why we customise this in the first place).

I did have a quick look through the code but the bug wasn't immediately obvious to me. I might have a bit more of a look later but thought i'd raise the issue if it's a quick one for someone more familiar with the codebase 😉

**Comment by rarkins** [comment]
That's really weird. I did a quick code search for the string `renovate/` and all looks well. Templates are located here: https://github.com/renovateapp/renovate/tree/master/lib/config/templates and any I checked all seem to use ``{{branchPrefix}}`.

My best guess is that the config overriding `branchPrefix` is perhaps not being applied at the right time for Docker, in which case it's not an obvious fix. I can take a look later today.

**Comment by rarkins** [comment]
I'm not able to reproduce this at first attempt. Check out https://github.com/renovate-tests/docker-prefix/pull/1

**Comment by rarkins** [comment]
Are you putting your config in your `package.json` ?

**Comment by rarkins** [comment]
I think you will need to put your config into a `renovate.json` file (not `package.json`) until I implement this feature: https://github.com/renovateapp/renovate/issues/1323

i.e right now config in a `package.json` only applies to that actual `package.json` file. This was fine when only `npm` was in use, but now needs this improvement.

**Comment by michaeltaranto** [comment]
Ok that makes a bit more sense. Let me try pulling it out of `package.json` and see how that goes. I'll let you know, thanks 👏

**Comment by michaeltaranto** [comment]
I have switched out from `package.json` to a `renovate.json` file for configuration. Since then i seen Renovate refresh any of it's PRs. Does it autodetect changes on a repo when the configuration moves?

**Comment by michaeltaranto** [comment]
Is there a default schedule for picking up changes?

**Comment by rarkins** [comment]
@michaeltaranto it should be running again right away whenever you add or edit a `renovate.json`. Then there's also a randomised hourly batch queue for all repos which should catch anything that's missed.

I'll check my webhook logic today to make sure that's still happening for the `renovate.json` case.

**Comment by rarkins** [comment]
@michaeltaranto did the configuration change take effect as you expected, once Renovate eventually re-ran?

**Comment by rarkins** [comment]
I think this was the first time it detected `renovate.json`:
```
{"name":"renovate","level":20,"repository":"SEEK-Jobs/**redacted**","msg":"renovate.json exists","time":"2018-01-08T22:04:44.874Z"}
```

I *think* that should have been before your comment here - it's 10:04pm UTC and GitHub says your comment was 11:22pm UTC.

I checked the logs and saw something strange - both `branchprefix` and `branchPrefix`. I think this was the culprit: https://github.com/singapore/renovate-config/commit/335ba04359d6b52236bc14e413f7d771a7ecec17

Sorry about that

**Comment by michaeltaranto** [comment]
Once the config was detected it took affect as expected. Although because I closed the last docker PR I'm not expecting another PR until the next version of the container is released which means I can't confirm the `branchPrefix` is correct yet.

Took a while for the first PR after the config change to come through but nice to know about the hourly sweeper process. 

Aside from this day one was awesome, very excited about this 🙌👏
