### ISSUE TITLE
Add validator

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1352]
Inspiration: https://github.com/seek-oss/renovate-config-seek/blob/master/test.js

Advanced:
- Look for `renovate.json`, `.renovaterc` and `.renovaterc.json`
- Look for `renovate` or `renovate-config` within any `package.json` within the repo

Bundle it up and publish only the "dist" so that the total install is not too large (renovate itself includes `npm` and `yarn` so it's pretty heavy).

I think we should publish this with a scope, e.g. `@renovate/validate`. Doing so will also mean that it could be pulled back into a monorepo later if so desired (#1349).

**Comment by rarkins** [comment]
Cc @michaeltaranto markdalgleish

**Comment by destroyerofbuilds** [comment]
👍 as several teams I work with have expressed an interest in a means to validate Renovate configuration changes after the on-boarding process.

**Comment by rarkins** [comment]
When you install `renovate` from npmjs, it now comes with both the `renovate` binary as well as a `renovate-config-validator` binary. Running it in a project will result in it validating `renovate.json`, `.renovaterc`, `.renovaterc.json` and any renovate config inside `package.json`.

This package may be split away from the regular `renovate` one in future once there is a better way to compile it without requiring the "full" Renovate dependencies, but for now I will close this issue. Please create a new issue if you have further requirements.
