### ISSUE TITLE
Pin package.json dependencies using lock files

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1362]
Currently, we pin `package.json` dependency versions using the latest in the range in `npmjs`. The problem with this is that these latest versions might *break* the build.

If the project uses a `yarn.lock` or `package-lock.json`, Renovate should instead determine what was the last "locked" version from those and pin to that instead. Assuming the last locked versions passed tests, it should increase the chance that the Pin Dependencies PR also passes tests.

**Comment by hkdobrev** [comment]
That would definitely make me more willing to pin dependencies from the start since it would start with the ones from the our already generated lock file.
