### ISSUE TITLE
Combine @types upgrades with regular upgrade

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1365]
e.g. upgrade `@types/source-map` with `source-map`

**Comment by pvinis** [comment]
This is done? I notice that `react-native` and `@types/react-native` dont go together. Is there somewhere I can send a PR for this?

**Comment by rarkins** [comment]
Please create a new issue to discuss, ideally with a simple reproduction repository

**Comment by pvinis** [comment]
Created #4893
