### ISSUE TITLE
Using --renovate-fork=true on a repo without a renovate.json doesn't work.

### ISSUE THREAD

**Issue by mastermatt** [renovateapp/renovate#1371]
Setting up renovate on a fork is confusing.

I wanted to take Renovate for a test drive before installing it as a Github app.
I ran `npm install -g renovate` then tried `renovate  --token <...> --renovate-fork=true  user/repo` only to be presented with:
> Repository is a fork and not manually configured - skipping

Given the use of `--renovate-fork=true`, I was pretty sure that I was manually configuring that option, yet no onboarding PR.

The logic in the [repo config](https://github.com/renovateapp/renovate/blob/80bed05146282a292ebc8c12bb03507d84245cc3/lib/workers/repository/configured.js) led me to believe it should just work until I debugged my way to the [onboarding branch](https://github.com/renovateapp/renovate/blob/228b823e45febed8d8ad09479ed832511adca13a/lib/workers/repository/onboarding/branch/index.js#L14-L16) which does not share the same `if (config.isFork && !config.renovateFork)` statement.

It's unclear to me if this is a small bug and `onboarding/branch/index.js` just needs its `if` statement updated or if there is a legitimate reason why forks can't have an onboarding PR. If it's the latter I'd suggest different verbiage in the error output that states a `renovate.json` needs to be manually added first.

**Comment by rarkins** [comment]
Sounds to me like we can update the `if` in onboarding. My intention as an administrator was to skip all forks by default but include them if they have a config including `renovateFork`. But if it run your own instance I can’t see anything wrong with it.

**Comment by mastermatt** [comment]
I'll open a PR.
