### ISSUE TITLE
bug: Branch prefix not working with gitLab platform

### ISSUE THREAD

**Issue by jvetyska** [renovateapp/renovate#1384]
I have just realized that even through I was always setting the branchPrefix option in the config.js, all dependency level branches were still using the default /renovate/eslint... format.
It looks like the branchPrefix config option is never read or it gets overwritten somewhere.
`config.branchPrefix` returns undefined.

Setting in config.js, for example:
`branchPrefix: "chore/WQ-0_renovate_",`
Results in default branch format, such as: renovate/eslint-4.x

The only way to get around it is to actually overwrite the branchName in the config:
`branchName: "chore/WQ-0_renovate_{{depName}}-{{newVersionMajor}}.x",`
This will work and correct branch names are used.

**Comment by rarkins** [comment]
The “config:base” preset sets the branchPrefix, so ifnyoive configured that preset in the repository then it will override anything configured in the client’s `config.js`

**Comment by rarkins** [comment]
@jvetyska can you confirm if the repository config has a preset defined there? i.e. which would override the `config.js` setting?

**Comment by jvetyska** [comment]
It's just the standard config that onboarding creates:
`{
  "extends": [
    "config:base"
  ]
}`

**Comment by rarkins** [comment]
Yes, those presets override your config.js if they have overlap. You can delete that preset and your client settings will be used. It’s recommended to use raw config and not presets in the client.js.

**Comment by jvetyska** [comment]
I see. This may a bit counter intuitive, from the standpoint of following setup instructions.
Especially because the onboarding will work correctly with the config.js, so one would assume it's ready to go, but second run will fail when renovate will force these defaults automatically. 
It would seem that if the settings have certain default already, why would a generic config:base overwrite those default to the same value and thus mess up expected behavior? 
I think for predictable and intuitive behavior, it would be best not to include the config:base in the default renovate.json or remove some of the overrides from the config:base setup so that users don't get unpredictable behavior out of the box. 
There are still lots of helpful settings in the base config, so it would make sense if it didn't set those things that are already set by default value, but especially related to branches.
It is much easier to set the branch behavior in the global config.js once, then to maintain dozens of renovate configs in the repo.

**Comment by rarkins** [comment]
One of the ideas of including default settings on that base was that the *tool*'s default settings could change over releases (ideally in a major release to indicate breaking changes) but those with the base config could still get the same functionality.

But I agree that it's frustrating to see it overriding `config.js` settings *unnecessarily*, e.g. like `branchPrefix`. I think that's one that I can probably leave out of the base description anyway, as the large majority of users do not change it anyway. An alternative is to leave it in as description-only but with actual config inside, therefore giving users the description without overriding anything.

**Comment by jvetyska** [comment]
That would be perfect! 
I would agree, that leaving things in commented out makes it easy to be aware of other options and enable them if that makes sense.

**Comment by rarkins** [comment]
I've decided to leave the `config:base` preset as-is. since the above comments, some related points:

1. The default onboarding config is now configurable by bot owners, so you are free to define your own `config:base` equivalent
2. In the next major release, I will make the *app* (with no presets) defaults less opinionated so that they are easier to override
