### ISSUE TITLE
Received an undefined error in an issue from Renovate

### ISSUE THREAD

**Issue by ryansmith94** [renovateapp/renovate#1388]
Hey guys, I've received a strange issue from Renovate saying "Action Required: Fix Renovate Configuration", but the error type is undefined in the initial comment and I'm using the same config in other repositories.

> There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop renovations until it is fixed.
> 
> Error type: undefined

https://github.com/HT2-Labs/jscommons/issues/27

**Comment by rarkins** [comment]
@ryansmith94 I'll take a look

**Comment by rarkins** [comment]
I forced a manual renovation just now and it's closed the issue, meaning that whatever problem it thought was there before is now gone. Most likely it would have cleared soon of its own accord as the repo was queued up for its hourly renovation already anyway. I will follow up by looking at the log from when the issue was created, to see how we can handle it better in future.

**Comment by ryansmith94** [comment]
That's great thanks Rhys! Do you ever rest haha? You respond so quickly.

**Comment by rarkins** [comment]
I hate "user facing" errors so always try to jump on them pretty quickly! 

Confirmed that it was an npm backend error causing it:
```
{
  "name": "renovate",
  "level": 30,
  "repository": "HT2-Labs\/jscommons",
  "err": {
    "name": "HTTPError",
    "host": "registry.npmjs.org",
    "hostname": "registry.npmjs.org",
    "method": "GET",
    "path": "\/@ht2-labs%2Frenovate-config",
    "protocol": "https:",
    "url": "https:\/\/registry.npmjs.org\/@ht2-labs%2Frenovate-config",
    "statusCode": 503,
    "statusMessage": "first byte timeout",
    "headers": {
      "server": "Varnish",
      "retry-after": "0",
      "content-type": "text\/html; charset=utf-8",
      "content-length": "448",
      "accept-ranges": "bytes",
      "date": "Sun, 14 Jan 2018 16:34:00 GMT",
      "via": "1.1 varnish",
      "connection": "close",
      "x-served-by": "cache-sea1032-SEA",
      "x-cache": "MISS",
      "x-cache-hits": "0",
      "x-timer": "S1515947609.276348,VS0,VE30985"
    }
  },
  "msg": "npm registry failure",
  "time": "2018-01-14T16:34:00.264Z"
}
```

I will modify the the code so that this type of external error is thrown all the way so that the repository renovation is either aborted or ideally retried from scratch.

**Comment by rarkins** [comment]
Please leave this issue open, I will use it as the basis for better handling and retrying npmjs 503's.

**Comment by ryansmith94** [comment]
Yeah I know what you mean. It's really awesome and I really appreciate your dedication here!

Nice, some good logging right there. Okay that sounds great.

Will do, okay, thanks again Rhys 👍  enjoy the rest of your weekend :smile:

**Comment by rarkins** [comment]
Thanks, you too. I've pushed a fix now that should hopefully avoid repositories getting Config Validation warnings (as a result of presets not found) when the error is actually an npmjs internal one. Will be live in the app in about 10 minutes. npmjs seems to have settled down though so I'm hoping that any other affected repositories should have their Issue closed by now too, although they'll undoubtedly be confused.

**Comment by ryansmith94** [comment]
Thanks 👍  That's awesome, thank you! Yeah I'm sure they will haha.
