### ISSUE TITLE
[docs] packageRules: or a way to group related deps, or a whitelist of what to upgrade?

### ISSUE THREAD

**Issue by dylang** [renovateapp/renovate#1428]
This might be a documentation issue for `packageRules`:

https://renovateapp.com/docs/configuration-reference/configuration-options#packagerules

We're still having trouble with Renovate ignoring most of our dependencies, and I realized maybe we don't understand `packageRules` from the docs. 

We're using it to group related dependencies, like `estlint`, `graphql/apollo`, `webpack`, `react`, etc. Very cool!

But we have 100 or so other dependencies that don't belong in any particular group, and should be upgraded independently. 

What should be done so all packages get upgraded, but only some are grouped using `packageRules`?

Thanks!

**Comment by rarkins** [comment]
> We're still having trouble with Renovate ignoring most of our dependencies

Sounds like you have some bad packageRules defined.

So you know, the `config:base` preset includes `group:monorepos`, which is a kind of autogenerated set of definitions of known "monorepos" like react, jest, babel, etc. So if you include either "config:base" or "group:monorepos" then you will get that part for free. After that, it's up to you to define any extra groups you want.

For tips on that, please see https://renovateapp.com/docs/all-other/faq and search for occurrences of "packageRules". Let me know here if you have a requirement that's not described there and not obvious how to do.

You are also welcome to post whole or partial configs for review at https://github.com/renovateapp/config-help

**Comment by rarkins** [comment]
In case it wasn't obvious, keeping packages "upgraded independently" is the default behaviour, except for the monorepos groupings described above. So any difference to that is probably based on incorrect rules you're adding, maybe if you don't know that they get independent upgrades by default without any rules necessary.

**Comment by edmorley** [comment]
Also if any of your groups are ones that others may wish to use, then they can always be upstreamed into the base config (example: https://github.com/singapore/renovate-config/pull/10) to simplify your config.

**Comment by dylang** [comment]
Thanks @rarkins and @edmorley - I've added our config and a recent log to https://github.com/renovateapp/config-help/issues/10
