### ISSUE TITLE
lerna bootstrap support

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1441]
Transferring from discussions in #1407 

Renovate needs logic to run `lerna bootstrap` in lerna repositories using lockfiles instead of `npm install`. Otherwise some unpublished internal modules may fail the install if not bootstrapped first.

Requirements:
- [ ] Detect when `lerna` is in use and `package-lock.json` found next to `lerna.json`
- [ ] Whenever a package is updated in subfolders, do not run `npm install` locally, instead run `lerna bootstrap` from root (similar to how we run `yarn install` from root)
- [ ] Use the same version of `lerna` as defined in `devDependencies` in root `package.json`

**Comment by rarkins** [comment]
@ctaepper I would like to make sure I understand these requirements fully:

> renovate should execute npm install --package-lock-only in order to handle the root dependencies

Do you mean that in cases where only the root `package.json` is updated, we only need `npm install` and not `lerna bootstrap`? Because if we're running `package-lock-only` and not actually installing any modules then I assume it's not a "prerequisite" of `lerna bootstrap`?

> `lerna bootstrap` might be configured as `postinstall` script of the project root, i'm not sure if this is triggered by `npm install --package-lock-only`

I also run with `--ignore-scripts` for security reasons so we can hopefully skip that if it's `postinstall` and instead do it manually.

**Comment by rarkins** [comment]
Regarding `lerna` version, we might be able to use [npx](https://www.npmjs.com/package/npx) for that, because it comes bundled with `npm` now anyway.

e.g. we can parse the root `package.json > devDependencies > lerna` value and then run something like `npx lerna@2.8.0 bootstrap -- --package-lock-only`

**Comment by rarkins** [comment]
@ctaepper thanks for offering to help out on this one. The most valuable thing you could do right away is:

1. Create the simplest possible monorepo in a public repository that we can use to test this solution with, e.g. one that fails with `npm install` but works with `lerna bootstrap`. Please don't use env variable substitution or private registries, to keep it as simple as possible.

2. Test out using `npx` to run `lerna` on your *real* (internal) repository to make sure that works. If so then I think we've found the best way to run the exact version of `lerna` necessary

**Comment by ctaepper** [comment]
@rarkins I can confirm npx works with lerna, we are actually using it in our projects in CI and docker generation

will try to create the repo asap

**Comment by rarkins** [comment]
> 2. don't care about the hoist mode and always run `npm install && lerna bootstrap` becuase this will always update any lockfile which needs updating

I don't mind this option as it simplifies logic. And especially if detection can be unreliable anyway.

BTW when we are ready to start, let's work again from your fork, as then we can both easily edit. You may want to delete and re-fork it though once the first PR is merged.

**Comment by ctaepper** [comment]
yeah sure, go ahead and ping me, when you merged the first PR, I will create the next one for WIP

**Comment by rarkins** [comment]
Could you:
- delete and re-fork
- create a branch `feat/1441-lerna-bootstrap` (allows us to later split the work into other feature branches if necessary)
- add some dummy commit we can revert later, so the diff is not empty, e.g. to readme.md
- Create a WIP PR back to this repo so we can begin work on it

**Comment by ctaepper** [comment]
here we go
