### ISSUE TITLE
bug: renovate fails when encountering git@repository references

### ISSUE THREAD

**Issue by jvetyska** [renovateapp/renovate#1464]
For some reason, when running renovate it chokes on a dependency reference in the format:
in package.json:
`git+ssh://git@gitlab.domain.com:project/redesign/dpl.git#v1.2.18`
when then is trying to execute:
`/usr/bin/git ls-remote -h -t git@gitlab.domain.com:project/redesign/dpl.git`
but results in shell asking to enter password instead.

Calling that shell command on it's own is no problem, I don't need to log in anywhere, that makes no sense.

I can see that it's trying to execute this in file npm.js:
`({ stdout, stderr } = await exec(cmd, {`

Because it works fine when I execute that command in the same terminal on it's own, I don't understand how I could debug this any further. 

Locally starting with: 
`LOG_LEVEL=debug npm run start -- --platform=gitlab --token=xyz --endpoint=https://gitlab.domain.com/api/v4`

**Comment by rarkins** [comment]
Is it Renovate having the problem directly or is it when we call out to npm or yarn?

**Comment by jvetyska** [comment]
I don't know if it was clear, it's when the execution of the shell commands
is done.
But only within execution of Renovate.




On Jan 30, 2018 9:14 PM, "Rhys Arkins" <notifications@github.com> wrote:

Is it Renovate having the problem directly or is it when we call out to npm
or yarn?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/renovateapp/renovate/issues/1464#issuecomment-361826232>,
or mute the thread

**Comment by rarkins** [comment]
In that case it’s either `npm` or `yarn` within that shell failing. We don’t invoke any git commands directly.

**Comment by rarkins** [comment]
Can you provide an open source repo that can be used to replicate the problem? Ideally as small as possible to isolate the fault

**Comment by rarkins** [comment]
Closing in favour of #817
