### ISSUE TITLE
Use existing yarn.lock when rebasing

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1481]
If branch `renovate/a-1.x` needs rebasing then many times the lock file in that branch will remain unchanged. We should use the copy from the branch instead of the one from the base branch.

**Comment by edmorley** [comment]
I think this would mean that a stale lock file would be used instead?

ie:
If the transient deps of `a@1.x` had since had some updates of their own, I would rather the yarn.lock include those, and not remain at the older versions of those sub-deps when `renovate/a-1.x` was updated.

**Comment by rarkins** [comment]
@edmorley the lock file is "holding back" transient dependencies all the time, and I don't think it's worth handling specially just one of the many cases when we can't handle them all. Meaning that transient dependencies are being updated probably non-stop, and everyone's lock files are holding them back "by design".

Also, if transient dependencies have updated, it means they were updated well after `a@1.x` was released too. This use case is nearly always for when people configure `rebaseStalePrs=true` and means that a simple rebase for non-`package.json` reasons shouldn't result in a branch failing when it previously passed.
