### ISSUE TITLE
Semantic Commit Scope

### ISSUE THREAD

**Issue by adam-moss** [renovateapp/renovate#1504]
Is it possible to have the package name as the semantic commit scope?  So rather than `chore(deps)` or `fix(deps)` it would be, for example `chore(eslint)` etc?

**Comment by rarkins** [comment]
Try setting scope to `{{depName}}` - might work

**Comment by rarkins** [comment]
You might end up with some pretty long semantic prefixes though

**Comment by adam-moss** [comment]
Hmm.  So with config options:

```js
    commitMessage: '{{semanticPrefix}}Update {{depName}} to {{newVersion}}',
    semanticCommits: true,
    semanticCommitType: 'chore',
    semanticCommitScope: '{{depName}}',
```

The MR ends up with a title of `chore(snyk): update dependency snyk to v1.69.7` (so it appears the commit scope has been used) but the commits themselves have `chore({{depName}}): update snyk to 1.69.7`

**Comment by rarkins** [comment]
Look old like the commitMessage could do with a second handlebars compile
