### ISSUE TITLE
group:definitelyTyped creates PR with other deps.

### ISSUE THREAD

**Issue by mastermatt** [renovateapp/renovate#1512]
My assumption is that issue is related to the comment @rarkins made in https://github.com/singapore/renovate-config/pull/17.

> I'm also not 100% sure if there will be any unintended side effects of this rule with some custom `@types` handling already embedded in the app - namely that by default we implicitly group any types package with its non-types sibling. However even if there is a side effect, it can be fixed in the Renovate source code as there's nothing fundamentally stopping this concept.

After updating the config to:
```json
   "renovate": {
     "extends": [
       "config:base",
       "group:definitelyTyped"
     ]
   }
```
...a PR was created with the title of `Update definitelyTyped packages` and the following changes to the `package.json`.

```diff
diff --git a/package.json b/package.json
index fff90e5..df7a665 100644
--- a/package.json
+++ b/package.json
@@ -16,16 +16,16 @@
   "dependencies": {
     "@types/hystrixjs": "2.1.33",
     "@types/request": "2.47.0",
-    "@types/request-promise-native": "1.0.12",
+    "@types/request-promise-native": "1.0.13",
     "@types/statsd-client": "0.4.0",
     "bunyan": "1.8.12",
     "debug": "3.1.0",
     "hystrixjs": "0.2.0",
     "lodash": "4.17.5",
-    "newrelic": "2.6.1",
+    "newrelic": "2.7.1",
     "request": "2.83.0",
     "request-promise-native": "1.0.5",
-    "rxjs": "5.5.2"
+    "rxjs": "5.5.6"
   },
   "devDependencies": {
     "@types/bunyan": "1.8.4",
@@ -33,19 +33,19 @@
     "@types/chai-as-promised": "7.1.0",
     "@types/debug": "0.0.30",
     "@types/express": "4.11.1",
-    "@types/lodash": "4.14.97",
-    "@types/mocha": "2.2.46",
-    "@types/nock": "9.1.1",
+    "@types/lodash": "4.14.102",
+    "@types/mocha": "2.2.48",
+    "@types/nock": "9.1.2",
     "@types/node": "8.5.8",
     "@types/sinon": "4.1.3",
     "chai": "4.1.2",
     "chai-as-promised": "7.1.1",
-    "mocha": "4.1.0",
+    "mocha": "5.0.0",
     "nock": "9.1.6",
-    "sinon": "4.1.6",
+    "sinon": "4.2.2",
     "ts-node": "4.1.0",
     "tslint": "5.9.1",
-    "typescript": "2.6.2"
+    "typescript": "2.7.1"
   },
```
Note: the `yarn.lock` was also updated but I didn't include it here for brevity. 

The expectation would be that `newrelic`, `rxjs`, `mocha`, `sinon`, and `typescript` would be upgraded in different PRs.

It's unclear if `mocha` should be it's own PR or if `@types/mocha` should join it. 
I'm fine with either way. Reading through https://github.com/renovateapp/renovate/issues/519, it seems we're on the right track for `@types` already. 
I just want to be able to group all the `@types` in one PR that are not related to source upgrades.

Let me know if I can provide more info to help reproduce the issue or if I can provide a PR for anything.

**Comment by rarkins** [comment]
Is your whole config really just `config:base` and `group:definitelyTyped` ? I can't say I predicted it to be quite like that! But if you can confirm it and I can reproduce it based on your dependencies above, we should be able to fix it. I think that if you configure such a grouping explicitly then it should override any implicit grouping built into the app, i.e. you should only see `@types/*` in this PR and the rest are on their own.

**Comment by rarkins** [comment]
I can reproduce it, will look into what fix is required

**Comment by rarkins** [comment]
@mastermatt turns out it was the preset that was incorrect rather than Renovate. I fixed the preset and now get the result we expected, so please try again.

**Comment by mastermatt** [comment]
That did the trick, thanks.
