### ISSUE TITLE
semanticScope uses last depName when pinning dependencies

### ISSUE THREAD

**Issue by adam-moss** [renovateapp/renovate#1514]
For config

```js
    commitMessage: '{{semanticPrefix}} update to {{newVersion}}',
    pinVersions: true,
    semanticCommits: true,
    semanticCommitType: 'chore',
    semanticCommitScope: '{{depName}}',
```

when the initial MR is to pin dependencies the semanticPrefix given in the commit message reflects the last {{depName}} identified.

```js
chore(typescript): pin dependencies
```

Suggest in this use case the semanticCommitScope should be null, or something else.

**Comment by rarkins** [comment]
This is fixable via configuration, e.g.

```
  "pin": {
    "semanticCommitScope": "packages"
  }
```
