### ISSUE TITLE
Renovate does not modify package-lock.json correctly

### ISSUE THREAD

**Issue by sarunint** [renovateapp/renovate#1528]
Last week, renovate updated `firebase` from 4.9.1 to 4.10.0 and it break my test. After some digging, I found out that the lock file has been modified incorrectly.

What I suspect is, many of `firebase` dependencies, namely `@firebase/app`, `@firebase/database`, `@firebase/firestore`, `@firebase/messaging`, `@firebase/polyfill` and `@firebase/storage`, had been moved from top level of `package-lock.json` to be in `dependencies` key of `firebase` package.

Dependencies of `firebase@4.9.1`
![image](https://user-images.githubusercontent.com/3850197/36352663-eceb20ba-14ee-11e8-8d7a-c4a2a267382e.png)

Dependencies of `firebase@4.10.0`
![image](https://user-images.githubusercontent.com/3850197/36352658-de3ac50c-14ee-11e8-9577-876ab3ebec8b.png)

Excerpt of `package-lock.json` before updating:

```
{
  "name": "npm-test",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "@firebase/app": {},
    "@firebase/app-types": {},
    "@firebase/auth": {},
    "@firebase/auth-types": {},
    "@firebase/database": {},
    "@firebase/database-types": {},
    "@firebase/firestore": {},
    "@firebase/firestore-types": {},
    "@firebase/messaging": {},
    "@firebase/messaging-types": {},
    "@firebase/polyfill": {},
    "@firebase/storage": {},
    "@firebase/storage-types": {},
    "@firebase/util": {},
    "@firebase/webchannel-wrapper": {},
    "firebase": {
      "version": "4.9.1",
      "resolved": "https://registry.npmjs.org/firebase/-/firebase-4.9.1.tgz",
      "integrity":
        "sha512-PMZCkju+Fs2DvtKxuuQPRxWq2fvlgmGXeNF2kHVNeZ1x+cA2OKrC3+HzbmjrgMChFejvFJrqPiPGPv/I3odhrQ==",
      "requires": {
        "@firebase/app": "0.1.8",
        "@firebase/auth": "0.3.3",
        "@firebase/database": "0.1.9",
        "@firebase/firestore": "0.3.2",
        "@firebase/messaging": "0.1.9",
        "@firebase/polyfill": "0.1.4",
        "@firebase/storage": "0.1.6",
        "dom-storage": "2.0.2",
        "xmlhttprequest": "1.8.0"
      }
    }
  }
}
```

Excerpt of `package-lock.json` after updating:

```
{
  "name": "npm-test",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "@firebase/app-types": {},
    "@firebase/auth": {},
    "@firebase/auth-types": {},
    "@firebase/database-types": {},
    "@firebase/firestore-types": {},
    "@firebase/messaging-types": {},
    "@firebase/storage-types": {},
    "@firebase/webchannel-wrapper": {},
    "firebase": {
      "version": "4.10.0",
      "resolved": "https://registry.npmjs.org/firebase/-/firebase-4.10.0.tgz",
      "integrity":
        "sha512-d/Z2BDoR3NpUhHxuedMK3XleMqs9rdlrfjrPcEMwl9fy+FoyWZV9inqMXRT/ec3bbrUycTZL4TWhS9GZD5M0iw==",
      "requires": {
        "@firebase/app": "0.1.9",
        "@firebase/auth": "0.3.3",
        "@firebase/database": "0.1.10",
        "@firebase/firestore": "0.3.3",
        "@firebase/messaging": "0.2.0",
        "@firebase/polyfill": "0.1.5",
        "@firebase/storage": "0.1.7",
        "dom-storage": "2.0.2",
        "xmlhttprequest": "1.8.0"
      },
      "dependencies": {
        "@firebase/app": {},
        "@firebase/database": {},
        "@firebase/firestore": {},
        "@firebase/messaging": {},
        "@firebase/polyfill": {},
        "@firebase/storage": {},
        "@firebase/util": {}
      }
    }
  }
}
```

The problem is, these two lockfiles generate different structure which could lead to errors.

The way I currently solve this problem is to manually run `npm dedupe` to bring the sub-dependencies to the root. But it's kinda hacky. Is this the way intended? I don't think so.

I think this maybe because `--package-lock-only` flag of `npm install` but I'm not sure.

**Comment by rarkins** [comment]
Any package lock updating is done via `npm` child process so unlikely to be Renovate’s direct problem. However if you can provide a full `package.json` and lock file that can reproduce the problem then I can raise this as a bug to npm.

**Comment by sarunint** [comment]
I've posted an issue here: npm/npm#19852, you can check it there.

**Comment by rarkins** [comment]
Thanks, I've added a comment to that issue too. I'm thinking whether to remove `package-lock.json` files before `npm install --package-lock-only` as a workaround.

**Comment by rarkins** [comment]
@sarunint Based on my testing, it seems that using a "cached" `package-lock.json` causes this problem, so I have temporarily disabled writing these lock files before running `npm install --package-lock-only` so that `npm` generates the lock file from scratch each time. This increases the lock file generation time a lot, but at least should produce correct lock file again until the npm issue is fixed.
