### ISSUE TITLE
Renovating Engines Crashes on GHE

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/renovate#1540]
I began testing the new Renovate feature that allows upgrading the `node` engines property in a `package.json` file. It seems to be attempting to fetch Node release information from an on-premise GHE instance instead of `github.com`.

```bash
INFO: Checking node engine (repository=hbetts/node-version-test, packageFile=package.json, depType=engines)
DEBUG: GET repos/nodejs/node/releases?per_page=100 [retries=5] (repository=hbetts/node-version-test, packageFile=package.json, depType=engines)
ERROR: Repository has unknown error:
       {
         "name": "GitHubError",
         "host": "github.example.com",
         "hostname": "github.example.com",
         "method": "GET",
         "path": "/api/v3/repos/nodejs/node/releases?per_page=100",
         "protocol": "https:",
         "url": "https://github.example.com/api/v3/repos/nodejs/node/releases?per_page=100",
```

**Comment by rarkins** [comment]
Same problem as we had with changelogs, I'll try to fix now.

**Comment by destroyerofbuilds** [comment]
Works great @rarkins!

---

![node-upgrade](https://user-images.githubusercontent.com/10657293/36449807-8b8b3364-1651-11e8-843f-c9ead84aedff.png)

**Comment by rarkins** [comment]
Sorry for the initial inconvenience!

**Comment by nathanpower** [comment]
Just to note, still seeing this (or similar) on v13.39.1

```
 INFO: Error retrieving from github (repository=org/repo)
       "repo": "nodejs/node",
       "err": {
         "name": "GitHubError",
         "host": "github.example.com",
         "hostname": "github.example.com",
         "method": "GET",
         "path": "/api/v3/repos/nodejs/node/tags?per_page=100",
         "protocol": "https:",
         "url": "https://github.example.com/api/v3/repos/nodejs/node/tags?per_page=100",
         "statusCode": 404,
         "statusMessage": "Not Found",
```

**Comment by rarkins** [comment]
@nathanpower can you describe how you’re configuring Renovate? Eg 100% CLI, 100% env, a mix, etc?

**Comment by nathanpower** [comment]
Sure, we have a module that wraps the renovate CLI. The wrapper module is mostly concerned with resolving the `repositories` field in the config. Configuration is exported from `config.js` and overridden when needed in the target repos via `renovate.json`. Process runs nightly on a Jenkins server, and uses `GITHUB_TOKEN` and `GITHUB_COM_TOKEN` for auth. Anything else that would be useful to know?

**Comment by rarkins** [comment]
How do you configure endpoint? Can you try using GITHUB_ENDPOINT if not already?

**Comment by nathanpower** [comment]
It's set to our GHE API endpoint in `config.js

```JS
module.exports = {
    endpoint: 'https://github.example.com/api/v3/'
}
```
