### ISSUE TITLE
Upgrade Up To But No Further Than

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/renovate#1555]
We have several teams developing Angular JS (1.x) applications and libraries.

We use a common configuration (scaffolded by default thanks to #1521) to ensure a consistent experience across our community.

For _reasons_ (cost, and the need to upgrade in sync) we're using Angular 1.5 across our organization, and no projects, application or library, are allowed to upgrade past that version.

We know we can disable upgrade PRs for Renovate in our common configuration, but it doesn't quite capture what we're trying to achieve.

While we don't want anyone to upgrade past version 1.5, we do have a few projects on lower versions that we want to receive upgrade PRs.

Therefore, what we're trying to say is "submit upgrade PRs up to, and including, AngularJS 1.5".

**Comment by rarkins** [comment]
I assume that using a patch-only config for sngular as a workaround doesn’t work because some repositories might still be on < 1.5?

My first idea for this is to have a new field named something like `versionRange` that could be added to a packageRule and needs to be a valid server version or semver range. Eg you could set it to “1.5.x” or “1.5” or “~1.5.0” or even “< 1.6” in this case.

**Comment by destroyerofbuilds** [comment]
> I assume that using a patch-only config for sngular as a workaround doesn’t work because some repositories might still be on < 1.5?

Our shared configuration has `major` and `minor` upgrades disabled for AngularJS. 

Though, as you noted, it means we have disabled Angular upgrades for projects that may still need to adopt 1.5.

> that could be added to a packageRule

We've begun adopting the `packageRules` field for managing common libraries, such as AngularJS and TypeScript, so adding additional rules under `packageRules` would be intuitive for us.

> needs to be a valid server version or semver range. Eg you could set it to “1.5.x” or “1.5” or “~1.5.0” or even “< 1.6” in this case.

What would the value mean?

If my value is `^1.5.0`, does that mean Renovate may submit `minor` and `patch` upgrades as long as they are satisfied by that range?
