### ISSUE TITLE
PR opened before unpublish-safe passed

### ISSUE THREAD

**Issue by edmorley** [renovateapp/renovate#1580]
Hi :-)

Our Renovate configuration includes `:prNotPending` and `:unpublishSafe`, however mozilla/treeherder#3295 was opened at 2018-03-02 20:09 UTC - when the package was only published at `2018-03-02T19:55:26.091Z` according to `yarn info auth0-js@9.3.2 time`, and as such the unpublish-safe check is still marked as pending.

**Comment by rarkins** [comment]
Solution: skip creating the branch/PR if prCreation=not-pending and the dependency is less than 24 hours old. This will fix the race condition between pending timeout and unpublishSafe
