### ISSUE TITLE
GitLab automerge aborting when jobs exist with allow_failure === true

### ISSUE THREAD

**Issue by adam-moss** [renovateapp/renovate#1586]
So I've been enabling the automerge feature in GitLab.  One of our standard pipeline jobs includes a call to `npm outdated` which is allowed to fail (therefore the build is marked as "Passed with warnings".

It looks like the automerge check however is simply looking at whether any step failed - https://github.com/renovateapp/renovate/blob/master/lib/platform/gitlab/index.js#L246.

Would you be amenable to this being amended to report a status of `success` if the `allow_failure` attribute returned in the api payload is set to `true` ?

**Comment by rarkins** [comment]
That sounds fine to me, please go ahead. Do you think it needs to be configurable, or would you expect everyone to want the same approach?

**Comment by adam-moss** [comment]
I'd argue everyone should have the same approach - if you're specifically saying in your pipeline it is ok for a job to fail then it is ok to fail, and therefore by definition the pipeline passes 👍 

I'll raise an MR on that basis - if someone in the future wants something more complicated they can also raise a further change 😈
