### ISSUE TITLE
github limit rate

### ISSUE THREAD

**Issue by jycouet** [renovateapp/renovate#1593]
Hello from yesterday I'm getting this error: 
`API rate limit exceeded for xx.xx.xx.xx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)`

I'm using renovate with VSTS and I get this error when renovate tries to get github `changelog` of package that I use.

Are you aware of this? Could I help somewhere?

**Comment by rarkins** [comment]
You can fix this if you set a `GITHUB_TOKEN` env var in the environment where you run Renovate. It should be a personal access token, and can be *any* account. e.g. even create an account just for this purpose.

If you'd like to help though, it would be great if you can work out where in our existing docs we should mention this for VSTS and GitLab users.

**Comment by jycouet** [comment]
It's working well with a `GITHUB_TOKEN` thank you.
I didn't even need to set speacial scope!

I would say that it's sufficient to close the ticket and people will this this ticket to solve their problem?

**Comment by shirbr510** [comment]
it appears like @rarkins 's solution doesn't work for me.

as you said, I am running my script with the `GITHUB_TOKEN` env set like this:

```
docker run -e GITHUB_TOKEN=my-token --rm renovate/renovate:latest --platform=gitlab --token=my-token --endpoint=my-private-gitlab --update-lock-files=true --require-config=true --autodiscover 
```

and I'm still receiving the exact same error of:

```
API rate limit exceeded for xx.xx.xx.xx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

**Comment by rarkins** [comment]
Use `GITHUB_COM_TOKEN`. See https://github.com/renovatebot/renovate/blob/master/docs/self-hosting.md#githubcom-token-for-release-notes for details
