### ISSUE TITLE
Support pinVersions for package.json > engines fields

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1595]
Following on from #320, we should pin `node` to the latest satisfying version if pinVersions=true.

**Comment by destroyerofbuilds** [comment]
Could we extend the `node` option with support for a nested `pinVersions` option?

We have `pinVersions` disabled globally, but we **do** want our Node versions for applications and services to be pinned.

Therefore I was wondering if there could be an equivalent of `"pinVersions": null` under `node` so that Renovate pins Node for applications and services, but maintains version ranges for libraries.

This may also require supporting a `supportPolicy` option per project type (one for applications and services, and another for libraries)

**Comment by rarkins** [comment]
I've actually been wondering whether to deprecate the `node` object and instead just have people use a packageRule targeting packageName "node". This would then catch the `node` in engines too. What do you think?

**Comment by destroyerofbuilds** [comment]
> I've actually been wondering whether to deprecate the node object and instead just have people use a packageRule targeting packageName "node"

Personally I would find that confusing. To me Node isn't a package. It's not code that I incorporate into my product. It's a runtime environment.

Also, there's the _actual_ [`node`](npmjs.com/packages/node) package. It would further get confusing when other languages are added, bringing npm packages, such as [`python`](https://www.npmjs.com/package/python) into conflict.

**Comment by rarkins** [comment]
Thanks for the feedback. I think that applying the "node" settings to `package.json>engines.node` is also a little inelegant, but perhaps it's the best choice.

**Comment by destroyerofbuilds** [comment]
> I think that applying the "node" settings to package.json>engines.node is also a little inelegant

Because it's touching the `package.json` file in particular?

**Comment by rarkins** [comment]
Yes. That setting essentially belongs to `npm` or `yarn`, neither of which we want to be a subcategory of “node”. But I’m ok with exceptions if they are very special  exceptions

**Comment by rarkins** [comment]
This already works for package.json > engines > node, although the setting terminology has changed to "rangeStrategy=pin"

**Comment by leethree** [comment]
How can I disable pinning `engines`? We use it only to check if the runtime environment satisfy the minimal requirements of the project.

**Comment by rarkins** [comment]
@leethree please raise an issue in https://github.com/renovate-tests/config-help with a copy of your current config, and I will help there

**Comment by leethree** [comment]
@rarkins See: https://github.com/renovatebot/config-help/issues/53 . Thank you!
