### ISSUE TITLE
Support in-range updates

### ISSUE THREAD

**Issue by kesne** [renovateapp/renovate#1607]
We're playing around with getting Renovate running at Airbnb, and we've run into some issues with the `pinVersions` configuration with lockfiles. Our npm setup is that we have a `package.json` that contains semver ranges, alongside a `package-lock.json`. The `package.json` ranges are mostly just used to express intent.

It seems like Renovate will only create PRs for out-of-range dependency updates, despite the presence of a lockfile indicating that every dependency is essentially an out-of-range update. Setting `pinVersions` means our `package.json` would change and not contain ranges, which isn't what we want either.

**Comment by rarkins** [comment]
Hi @kesne, really great to hear that you are testing it out and I understand what you mean.

The first thing you can do is enable "lock file maintenance". What this does is completely refreshes the lock file, including indirect dependencies. It defaults to a weekly schedule once you enable it though, because it can be "noisy".

I think you would be more interested in a feature in the pipeline #1382 that I'm calling "lock file maintenance v2". Please have a read through there and let me know if you think that suits your requirements and it can be prioritised higher.

**Comment by kesne** [comment]
@rarkins Hey there! I think lockfile maintenance isn't really what we want. That seems a little bit extreme and I think it'd be confusing for our repo maintainers. #1382 seems good though. Really it just seems like Renovate should try to read out the lockfile version if it exists and use that instead of the range.

**Comment by rarkins** [comment]
So you want PRs that modify the lockfile only? And that upgrade one direct dependency at a time?

**Comment by kesne** [comment]
Well ideally they'd also update the range to `^version-just-upgraded-to-which-is-now-in-the-lockfile`

**Comment by rarkins** [comment]
I had thought you meant like this:

|                   | Before | After  |
|-------------------|--------|--------|
| package.json      | ^1.0.0 | ^1.0.0 |
| package-lock.json | 1.5.0  | 1.5.1  |

But do you actually mean you expect it to be like this?

|                   | Before | After  |
|-------------------|--------|--------|
| package.json      | ^1.5.0 | ^1.5.1 |
| package-lock.json | 1.5.0  | 1.5.1  |

**Comment by kesne** [comment]
Yeah that’s how we do it for all of our stuff internally. I think the former is acceptable to get us using it fully internally, but the latter would be icing on the cake!

**Comment by rarkins** [comment]
The latter might actually be easier to implement within Renovate so I’ll try for that first

**Comment by kesne** [comment]
Oh stellar! Let me know if there’s anything I can do to help.

**Comment by rarkins** [comment]
@kesne does this look like the type of result you're after?

![image](https://user-images.githubusercontent.com/6311784/37076351-84d6e00a-21d6-11e8-92ac-a97172109060.png)

Right now I've limited it to simple caret and tilde ranges like in the above example - works for you?

**Comment by kesne** [comment]
Yeah that seems to align with how we use it!

**Comment by rarkins** [comment]
This feature is complete (see #1608) and will be available in a release shortly. To enable it, set `"upgradeInRange": true` in your config.

**Comment by rarkins** [comment]
This is released in v11.33.0 behind feature flag "upgradeInRange". Feedback/testing very welcome of course.

**Comment by destroyerofbuilds** [comment]
**Some Feedback**

The version specified in a semantic version range in `package.json` should be the minimum version required by the consuming project. 

It should _never_ be upgraded _except_ when required by the consuming library.

When upgraded, from `1.0.0` to `1.2.0` (as shown in the example above), it should be because your library depends on an enhancement added in version `1.2.0` of your dependency.

Automatically upgrading the minimum version when there is no change in your library's requirements is actively harmful to the JavaScript community. It inhibits the ability for `npm` and `yarn` to de-duplicate dependencies by finding the greatest overlapping semantic version range for a given dependency.

**Comment by kesne** [comment]
@destroyerofbuilds I’m talking more about apps here. I agree with you on libs.

**Comment by destroyerofbuilds** [comment]
> @destroyerofbuilds I’m talking more about apps here. I agree with you on libs.

Hmm... but doesn't the same logic apply to applications? If your application does not require an upgrade from `1.0.0` to `1.2.0`, why upgrade?

If you want your project to consume the latest upstream bug fixes, then you want your lockfile upgraded. Upgrading your lockfile will naturally pick up `1.2.0`.

Furthermore, lockfile updates are more beneficial to you. If you are upgrading from `1.0.0` to `1.2.0` for the purpose of consuming bug fixes, wouldn't you also want the same benefit for transitive dependencies specified by your other direct dependencies that haven't, themselves, released a new version?

**Comment by kesne** [comment]
I agree that lockfile changes are all that’s required, but we just prefer keeping our package.json updated to reflect what is in the lockfile. I’ve found it’s a better developer experience because you can figure out what version of packages your app is using without having to dive into lockfiles.

**Comment by ljharb** [comment]
Maybe this will help clarify: *apps* and *packages* should have different rules, and package's dev deps behave like all app deps.

Apps (not published: private: true and no "main") should always update package.json along with the lockfile.

Packages (published, with a "main" or a "bin") should, for prod and peer and optional deps, only update package.json when it *expands* the range, but the range should never be restricted. For dev deps, it should behave the same as it does for apps.

**Comment by rarkins** [comment]
Question: What would you *lose* if you simply pinned versions in `package.json` instead of maintaining the range operators? @kesne mentioned they indicate "intent" but I'm not sure exactly what that means.

if you `package.json` specified `1.2.0` instead of `^1.2.0` then it would seem more obvious to developers without them needing to peek into `package-lock.json` to be sure.

**Comment by ljharb** [comment]
@rarkins the conceptual information that the range communicates; that a) the dep follows semver (ie, it's not underscore or uglify, to name a few), that b) you intent to aggressively update that dependency.

More to the point, if package.json does not specify a range, then a service like renovate *should not suggest updating it casually*. A breaking change update is *just as risky* as updating beyond a pinned range.

**Comment by destroyerofbuilds** [comment]
> I’ve found it’s a better developer experience because you can figure out what version of packages your app is using without having to dive into lockfiles.

Except your transitive dependencies aren't reflected in your `package.json` file.  So it's easier to see which version of a direct dependency your application is using, but there's no way to see the exact version of your transitive dependencies.

> Apps (not published: private: true and no "main") should always update package.json along with the lockfile.

Could you explain the value of updating the version in `package.json`? What is the value to the behavior of the application? What is the value to the developer?

> prod and peer and optional deps, only update package.json when it expands the range, but the range should never be restricted.

Even if, as shown in my example above, my library/package depends on version `1.2.0` of a dependency for a new feature, are you saying that I shouldn't update the minimum version (restricting the range)?

> the conceptual information that the range communicates; that a) the dep follows semver

But it doesn't communicate that. It communicates: "I _believe_ this dep follows semver, and assuming it does, I would like my application to inherit all range-compatible updates"

**Comment by ljharb** [comment]
> But it doesn't communicate that. It communicates: "I believe this dep follows semver, and assuming it does, I would like my application to inherit all range-compatible updates"

Fair, but that information is MASSIVELY valuable, and the belief in semver is what drives npm, the largest package ecosystem on the planet :-) Losing that information is a big problem.

**Comment by kesne** [comment]
> Could you explain the value of updating the version in package.json? What is the value to the behavior of the application? What is the value to the developer?

I think the value is what I previously stated, not having to dive into the lockfile. Transitive dependencies should be _relatively_ transparent. Imagine I want to know if I can use a feature released in React 16.2. I'd need to go look at the lockfile to know if the app was using 16.2 or 16.1 or 16.0. That sucks.

**Comment by destroyerofbuilds** [comment]
So my impression is that y'all are using the _lack_ of a `^` (Or perhaps `~`) notion in a version string within your `package.json` file to instruct Renovate to _not_ update that dependency. Is that correct?

Are y'all manually upgrading dependencies when a new version is out of the existing range?

> Imagine I want to know if I can use a feature released in React 16.2

There's no need to look into your lockfile. You've indicated that you want to use a feature in React `16.2`, so you should manually update the minimum version in your application's `package.json` file to be `^16.2`. If the minimum version of React in your `package.json` is less than `16.2`, then you should _not_ use that new feature, regardless of what is listed in your project's lockfile.

**Comment by ljharb** [comment]
@destroyerofbuilds typically we try to use `=1.2.3` to indicate it's strictly pinned, but `1.2.3` is equivalent, so yes - that means that 1.2.5 isn't something that's safe to upgrade to. Yes, those deps are manually updated. Auto updates are only for deps that haven't betrayed our trust in them by willfully violating semver.

**Comment by rarkins** [comment]
@ljharb thanks for the context.

Usual disclaimer: I really don't mind how people use Renovate and strive to make it as configurable as possible.

> the range communicates; that a) the dep follows semver (ie, it's not underscore or uglify, to name a few), that b) you intend to aggressively update that dependency.

I think this is a pretty "opinionated" convention, and definitely not something you could interpret from the semver specification alone. i.e. I don't think it's something everyone would want to follow. If these *implicit* meanings of range vs no-range are communicated well internally, it sounds like an interesting way to essentially "tag" dependencies according to their past bad semver behaviour.

> if package.json does not specify a range, then a service like renovate should not suggest updating it casually.

First of all it's a bot, so nothing is really casual or not. But as you derive meaning from pinned vs ranged dependencies in `package.json`, I can think of some approaches:

1. You could define a package rule that flags certain dependencies using a specific label to indicate they unreliably follow semver (but this means you are kind of double flagging them both in package.json as well as renovate config), or

2. You could request a feature in Renovate to implicitly *never* propose updates to pinned dependencies. e.g. call it `updatePinnedDeps` which defaults to true, and you would flip it to false. To make it even clearer you could perhaps use the `=` prefix as you mention above. I actually need to check if Renovate supports upgrading `=x.y.z` notation. Maybe it skips it by accident already! But that's something we shouldn't rely on long term even if so.

3. Anything else you can think of? I'm not really sure how to make PRs less "casual" for pinned upgrades than ranged ones. Assuming everyone on your projects should be aware of the "pinned dependencies means this dep does bad semver" convention, then the PR title and body itself would also be communicating this same convention, as it's clearly visible that it's upgrading a version and not a range.

**Comment by ljharb** [comment]
By "casual" I'm just assuming (not yet heavily using renovate) that a PR updating from v4 to v5 has more scary language ("things will probably break") than a PR updating from v4.1 to v4.2 (which should be safe).

**Comment by destroyerofbuilds** [comment]
Though continuing with the slightly off-topic discussion about PR templates, the existing templates work quite well for us.

The way we think about it is that if a PR is raised by Renovate, it's because a dependency is out of the existing range. If a dependency is out of the range, that means it isn't compatible with our application. If it's not compatible, then it must include breaking changes. Therefore, every PR from Renovate should be carefully reviewed as if the upgrade is introducing breaking changes. (This excludes lockfile maintenance PRs)

**Comment by rarkins** [comment]
BTW the same "casual" concern occurred to me and some users in the past about pre-1.0 dependencies. i.e. every single update of those (even "patch") may be backwards-incompatible and should be treated carefully. I wish the industry would make 0.x packages kind of taboo, e.g. using them as dependencies in production is like using alpha or beta software. If large companies or projects made a policy to stop using 0.x in their next major release I bet a lot of library authors would release 1.0.0 pretty quickly

**Comment by ljharb** [comment]
@rarkins that's not technically true; in `0.x.y`, "x" is breaking but "y" is not, it's only in `0.0.x` that every change is breaking.

**Comment by rarkins** [comment]
@ljharb that’s not how I interpret this section of semver 2.0.0

“4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.”

**Comment by ljharb** [comment]
The community's idea of semver doesn't, nor needs to, cleave tightly to any semver spec - and especially not a specific version of it.

The way I've described it imo reflects the common understanding. (Regardless, I think < 1.0 versions should be avoided for many reasons)

**Comment by rarkins** [comment]
Perhaps, but you chose the term "**technically** true", not me.. specifications are technical, community ideas are not. Apart from that, I agree with you that `0.x.y` "patch" upgrades are *usually* not breaking and I'd like to avoid < 1.0 versions whenever possible.

**Comment by ljharb** [comment]
lol ok fair :-)

**Comment by rarkins** [comment]
Anyway, I think I understand now about your convention with ranges vs pins (conveying the "reputation" of the dependency for correct semver) and why it's especially harmless to be doing it in a private app regardless. If you have any request for special handing of pinned versions vs ranges then I'm happy for you to raise a feature request to discuss there an elegant way to achieve it.
