### ISSUE TITLE
Bot not running?

### ISSUE THREAD

**Issue by alan-agius4** [renovateapp/renovate#1611]
It looks like renovate stopped running on one of my repo https://github.com/alan-agius4/ng-mono-repo-starter

If I go in renovate, i see that it is enabled for this repo.

I tried to install and uninstall it but didn’t help. When I add another new repo to renovate, I get the onboarding PR.

Config: https://github.com/alan-agius4/ng-mono-repo-starter/blob/master/renovate.json

Any idea what I can do?

**Comment by rarkins** [comment]
I saw your onboarding PR pop up a little earlier but didn't realise you were uninstalling/installing. I'll take a look at the logs now to see if there's any problem.

**Comment by rarkins** [comment]
You have configured `pinVersions=false` and it looks like your dependency ranges are all still valid. i.e. there are no upgrades and that's why you have no PRs. If you run "npm outdated", do you get any different result?

**Comment by alan-agius4** [comment]
Thanks for your fast reply

Is there a way to force it to update a minor version with pinVersion=false?

I now understand that indeed actually it is not a  problem. If it works the
same as npm outdated.

Thanks you again for your fast reply, much appreciated.

**Comment by rarkins** [comment]
> Is there a way to force it to update a minor version with pinVersion=false?

Best way would be if you define a tilde range instead of caret, e.g. ~1.5.0 instead of ^1.5.0

**Comment by l5x** [comment]
@rarkins not to open another PR. I may have messed up something with git push --force. When you have a minute can you please take a look at https://github.com/escapace/recce

**Comment by rarkins** [comment]
@l5x please raise a new issue in https://github.com/renovateapp/config-help describing what the exact problem is?

**Comment by l5x** [comment]
@rarkins false alarm, the bot opened the PR. Wasn't sure that renovate is working after install/uninstall. Thank you!
