### ISSUE TITLE
Validate npmrc field as ini file

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1630]
Check that any configured "npmrc" config option is in valid INI format (use https://github.com/npm/ini)

**Comment by hulkish** [comment]
@rarkins Don't think that package actually involves any form of validation for ini. [Nor does npm](https://github.com/dominictarr/config-chain/blob/0b6db3e14b9cdbe31460292bc4caf3983f977816/index.js#L42). 

But, you are wanting to parse the string content using this package, right?

**Comment by rarkins** [comment]
Yes, it seems that ini files are very "flexible" and it's hard to automate validation of a `.npmrc` file because format-wise, almost anything goes

**Comment by hulkish** [comment]
looks like [you've already added this](https://github.com/renovateapp/renovate/blob/master/lib/datasource/npm.js#L37)?

**Comment by rarkins** [comment]
Yes but in reality it validates nothing eg it did not earn me when someone forgot to add registry= to a line :)

**Comment by hulkish** [comment]
I see. So, really what you're looking for is a validation on the object which `ini.parse` produces

**Comment by rarkins** [comment]
Yes, but I’m thinking to probably give up as even npm doesn’t have that type of validation / warning

**Comment by hulkish** [comment]
@rarkins We could just log the masked output, say for ex this is the string we pass to npmrc:
```ini
//some.registry.com/:_authToken=abcdefghi-1234-jklmno-aac6-12345567889
```
then you log:
```
//some.registry.com/:_authToken=*********-****-******-****-*********
```

**Comment by rarkins** [comment]
But that's logging, not validation. Also my goal was to catch invalid npmrc lines while the one above is valid too

**Comment by rarkins** [comment]
I think I'll close this - if npm doesn't validate, we can't be expected to either
