### ISSUE TITLE
renovate-config-validator Can't Validate Preset Package

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/renovate#1632]
I'm switching over the validation logic for a preset package to use the new `renovate-config-validator` CLI tool published as part of #1352, and it seems it can't validate a preset package.

```bash
package.json > renovate-config contains errors:

[
  {
    "depName": "Configuration Error",
    "message": "Invalid configuration option: `default`"
  },
  {
    "depName": "Configuration Error",
    "message": "Invalid configuration option: `web`"
  }
]
```

The keys `default` and `web` are the preset names within the preset package's `package.json` file.

**Comment by destroyerofbuilds** [comment]
Since the `renovate-config` key seems to be unique to preset packages (at least that's the impression I get from the documentation), perhaps each key under `renovate-config` should be looked at as a separate renovate configuration?

**Comment by destroyerofbuilds** [comment]
Perhaps we can loop through every key fetched from `renovate-config` on [this line of code](https://github.com/renovateapp/renovate/blob/548fd34ef5553fd659d7150112ab9f724dd1cbeb/bin/config-validator.js#L54).

**Comment by rarkins** [comment]
Does it fail this way for every preset you tried?

**Comment by rarkins** [comment]
It would be fine to test them all separately but I’m confused as to why that’s necessary

**Comment by destroyerofbuilds** [comment]
I'm running `renovate-config-validator` inside the preset package itself:

```
"test": "eslint src/ && renovate-config-validator"
```

The `package.json` for the preset package has something like:

```json
  "renovate-config": {
    "default": {
      "extends": [
        "config:base"
      ]
    },
    "web": {
      "extends": [
        "@scope:default"
      ],
      "lockFileMaintenance": {
        "enabled": true,
        "schedule": [
          "before 5am on sunday"
        ]
      }
    }
  },
```

When I run `yarn test` inside the package, I get the following:

```bash
> yarn test

yarn run v1.5.1
$ eslint src/ && renovate-config-validator
Validating renovate.json
Validating package.json > renovate-config
package.json > renovate-config contains errors:

[
  {
    "depName": "Configuration Error",
    "message": "Invalid configuration option: `default`"
  },
  {
    "depName": "Configuration Error",
    "message": "Invalid configuration option: `web`"
  }
]
error An unexpected error occurred: "Command failed.
```

**Comment by rarkins** [comment]
Ohhh of course! Thanks.  Yes that needs a fix as you describe

**Comment by rarkins** [comment]
My iOS GitHub client wasn’t showing your copy paste correctly so I wasn’t seeing your preset names

**Comment by destroyerofbuilds** [comment]
I'll put a fix together shortly.

**Comment by jedwards1211** [comment]
I can't seem to get any validation errors whatsoever with the latest version of this package.  Shouldn't the following in `package.json` error?

```json
{
  "renovate-config": {
    "default": {
      "major": "FOO"
    } 
  }
}

**Comment by rarkins** [comment]
@jedwards1211 it should, yes. Can you raise it as a separate bug report with additional details?
