### ISSUE TITLE
Include git as a dependency in the official docker image

### ISSUE THREAD

**Issue by adam-moss** [renovateapp/renovate#1642]
#### This is a:

* [ ] Bug report (non-security related)
* [X] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [X] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:
I've migrated across to your official docker image however it does not appear to include git to be able to satisfy git+ssh or git+https type dependencies.  Would you be willing to add that?

**Comment by rarkins** [comment]
@adam-moss I've added `git` to the alpine base image, which should be built soon after the next release is tagged. Can you check it out and confirm if it's now working in your environment?

**Comment by adam-moss** [comment]
Dang, looks like it needs openssh-client also
