### ISSUE TITLE
Docker FROM - alias being removed when updating digest

### ISSUE THREAD

**Issue by notquitedilbert** [renovateapp/renovate#1656]
#### This is a:

* [X] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [X] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [X] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:
If there are multiple FROM statements in a docker file, and they use the same image, and at least one of them doesn't have an alias, then only one FROM statement will be updated, and if it has an alias it will be removed.

eg -
```
FROM debian:wheezy as stage-1
FROM debian:wheezy 
```
becomes 
```
FROM debian:wheezy@sha256:21c3c65a~/~6adf1a
FROM debian:wheezy 
```
but it should be 
```
FROM debian:wheezy@sha256:21c3c65a~/~6adf1a as stage-1
FROM debian:wheezy@sha256:21c3c65a~/~6adf1a
```

I've had a look in some of the log files for the self-hosted GitLab, and it's identify all the FROM statements correctly, so I think it's when its writing out FROM without an alias, it's just finding the first match and then overwriting it.  

If you need any more info let me know.
Thanks

**Comment by rarkins** [comment]
@notquitedilbert I can replicate "only one FROM statement will be updated" but cannot replicate "if it has an alias it will be removed". I used your example to reproduce:
```
FROM debian:wheezy as stage-1
FROM debian:wheezy 
```

**Comment by rarkins** [comment]
OK, this one works to reproduce:
```
FROM debian:wheezy as stage-1
RUN something
FROM debian:wheezy
RUN something else
```

**Comment by rarkins** [comment]
@notquitedilbert thanks for taking the time to pinpoint this problem. I have pushed a regex change that should hopefully fix this for you. Example PR: https://github.com/renovate-tests/baddocker/pull/2/files

**Comment by notquitedilbert** [comment]
@rarkins - thank you - very quick work!

Does your pipeline update the github app bot when you merge to master?
or does it lag behind (i've just done a quick test, but I still got the old behaviour)

**Comment by rarkins** [comment]
By default there's a deliberate lag between publishing to npm and going live on the app to give me a "kill switch" opportunity in case anything untoward happens. It's now live. Can you try again now?

**Comment by notquitedilbert** [comment]
Yes, that's now updated my test files correctly on github - thank 👍 

On the self-hosted gitlab - the renovateBot doesn't run until tonight - so I won't know if there's a problem until tomorrow - I'm not expecting one - but if there is, I'll provide an update.
Thanks again.

**Comment by adam-moss** [comment]
@notquitedilbert you can actually it through our on-prem instance whenever you like - just copy my forked example to target your repo specifically rather that auto-discovering all 😉
