### ISSUE TITLE
GitLab closes PR when branch deleted

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1657]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [x] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

GitLab behaviour appears to have changed. Now, when we delete a branch to rebase a PR, GitLab will close the PR, which are are not expecting.

Need to check if it's deliberate, and if the "delete branch when PR closes" setting impacts it.

**Comment by rarkins** [comment]
Cc @Autre31415 @hbetts @adam-moss

**Comment by Autre31415** [comment]
In my experience this isn't happening when a PR needs to be rebased, it's occurring when a dependency in an open PR gets a new update. The workflow looks something like this:

- Open PR exists to update dependency `x` to version 0.2.0.
- Dependency `x` pushes a new 0.2.1 release.
- Renovate runs
- Renovate discovers that the `x` PR is out of date.
- Renovate updates the PR.
- Renovate closes the PR (Unexpected behavior).

And then later on Renovate runs again
- Renovate sees a closed PR for dependency `x`
- Renovate then deletes the branch for dependency `x` under the assumption that the PR was closed intentionally.

The closing of the branch is only incidental, and not a root part of the bug itself.

**Comment by rarkins** [comment]
I tested manually that when deleting a branch attached to a MR that GitLab closes the MR too, this is the fundamental change from before

**Comment by rarkins** [comment]
BTW I forgot to confirm that yes, the "use case" I'm looking at is the one where the MR needs updating because a newer version exists, exactly as described by @Autre31415 

I'm going to try a few experiments, but I hope such a functionality change didn't go unpublicised by GitLab. Worst case we can hopefully reopen the MR after we submit the new commmit. i.e. the MR will have only one commit after the update, but it will there will be a close/reopen "noise" in the MR log each time it's required.

**Comment by rarkins** [comment]
I found where GitLab changed this behaviour deliberately: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/16690

**Comment by rarkins** [comment]
Here's how the discussion would look:

![image](https://user-images.githubusercontent.com/6311784/37361523-6438ccc4-26f3-11e8-9454-af4642374948.png)

**Comment by adam-moss** [comment]
So it kinda makes sense - if you kill the branch then the MR could never go forward so yeah, would then close.

Its a bit noisy, but no harm done.  I wonder if you might face any caching issues in the gitlab api though doing it straight away - I've seen a few things where it hasn't performed things before sending a response of success.

The other alternative would be to delete the PR and re-create it, which is a bit of a faff.  But deleting the MR wouldn't automatically delete the branch, so you'd still need to do that.

**Comment by rarkins** [comment]
I think deleting MR is a far bigger pain as you keep incrementing numbers each time and lose any comment history. and you’ll soon start doing this for conflicted and stale MRs too!
