### ISSUE TITLE
Can't Fetch Renovate File For Validation on PR from Fork

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/renovate#1658]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [x] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

I recently upgraded an on-premise Renovate instance to version [11.36.2](https://github.com/renovateapp/renovate/releases/tag/11.36.2) and I'm now receiving the following log message: `WARN: Error checking PR (repository=org/project)`

I recently filed a pull request against the `org/project` repository with a change that modifies the contents of the `renovate.json` file.

My pull request is from a fork of the `org/project` repository called `hbetts/project`, and the branch is called `patch-1`.

Renovate successfully determines that my pull request contains a modified `renovate.json` configuration file using the [following code](https://github.com/renovateapp/renovate/blob/862998c2b43c8d5b9dfd54e3d81ebeb221e19bae/lib/workers/repository/validate.js#L30).

When it [attempts to fetch the `patch-1` branch](https://github.com/renovateapp/renovate/blob/862998c2b43c8d5b9dfd54e3d81ebeb221e19bae/lib/workers/repository/validate.js#L39) it uses the following path - `/api/v3/repos/org/project/git/refs/heads/patch-1`

That path is for the upstream repository, not my fork. Therefore the request fails, as the branch, `patch-1`, is not on the upstream repository.

**Comment by rarkins** [comment]
Even if we add logic to detect a forked source branch and look for it, I don't know if the app/bot will get any automatic access to forks. Is the only impact right now the WARN in logs, or is it causing anything annoying in the repository itself? If only the WARN, I'd say the mitigation is just to catch that error and assume it's because of a patch, and not show a WARN.

**Comment by destroyerofbuilds** [comment]
> I don't know if the app/bot will get any automatic access to forks.

If the upstream project is _public_ wouldn't the fork be public as well?

Not sure about private projects. 

Is that something we need to follow up with GitHub support about? (Ask for an API end-point that allows accessing file contents for files in a PR).

> Is the only impact right now the WARN in logs

Yes, looks like it's just the logs.

> If only the WARN, I'd say the mitigation is just to catch that error and assume it's because of a patch, and not show a WARN.

Long-term, though, we wouldn't be able to validate Renovate configuration changes from forks.

**Comment by rarkins** [comment]
Based on https://developer.github.com/v3/pulls/#list-pull-requests it looks like we can use `body.head.repo.full_name` to find out the source repository. It would be another field we need to our cached `prList` in the GitHub platform. Then modify the `getFile` function to allow an override of repository name.

**Comment by rarkins** [comment]
This is a known limitation of permissions but there may be a workaround. If you take the URL for a PR on GitHub and then append ".patch" to it, you can see the file contents

**Comment by rarkins** [comment]
I have added `sourceRepo` as a field to the `getPrList()` function: https://github.com/renovateapp/renovate/blob/1ba12ef59c6e6831c1c7922881e6ede5f22c0481/lib/platform/github/index.js#L767

So the next step is to modify the validation code to check if sourceRepo is defined and if so then look up the files in that repo and not the default one. May require small change to platform
