### ISSUE TITLE
Cannot scroll documentation sidebar

### ISSUE THREAD

**Issue by bahmutov** [renovateapp/renovate#1661]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

This is for static documentation site pages like https://renovateapp.com/docs/configuration-reference/configuration-options

I cannot scroll the left column with the list of configuration options. See the attached video - the scroll over the left column scrolls the right text, thus finding the right option is very hard.

[cannot-scroll.webm.zip](https://github.com/renovateapp/renovate/files/1809383/cannot-scroll.webm.zip)

**Comment by rarkins** [comment]
Thanks, I noticed this too. Unfortunately it's a fault of the template I'm using so I need to find something better.

**Comment by rarkins** [comment]
@bahmutov please check out the new docs site https://renovatebot.com/docs - built with `mkdocs` with functional sidebar and better search.
