### ISSUE TITLE
Release notes for js-yaml update not shown

### ISSUE THREAD

**Issue by edmorley** [renovateapp/renovate#1709]
#### This is a:
* [X] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:
* [X] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:
Hi!

For this update only the 'commits' section was populated, not the release notes:
mozilla/treeherder/pull/3305

The js-yaml package changelog is here:
https://github.com/nodeca/js-yaml/blob/master/CHANGELOG.md

**Comment by rarkins** [comment]
Pity they don't use markdown headers 👎

**Comment by edmorley** [comment]
Ah true! They are using Restructured text headings in a markdown file 😆 
If it's too much of a pain to fix happy to close out.

**Comment by rarkins** [comment]
no it's ok, if we can capture it in a regex it's fine

**Comment by edmorley** [comment]
Thanks for the fixes here and in the other PRs! :-)
