### ISSUE TITLE
Update PR reverts recent unrelated package version change on master

### ISSUE THREAD

**Issue by edmorley** [renovateapp/renovate#1712]
#### This is a:

* [X] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [X] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:
I just merged a PR into master that updated a package:
mozilla-neutrino/neutrino-dev/pull/711

This caused conflicts with an already-open PR for a different package, so Renovate pushed an update to the other PR to resolve the conflicts. However unfortunately the updated PR now reverts the change to `package.json` that just landed on master:
mozilla-neutrino/neutrino-dev/pull/712

Ie: it's downgraded `eslint-config-standard` from `^11.0.0` to `^10.2.1`, presumably since it didn't use the `package.json` from master, but instead the version already present on that branch?

**Comment by rarkins** [comment]
This is a tough one to catch and fix. I noticed that you merged 4 PRs in close time together. Renovate detected changes and restarted once, but could not detect them all and so used a cached version of the `package.json` - from master, not its own branch - to base this PR off. Enabling `rebaseStalePrs` would be a way for this problem to fix itself if it reoccurs, although you probably prefer to have less "noise" and keep it disabled. In that case, renaming and closing the PR should fix this particular case.

**Comment by rarkins** [comment]
I've added a one line fix to greedily fetch the master branch SHA when we initialise a repo. This should make sure that we never create branches off a commit that didn't exist at the time we started renovation.
