### ISSUE TITLE
Update docker digest in CircleCI2 config.yml

### ISSUE THREAD

**Issue by teppeis** [renovateapp/renovate#1714]
#### This is a:

* [ ] Bug report (non-security related)
* [x] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

> [Overcoming Docker’s mutable image tags - Renovate](https://renovateapp.com/blog/docker-mutable-tags)

In the time, my some CircleCI jobs were broken too and they had been unstable for a few days because CircleCI workers cache old broken docker images.

> Docker Image Best Practices
> https://circleci.com/docs/2.0/executor-types/#docker-image-best-practices

[This](https://github.com/teppeis-sandbox/circleci2-multiple-node-versions/blob/d16185fbd867257e11c5dabab84bbfb509a64a9f/.circleci/config.yml#L66) is my sample project.
I want renovate to change 
```yaml
    docker:
      - image: node:8
```
to
```yaml
    docker:
      - image: node:8@sha256:aa231490fa207f5d255007d3187a3b4e2671eb596837d84b5138505c0095267a
```

**Comment by rarkins** [comment]
Great idea!
