### ISSUE TITLE
(Question) Should/Does renovate close pr's it has created which become stale?

### ISSUE THREAD

**Issue by hulkish** [renovateapp/renovate#1715]
#### This is a:

* [ ] Bug report (non-security related)
* [ ] Feature request
* [X] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [X] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:
This issue is a question:

Consider the following scenario:
1. Renovate has created pr's for each of these major upgrades:
```bash
 react                                15.0.2  →          16.2.0
# aka pr title of "Update dependency react to v16"
```
and also:
```bash
 react-dom                                15.0.2  →          16.2.0
# aka pr title of "Update dependency react-dom to v16"
```
2. At this point as a dev - you will want to combine these updates and test it locally. So you do this and make a pr, merge it.
3. Next time renovate runs, shouldn't it/does it auto close the now-stale pr's it created for `react` & `react-dom`?

**Comment by rarkins** [comment]
Yes it should autoclose those PRs as they have no reason to exist once you update them yourself. 

Also: if it’s a real example then you should consider the preset “group:monorepos” to automatically group react packages from the start
