### ISSUE TITLE
bug: Strip leading or trailing dash for groupSlug's generated from groupName

### ISSUE THREAD

**Issue by hulkish** [renovateapp/renovate#1724]
#### This is a:

* [X] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [X] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:
Consider this config:
```
  "packageRules": [
    {
      "groupName": "@myorg",
      "packagePatterns": [
        "^@myorg"
      ]
    }
  ]
```

When renovate generates the groupSlug/branch name based on this `groupName`; the resulting branch name is "`renovate/-myorg`" (note leading slash)

Same appears to happen for trailing dash. I'm not sure if this is a valid branch name (may be). But, in context of what renovate's intent is - seems like a bug to me.

I can see this is handled [here](https://github.com/renovateapp/renovate/blob/master/lib/workers/repository/updates/branchify.js#L31) - but I wonder if maybe using something like [this](https://www.npmjs.com/package/slugify) would be a better approach?

**Comment by rarkins** [comment]
I guess we should remove any leading or trailing slash, and slugify looks good

**Comment by rarkins** [comment]
However slugify keeps `@` symbols, which I think we'd want to remove for branch names

**Comment by hulkish** [comment]
@rarkins how about https://github.com/TheSavior/clean-git-ref to enforce this - after being slugified?

**Comment by rarkins** [comment]
ok, let's slugify and then git ref clean them. I may cause some branches/PRs to be recreated for people now, but we need to make *some* change as our current logic is incomplete and we may as well make the best change now and be done with it.
