### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/renovate#1734]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [x] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

Re-posting from - https://github.com/renovateapp/renovate-config/issues/26

---

I have Renovate configuration package with a `package.json` file that contains the following configuration section:

```json
{
  "renovate-config": {
    "default": {
      "extends": [
        "config:base"
      ]
    }
  }
}
```

When I run `yarn renovate-config-validator` I get the following error:

```bash
yarn run v1.5.1

Validating renovate.json
renovate.json is not valid JSON
Validating package.json > renovate-config
error An unexpected error occurred: "Command failed.
Exit code: 1
```

I went as far as having an `package.json` file with just the `renovate-config` section, but I still get the same error.

I can confirm that I started getting the validation error with version [11.40.0](https://github.com/renovateapp/renovate/releases/tag/11.42.0). though I still receive the error in Renovate `11.44.1`.

---

Sorry, I just realized I was reading that incorrectly. It's failing on the `renovate.json` file.

The `renovate.json` file is:

```
{
  "extends": [
    "config:base"
  ]
}
```

---

it's failing on this line - https://github.com/renovateapp/renovate/blob/70ae736988ee8c61ecf328f799a088784f338d39/bin/config-validator.js#L12

It can't get `length` of undefined because `res` is now a promise object. There is no `errors` property on the promise object.

Looks like it was specifically this line change here - https://github.com/renovateapp/renovate/commit/b89f448#diff-f77a59981c7f76d61bd1faf9496c0c19R15

So probably just a simple change to call `then` and `catch` on the promise object.

**Comment by rarkins** [comment]
@destroyerofbuilds thanks for the detailed report as always, and sorry for the inconvenience. The validator switched to async in order to be able to resolve presets prior to validating package rules, and I failed to find the `validate()` reference in the `bin/` directory.
