### ISSUE TITLE
Include semantic BREAKING CHANGE message for non-semver compatible peerDependencies upgrades

### ISSUE THREAD

**Issue by jedwards1211** [renovateapp/renovate#1735]
#### This is a:

* [ ] Bug report (non-security related)
* [x] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

I can't honestly say I've tried this, but as far as I can tell from the docs, none of the semantic commit message presets will include a very important `BREAKING CHANGE` section if a dependency is upgraded to a newer major version.

`semanticPrefixChore` and `semanticPrefixFix` seem kind of pointless to me, in my opinion there should be one default smart preset for semantic commit messages:
* `devDependencies` upgrades get `build` or `chore` type commit messages, regardless of severity of upgrade
* non-semver-comptabile upgrades in other sections get `fix` type commit messages with a `BREAKING CHANGE` section
* semver-compatible upgrades (e.g. from `^1.0.3` to `^1.1.9`) get `chore` commit messages, because no new semantic release needs to be triggered (installing the release that depends on `^1.0.3` will still install `^1.1.9` or later)

Note that non-semver-compatible upgrades to `peerDependencies` and `optionalDependencies` should also be considered `BREAKING CHANGE`s.

**Comment by jedwards1211** [comment]
Can I nest `major` and `minor` etc inside of the options for `dependencies`, `devDependencies`, etc?

What I want is

```json
    "semanticPrefixCorrect": {
      "description": "Create the proper semantic commit messages, there is really only one proper way to do it",
      "dependencies": {
        "major": {
          "extends": [":semanticCommitType(fix)", ":semanticBreakingChangeMessage"]
        },
        "minor": {
          "extends": ":semanticCommitType(chore)"
        },
        "patch": {
          "extends": ":semanticCommitType(chore)"
        }
      },
      "devDependencies": {
        "extends": ":semanticCommitType(chore)"
      },
      "optionalDependencies": {
        "major": {
          "extends": [":semanticCommitType(fix)", ":semanticBreakingChangeMessage"]
        },
        "minor": {
          "extends": ":semanticCommitType(chore)"
        },
        "patch": {
          "extends": ":semanticCommitType(chore)"
        }
      },
      "peerDependencies": {
        "major": {
          "extends": [":semanticCommitType(fix)", ":semanticBreakingChangeMessage"]
        },
        "minor": {
          "extends": ":semanticCommitType(chore)"
        },
        "patch": {
          "extends": ":semanticCommitType(chore)"
        }
      }
    },
```

**Comment by jedwards1211** [comment]
Actually I'm not thinking, this may not be the case for `dependencies`, for packages that may exist in multiple versions in a repo.

However, for `peerDependencies` it is probably necessary to label something a breaking change...

**Comment by rarkins** [comment]
Why would this feature be necessary in the first place? It not be a breaking change for the downstream repository unless it changes the external API of *your* library. Just because one of your dependencies changes major version doesn't mean you need to change major version too.

I'm assuming you're using semantic release or similar?

You may want to look at `commitMessageBody` if you really insist.

Otherwise if you just want to be "flagged"/alerted that something is major, perhaps a label on the PR would work.

**Comment by jedwards1211** [comment]
Yeah I wasn't thinking about that for `dependencies`.

However React component libraries are commonly published with
```json
"peerDependencies": {
  "react": "^16.2.0"
}
```
and if React gets major upgraded in these cases it would need to count as a breaking change.

I believe you mean `commitBody`, not `commitMessageBody`, right?

**Comment by jedwards1211** [comment]
@rarkins I think the default preset for semantic commit messages should at least use `fix` for non-semver-compatible upgrades aside from `devDependencies` and `chore` for all semver-compatible upgrades; wouldn't you agree?

**Comment by rarkins** [comment]
I'm still struggling to understand, sorry. Can you give a more detailed example? e.g. you're saying that if a React component has peer X defined and X has a major release then that should force the component to have a major release too? What if the component widens its peer range and supports e.g. "^16.2.0 || ^17.0.0"? Then that's not breaking at all.

**Comment by jedwards1211** [comment]
@rarkins yes if it widens it's not breaking.  But If it somehow drops compatibility for previous major releases (which has sometimes happened with React libraries) then it would have to be a breaking change.  I guess in general changes like this wouldn't be wise to automate though.

**Comment by jedwards1211** [comment]
@rarkins I guess I'm a little confused what `major`, `minor`, and `patch` mean if I'm using semver ranges as opposed to not.  If I have `"lodash": "^4.2.0"`, and a new version `4.2.1` gets published, and I have `"minor": {"automerge": true}`, will `renovate` make a PR with `"lodash": "^4.2.1"`?
I'm also not 100% sure how `:preserveSemverRanges` affects this.

**Comment by rarkins** [comment]
If you are preserving semver ranges and have a caret range like `"^4.2.0"` then `4.2.1` already satisfies that range and no PR will be raised.

Unless.. you enable `upgradeInRange`, in which case you will receive a Pr for `^4.2.1`. But in that case you should really question why you are using ranges at all, before you go down that path.

**Comment by rarkins** [comment]
I will close this for now, maybe revisit later after work on better peer dependency support and improvement of templates. I don't think it will be easy for us to detect breaking change PRs for sure, and commitBody can be used for now.
