### ISSUE TITLE
renovate-config-validator not reporting any errors in package.json > renovate-config

### ISSUE THREAD

**Issue by jedwards1211** [renovateapp/renovate#1736]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### Please describe the issue:
Create a project with the following `package.json`:
```json
{
  "name": "renovate-test",
  "version": "1.0.0",
  "renovate-config": {
    "default": {
      "major": "FOO"
    }
  }
}
```
Run `renovate-config-validator` on it:
```
$ npm-do renovate-config-validator
Validating package.json > renovate-config
OK
```
Expected to see an error message.

**Comment by rarkins** [comment]
Fixed in renovate@11.44.2
