### ISSUE TITLE
Refactor code to use @sindresorhus/is

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1764]
https://github.com/sindresorhus/is

Good to replace some of our own similar functions with this, e.g. some `isObject` calls etc

**Comment by rarkins** [comment]
@connorbrathwaite thanks for testing it out!

**Comment by connorbrathwaite** [comment]
sure thing, there are other little hiccups i've come across but for the most part type checking with `is` should be feasible. progress can be found @ this [fork](https://github.com/connorbrathwaite/renovate/tree/refactor-to-is)

thanks for all the work that went into the app!

**Comment by rarkins** [comment]
@connorbrathwaite I like the look of those diffs already
