### ISSUE TITLE
GitHub App - PR Status Update - Validation Failed (422)

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/renovate#1779]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [x] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

There is a branch on a repository with the name `refactor/renovate`, and that branch has been opened as a Pull Request against the `master` branch. The branch contains a modification to the repository's `renovate.json` file.

In our Renovate App logs (for an on-premise Renovate) we are seeing the following:

```bash
 INFO: Setting PR validation status (repository=org/repo)
       "status": "success",
       "description": "Renovate config is valid"
DEBUG: GET repos/org/repo/git/refs/heads/refactor/renovate [retries=5] (repository=org/repo)
DEBUG: POST repos/org/repo/statuses/a434add208049301ef8334cb1299036deadb3016 [retries=5] (repository=org/repo)
 WARN: Error checking PR (repository=org/repo)
```

Contained in the error object is the following:

```
 "message": "Validation Failed (422)",
       "body": {
         "message": "Validation Failed",
         "errors": [
           {
             "resource": "Status",
             "code": "custom",
             "message": "This SHA and context has reached the maximum number of statuses."
           }
         ]
       },
       "prNo": 60,
       "branchName": "refactor/renovate"
```

On the [following line](https://github.com/renovateapp/renovate/blob/3b8f3c5c167caaeea8681829724e4ce6f40aff4f/lib/workers/repository/validate.js#L88) I was able to see the following property values:

```
pr.branch - refactor/renovate
context - renovate/validate
description - Renovate config is valid
status - success
```

It looks like Renovate has been trying to set the status on every run, and it has exceeded the [1000 status updates that are allowed](https://developer.github.com/enterprise/2.13/v3/repos/statuses/#create-a-status). (This is a rather old pull request, and our Renovate runs every 10 minutes)

**Comment by rarkins** [comment]
oh wow, I assumed if you use the same context for status set then it counts as one "status update".
