### ISSUE TITLE
Unnecessary `v` in Renovate Docker PR

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/renovate#1806]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

I'm seeing an unnecessary `v` in the PR title for an update to the `latest` version of Node in a Docker digest PR - https://github.com/factset/labeledpipe/pull/60

![renovate](https://user-images.githubusercontent.com/10657293/38445977-698dbec0-39bb-11e8-90c4-88f150e0d194.png)

**Comment by rarkins** [comment]
I'll make sure this is fixed as part of #1760

**Comment by rarkins** [comment]
Actually this looks like the wrong prTitle. Tag is *already* latest so this title should be for updating the digest.
