### ISSUE TITLE
Lock file maintenance PRs not opened for a while

### ISSUE THREAD

**Issue by edmorley** [renovateapp/renovate#1809]
#### This is a:

* [X] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [X] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:
Hi :-)

I had a realisation earlier that I hadn't seen a lockfile maintenance PR on either of these two repositories for a while:
https://github.com/mozilla/treeherder
https://github.com/mozilla-neutrino/neutrino-dev

Looking at them now I see the last PRs were ~26 days ago (the schedule is weekly):
https://github.com/mozilla/treeherder/pull/3329
https://github.com/mozilla-neutrino/neutrino-dev/pull/746

I checked to see if there was a stale lockfile maintenance branch open, but there isn't.

I don't suppose you have any ideas as to what is happening?

Many thanks!

**Comment by rarkins** [comment]
Well, this one is easy to pinpoint in the logs: `"Skipping branch creation due to unpublishSafe + status checks"`

This was a "fix" I added to avoid the conflict between unpublishSafe + prCreation=not-pending. Seemed easiest to just not create the branch until it was publish-safe, but it is impacting lock file maintenance too!

**Comment by edmorley** [comment]
Thank you :-)

**Comment by edmorley** [comment]
Are new releases are auto-deployed at the time of the release comments (like the one above)?
It's just that I didn't see a lockfile PR this Monday, which was after the release.
Sorry to be a pain again!

**Comment by rarkins** [comment]
No problem - it needs to be resolved one way or another. Unfortunately this particular release didn't get merged into the App until mid-Monday, so missed the typical lock file schedule.
