### ISSUE TITLE
discovered projects but No repositories found warning

### ISSUE THREAD

**Issue by flipflopsimsommer** [renovateapp/renovate#1823]
#### This is a:

* [ ] Bug report (non-security related)
* [ ] Feature request
* [x] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [x] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

i'm using renovate with docker, since version 12 renovate will discovere my projects, but then warn me about no repositories found:

```sh
docker run -it \
renovate/renovate:latest@sha256:e4d4281ef0e735186cf955320fb40cecff0431513618962c079da4cf9879fff0 \
--token <token> \
--platform gitlab --autodiscover --endpoint https://git.example.org/api/v4/ \
--log-level=debug
```
output:

```txt
DEBUG: File config
       "config": {}
DEBUG: CLI config
       "config": {
         "logLevel": "debug",
         "platform": "gitlab",
         "endpoint": "https://git.example.org/api/v4/",
         "token": "***********",
         "autodiscover": true
       }
DEBUG: Env config
       "config": {}
 INFO: Autodiscovering GitLab repositories
DEBUG: getRepos(token, endpoint)
DEBUG: GET
       "path": "projects?membership=true&per_page=100"
 INFO: Discovered 8 project(s)
 INFO: The account associated with your token does not have access to any repos
 WARN: No repositories found - did you want to run with flag --autodiscover?
 INFO: Renovate finished
```

**Comment by rarkins** [comment]
@flipflopsimsommer thanks for your bug report and sorry for the inconvenience. This should be fixed now and you should soon see a patch release that's then built and released by Docker Hub. Can you confirm it's working again once that's ready?

**Comment by flipflopsimsommer** [comment]
thanks for the fast answer, i can confirm this is resolved now.
