### ISSUE TITLE
Renovate gives error about `packageRule` keys

### ISSUE THREAD

**Issue by sarunint** [renovateapp/renovate#1829]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [x] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

Whenever I run Renovate, I get this error:

```
ERROR: Found config errors
       "errors": [
         {
           "depName": "Configuration Error",
           "message": "depTypeList: depTypeList should be inside a `packageRule` only"
         },
         {
           "depName": "Configuration Error",
           "message": "packageNames: packageNames should be inside a `packageRule` only"
         },
         {
           "depName": "Configuration Error",
           "message": "excludePackageNames: excludePackageNames should be inside a `packageRule` only"
         },
         {
           "depName": "Configuration Error",
           "message": "packagePatterns: packagePatterns should be inside a `packageRule` only"
         },
         {
           "depName": "Configuration Error",
           "message": "excludePackagePatterns: excludePackagePatterns should be inside a `packageRule` only"
         }
       ]
```

This is likely due to #1810, since default config contains this:

https://github.com/renovateapp/renovate/blob/70ae45989020d02768a143090199b1b0a6d68421/lib/config/index.js#L19

https://github.com/renovateapp/renovate/blob/70ae45989020d02768a143090199b1b0a6d68421/lib/config/defaults.js#L22

https://github.com/renovateapp/renovate/blob/70ae45989020d02768a143090199b1b0a6d68421/lib/config/definitions.js#L374-L428

**Comment by rarkins** [comment]
Thank you for the detailed bug report - I'll take a look ASAP

**Comment by rarkins** [comment]
Could you clarify:

1. Does this happen before it starts any repositories?
2. How do you have it configured? e.g. `config.js`, ENV, etc?

**Comment by rarkins** [comment]
Nevermind, I can reproduce
