### ISSUE TITLE
Docs contents sidebar doesn't scroll

### ISSUE THREAD

**Issue by edmorley** [renovateapp/renovate#1838]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:
Hi!

When I visit https://renovateapp.com/docs/configuration-reference/configuration-options in either Firefox Nightly or Chrome beta, I'm unable to manually scroll the sidebar that links to each of the sections (eg by hovering over that panel and using the mouse scroll wheel), and it also doesn't scroll to highlight the current item when the main body of the page is scrolled past the items shown above the fold in the contents.

**Comment by destroyerofbuilds** [comment]
@edmorley is this similar to #1661?

**Comment by rarkins** [comment]
@edmorley please check out the new docs site https://renovatebot.com/docs - built with `mkdocs` with functional sidebar and better search.

**Comment by edmorley** [comment]
The new docs work (and look) great! 😃
