### ISSUE TITLE
Website UX issue - Menu on configuration options unusable

### ISSUE THREAD

**Issue by cabbiepete** [renovateapp/renovate#1840]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

Apologies if this is not the correct place for this issue let me know a different repo to post to.

On https://renovateapp.com/docs/configuration-reference/configuration-options the sidebar menu is unusable past whatever you can see on the initial viewport.

Probably a simple fix would be to make it not sticky and just scroll with the page.

I am guessing the original intent was that it would be separately scrollable which is also likely doable but a bit harder.

I'm happy to have a hack on this and do a PR if you point me at the source for the website (if it is open source).

**Comment by cabbiepete** [comment]
I've tested Mac - Safari and Chrome. Can also test other browsers as required.

**Comment by hbetts** [comment]
@cabbiepete is this similar to #1661?

**Comment by cabbiepete** [comment]
@hbetts yep its a duplicate of #1661

**Comment by rarkins** [comment]
Thanks @cabbiepete. Unfortunately the CSS for the website is in another repo that is not open sourced, so I can't take you up on your offer to take a look at it. I'm hoping to transition to a new template soon though

**Comment by rarkins** [comment]
@cabbiepete please check out the new docs site https://renovatebot.com/docs - built with `mkdocs` with functional sidebar and better search.

**Comment by cabbiepete** [comment]
@rarkins Great work :-)
