### ISSUE TITLE
Question: GitHub app installation with self-hosting and private GitHub/NPM

### ISSUE THREAD

**Issue by nathanpower** [renovateapp/renovate#1847]
#### This is a:

* [ ] Bug report (non-security related)
* [ ] Feature request
* [x] Just a question

#### I'm using:

* [ ] The Renovate GitHub App
* [x] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

Apologies if this is the wrong place for such questions, could not find anywhere else.

I am evaluating this for an organization with many (100+) NodeJS repos. They are running NPM enterprise and GitHub enterprise in their own VPC. My question is: It the [enabling of the GitHub  #app](https://renovateapp.com/docs/getting-started/install-github-app) required if I want to self-host Renovate within this setup, possibly even just from my own machine for the trial period?

**Comment by nathanpower** [comment]
Closing this for now as I think I have my answer (personal access token, instead of enabling GitHub app)

**Comment by rarkins** [comment]
Yes, simplest is to run it from a regular GitHub account using personal access token

**Comment by nathanpower** [comment]
I was hoping to use the docker image, and map a config.js file to that. I want to only onboard/enable renovate on a couple of repos. Is this possible using the config.js, without changing any repos in the org? I definitely don't want ~100 PRs opened just yet.

**Comment by rarkins** [comment]
You should be able to map a config.js with manual repo list using docker volumes

**Comment by nathanpower** [comment]
So something like:

```JS
module.exports = {
    npmrc: '//npm.some.org.com/:_authToken=xxx',
    repositories: ['org/repo1', 'org/repo2']
}
```

will be enough to just enable those repos?

**Comment by rarkins** [comment]
Yes. And never run with `automerge`. For best safety, at least during testing, use a dedicated bot account and only invite it to the repositories you need

**Comment by nathanpower** [comment]
It's working well for me now, thanks for the quick replies.
