### ISSUE TITLE
Support configuring initial commit prefix

### ISSUE THREAD

**Issue by fwal** [renovateapp/renovate#1867]
#### This is a:

* [ ] Bug report (non-security related)
* [x] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [x] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

I would like to configure the initial commit message during onboarding to work better with my tooling setup. Right now it's hardcoded to `Add renovate.json`.

My idea is to add two new configuration options, `onboardingCommitMessagePrefix` and `onboardingCommitMessage` and use handlebars to set the message.

I have code ready to go up in a PR if you agree with my proposal.

Thanks.

**Comment by rarkins** [comment]
@fwal thanks for the suggestion. I don't have anything philosophically against the idea, but would like to make sure first that the config options suggested are the cleanest way to do it.

I'm first of all wondering if there is any need to have two new options instead one one, i.e. if they are to be used and concatenated together at all times anyway.

Next thought is whether we should be doing this using existing configuration options instead, e.g. `commitMessage` and maybe also `prTitle` - or is "Configure Renovate" OK with you?

**Comment by fwal** [comment]
In my specific case I only needed to add a prefix but just having one configuration option works just as well and is probably better due to this perhaps being an edge-case.

I have no objection agains the PR title right now but I see your point. Also I need to have the prefix to differ from other commits.

As I've just getting started with Renovate (started testing it this Monday), I've yet to grasp the full width of the config system.

**Comment by rarkins** [comment]
Is your prefix a regular semantic one, e.g. `chore: add renovate.json`, or something custom? I've actually been thinking for a while that this initial commit should use the same "does this repo already follow semantic commits?" logic to decide whether to add "chore:" prefix by default. If that satisfies you then it's something I don't mind fixing/updating without any config change. "Add renovate.json" is something pretty much added on day 1 that I never thought about again after that, and there's nothing to stop its default value being changed either.

**Comment by fwal** [comment]
Sadly it's a custom but very close (basically a custom implementation created before semantic release became a thing).

I like your idea better and I would like to try to make our setup work in a proper semantic way.

**Comment by rarkins** [comment]
If you're OK with "Add renovate.json" being the main content, then I have this suggestion:

1. I will update the onboarding logic to honour semantic prefix settings (e.g. if autodetected, or manually enabled in bot configuration)

2. You would configure `semanticCommits: true` and `semanticCommitType: 'foobar'` in your `config.js`.

The result should be that the initial commit for onboarding will be `foobar: add renovate.json`.

Would that work for you?

**Comment by fwal** [comment]
Yes that works 👍

**Comment by fwal** [comment]
Just a thought but for consistency, maybe it should also use `commitMessagePrefix` and set PR title the same way as it does for update PRs.

**Comment by rarkins** [comment]
commitMessagePrefix is deprecated actually - use type and scope instead

**Comment by fwal** [comment]
Ah ok. 🙂
