### ISSUE TITLE
Add automerge option compatible with mergebots (like bors)

### ISSUE THREAD

**Issue by mythmon** [renovateapp/renovate#1878]
#### This is a:

* [ ] Bug report (non-security related)
* [x] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

There are several tools that handle merging and testing PRs through mechanisms besides the Github merge button (examples: [bors](https://github.com/graydon/bors), [bors-ng](https://bors.tech/), [homu](https://github.com/barosl/homu)). All of these tools work by watching for specially formatted comments on Github. After such a comment is left, the tool merges the PR with master, tests the resulting merge, and only then pushes the merge to master. It then moves on to the next mergeable PR. This is intended to result in a more consistent master branch.

Mergebots like the above work best when the master branch is controlled entirely by the mergebot. Other people or tools modifying the master branch at best interrupt the mergebot, and at worse can introduce breakage on the master branch. Therefore using a mergebot is incompatible with Renovate's automerge options.

My feature request is to add a new option for automerge that creates a PR, and then leaves a user-configurable comment on the issue, once Renovate has decided the PR should be automerged. Users could configure the mergebot and renovate to cooperate, creating automerges that still follow the mergebot's rules.

As a specific example, bors-ng scans comments for commands like "bors r+" alone on a line. That command would be read as "bors, I approve this PR, please merge it".

**Comment by destroyerofbuilds** [comment]
> once Renovate has decided the PR should be automerged

Would that happen according to Renovate's automerge rules?

For example, I setup my project to automerge on successful CI, and only if the change is a minor or patch version.

So would you expect to Renovate to only leave the comment after the PR has met Renovate's automerge rules?

**Comment by mythmon** [comment]
Yes, I would expect that rules like only minor or patch versions must be valid before the comment would be left. Whatever steps Renovate would normally take before automerging a PR would still happen. The difference would be the final step: instead of merging, it would only leave a comment.

**Comment by rarkins** [comment]
Right now we have three automergeMode values: `branch-push`, `branch-commit`, and `pr`. I guess this could add a third one: `pr-comment` ?

Before implementing, I'd like to know the exact comment format necessary for the three examples, so at least I can cover them. e.g. is it really just certain text found anywhere in the comment, or do any of them enforce that it must be the only text in the comment?

**Comment by mythmon** [comment]
A fourth `automergeMode` value, `pr-comment`, is exactly what I had in mind

All three tools follow a similar comment format. It is somewhere in between the two options you gave. The command doesn't have to be the only thing in the comment, but it must be on a *separate* line. Here is an example for each tool:

* bors: https://github.com/rust-lang/rust/pull/50326#issuecomment-385334177
* homu: https://github.com/servo/homu/pull/158#issuecomment-376875637
* bors-ng: https://github.com/mozilla/normandy/pull/1232#pullrequestreview-112996647

For bors and homu, the prefix is an `@` mention of an account tied to the tool. For bors-ng it is simply "bors". All three bots are perfectly happy if the comment has other contents. The important part is that *the command occurs on its own line*.

**Comment by rarkins** [comment]
What happens if the branch is updated (e.g. a newer version is released) before the bot has automerged? In that case do we need a new comment after the latest commit? Should we remove our old comment while we wait for passing status checks?

**Comment by notriddle** [comment]
> If the change happens before the merge process starts, then you wouldn't need to do anything. I'm not sure what any of the bots would do if the branch changes after the merge process starts. @notriddle, can you comment on how bors-ng would react if the branch being merged changed while a build was in progress? Or if the PR was closed?

If GitHub sends bors-ng or homu a notification that a branch was modified or a PR closed while it's building, we will discard the build and not merge. Unfortunately, you're creating a race condition if you do that; you might observe that the build was running, but in the time between that and GitHub getting around to sending us a webhook about your change, we might've finished the build and pushed it to master already.

Anything you do to cancel a build after starting it is best-effort, because we might not get your "cancel" request until after we've already merged, and merging a change into master is supposed to be irreversible.

**Comment by notriddle** [comment]
For context's sake, [Rultor's syntax is basically the same as homu's](http://doc.rultor.com/commands.html). It interprets everything after the mention `@rultor` as the command text.

And [BonnyCi keys directly off of GitHub Reviews](https://github.com/BonnyCI/bonnyci.org/blob/master/lore/end_users/use/README.md). If a repo collaborator gives an APPROVED review, then it puts it into the merge queue; no special comment needed. I'm not sure if BonnyCI is still running, though, so it probably isn't worth supporting it.

**Comment by rarkins** [comment]
@notriddle thanks for testing. I guess the safest option is to have *only* the configured text in the comment. Here is what I'm thinking:

1. New value `pr-comment` available for `automergeType`
2. New option `automergeComment` which is a text string
3. If automerge criteria are met (i.e. branch has status check="success", or user has disabled status checks using `requiredStatusChecks=null`) then we add that comment. It won't ever be removed or added more than once.

Sound good?

Cc @mythmon

**Comment by mythmon** [comment]
I'm happy with that plan.  :+1:

**Comment by rarkins** [comment]
@mythmon @notriddle the feature is now live in the hosted app. Could you test it out?

Example config:

```
{
  "automerge": enabled,
  "automergeType": "pr-comment",
  "automergeComment": "@bors: r+"
}
```

**Comment by mythmon** [comment]
I [added the configuration to a small project](https://github.com/mythmon/corsica-tree-status/pull/14). I guess I will have to wait until a package updates before renovate will try again? Or is there a way to force its hand somehow?

@notriddle one concern I have is that the "user" that Renovate uses to make the comments and commits doesn't seem to be a normal user. I'm not sure how bors-ng will handle that for permissions purposes. I've manually added "renovate" to the allowed users on the project's configuration, but I'm not sure if it will work.

**Comment by rarkins** [comment]
If there are no open PRs for the project then there’s not really any way to test it there. 

App “users” are a little weird. Eg the app name is “renovate” but there’s a user also called “renovate” who is not me. It seems that GitHub presents it as “renovate[bot]” in some contexts.

**Comment by mythmon** [comment]
I added a purposely out of date package to the project, so that Renovate would have something to do. Renovate has created [a PR for the update](https://github.com/mythmon/corsica-tree-status/pull/16), but it doesn't seem to have left a comment to automerge it.

**Comment by notriddle** [comment]
> I've manually added "renovate" to the allowed users on the project's configuration, but I'm not sure if it will work.

You need to use `renovate[bot]`, not just `renovate`. Same way it shows up in commits.

**Comment by mythmon** [comment]
> You need to use renovate[bot], not just renovate. Same way it shows up in commits.

I realized that I should use `renovate[bot]` myself, luckily before Renovate left the comment. Now Renovate has left the correct comment, and bors-ng merged the PR as expected. It all seems to have worked! Thanks for the help everyone.

> The app currently isn’t “wired” to react immediately when branches go green. It’s actually harder than you’d expect due to the design of GitHub’s webhooks. So I’m the meantime you can expect automerges to happen at worst hourly when the background jobs run.

I've taken a stab at monitoring CI status of commits in PR. You're right, it is surprisingly difficult. I didn't realize that Renovate would be waiting for CI to pass (though it makes sense). It probably should be covered in another issue, but with mergebots like bors-ng it wouldn't be needed to wait for the CI status, since the mergebot will check that.

**Comment by rarkins** [comment]
In that case add this config to disable waiting for status checks:

```
  “requiredStatusChecks”: null
```

Possible it may not add the comment immediately - I need to check. GitHub take at least a few seconds to report that a new branch is mergeable and normally this causes us to skip automerge on the same run we create the branch. If all we’re doing is adding a comment then I could add extra code to ignore the GitHub status entirely.
