### ISSUE TITLE
[Docs] Which is the correct default value of separatePatchReleases?

### ISSUE THREAD

**Issue by ryo-utsunomiya** [renovateapp/renovate#1901]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

There are contradictory descriptions in the docs.

In https://renovatebot.com/docs/config-presets/config-default , the default value of `separatePatchReleases` is `true`.

However, in https://renovatebot.com/docs/configuration-reference/configuration-options#separatepatchreleases , it is `false`.

Which is the correct default value of `separatePatchReleases`?

**Comment by ryo-utsunomiya** [comment]
Sorry I misunderstood the docs.
https://renovatebot.com/docs/config-presets/config-default is not the docs about default values.
Actually, the default value of `separatePatchReleases` is `false`.

**Comment by ryo-utsunomiya** [comment]
However, Renovate onboarding PR says `Combine any patch and minor upgrades together into same branch/PR` is the default. Is this incorrect?

```
Based on the currently configured presets, Renovate will:

...
Combine any patch and minor upgrades together into same branch/PR
```
https://github.com/ryo-utsunomiya/amazon-block/pull/1

**Comment by rarkins** [comment]
Hi @ryo-utsunomiya 

Please see the https://github.com/renovatebot/config-help repository for future config help questions.

I will describe `separatePatchReleases=false` (default) with an example.

If you currently have `v1.1.0` and both `v1.1.1` and `v1.2.0` are available then this means that you get only one PR - for `v1.2.0`. This is what is meant by "Combine any patch and minor upgrades together into same branch/PR".

If you wanted to get two separate PRs, e.g. one for `v1.1.1` and another for `v1.2.0`, the you should set `separatePatchReleases=true`.
