### ISSUE TITLE
Renovate don't update non-pinned private packages

### ISSUE THREAD

**Issue by fwal** [renovateapp/renovate#1916]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [x] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

Renovate doesn't seem to update private packages as long as they're semantically versioned in package.json (`^1.0.0`).

`yarn upgrade-interactive --latest` lists the updates. As soon as I pin the version in package.json, Renovate starts to update.

Other packages update perfectly fine.

**Comment by rarkins** [comment]
Questions:

1. Using your example of `^1.0.0`, what are you expecting it to be updated to, e.g. a minor version like `^1.1.0` or major like `^2.0.0`?

2. You say "private packages". Is the behaviour you're seeing different for public packages?

**Comment by fwal** [comment]
1. I expect minor and patch versions
2. By "private packages" I mean packages private on npm under our @[org] scope. Public packages gets updated properly but the private seems to be ignored. I don't even see any logs mentioning them when renovate runs.

**Comment by rarkins** [comment]
OK. There is likely no bug here, I think you just need config help. Please raise an issue in https://github.com/renovatebot/config-help/issues instead and I'll let you know the additional details required there. We can reopen and rename this issue if it turns out there is a bug after all.
