### ISSUE TITLE
Renovate PRs close unrelated issues if `Fix #nnn` or similar included in release notes

### ISSUE THREAD

**Issue by philippbosch** [renovateapp/renovate#1931]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

We just had a Renovate PR ([sinon](https://github.com/sinonjs/sinon) from `v5.0.3` to `v5.0.5`) that when merged closed a completely unrelated issue on our repo. The reason being that the release notes in the PR had the string `Fix #1781` in them. 

Screenshot:

---

![image](https://user-images.githubusercontent.com/57509/39696795-231326a0-51ef-11e8-81a8-d28dd92d8a7f.png)

---

Coincidentally our repo also had an open issue 1781. 

Possible fix: replace `#nnn` with `owner/repo#nnn`, e.g. #1781 becomes sinonjs/sinon#1781.

**Comment by rarkins** [comment]
@philippbosch sorry for the inconvenience. I'll see what can be done to detect and block this type of linking. We ideally want to block all "automatic" linking by GitHub because the people in the Sinon repository wouldn't want to see hundreds of back references from Renovate PRs either.

**Comment by philippbosch** [comment]
@rarkins oh, very true. then maybe wrap the `#nnn` in backticks to prevent the link? 

`#1781`

**Comment by philippbosch** [comment]
oh, zero-width spaces – 👌!

this was in a private repo.

**Comment by rarkins** [comment]
OK, that partially explains it. I was trying to mutate/interfere less for private repos because they *don't* result in annoying back references for upstream repos, however it might be necessary if it's causing other problems.
