### ISSUE TITLE
docs inconsistent around `rebaseStalePRs`

### ISSUE THREAD

**Issue by Aghassi** [renovateapp/renovate#1949]
#### This is a:

* [ ] Bug report (non-security related)
* [ ] Feature request
* [x ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

https://renovatebot.com/docs/configuration-options/#rebasestaleprs

This says "defaults to null", but the value in the table says "true". Which is it 🙃 ? Also, anywhere I can PR to make a change to the docs instead of doing this issue in the future?

**Comment by rarkins** [comment]
The default is actually `null`: https://github.com/renovateapp/renovate/blob/2cecf723b34862f609eac8762248d3303d387b57/lib/config/definitions.js#L578

The funny thing is that the descriptions are handwritten (see https://github.com/renovateapp/renovate/blob/master/website/docs/configuration-options.md#rebasestaleprs) and right. while the table is autogenerated based on `lib/config/definitions.js` but is wrong. We need to make that autogeneration smarter to understand a default of `null`.

The autogeneration is in a private repo so unfortunately not possible to be edited here.

Cc @SevenTurtles

**Comment by rarkins** [comment]
Now fixed, thanks for reporting
