### ISSUE TITLE
Onboarding PR commits being overwritten

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1961]
**What Renovate type are you using?**
GitHub App

**Describe the bug**
Changes to renovate.json by user were reset/overwritten by Renovate: https://github.com/thelounge/thelounge/pull/2437

**Expected behavior**
User changes are persistent.

**Comment by Songkeys** [comment]
This bug still happens to me on GitLab.

Every time I push a commit on the onboarding merge request, and it re-runs, the branch is then rebased by it. I can't have custom configuration...
