### ISSUE TITLE
release notes: compare link using commit instead of tag

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1963]
I was checking logs and noticed that this PR was updated unexpectedly: https://github.com/schulzetenberg/data-collector/pull/41

A manual inspect of PR body showed that a compare of `v6.0.0...v6.0.1` was updated to `v6.0.0...b9c40eef3cb0c0e4a25b4806a530e3bb8a2c7483`:
![image](https://user-images.githubusercontent.com/6311784/39967924-a508944a-56c4-11e8-85ed-266eaf43e10a.png)

I tried reproducing it here but could not: https://github.com/renovate-tests/changelog1/pull/1

I wonder if the failure to reproduce or even the problem itself could be related to timezones - Renovate App's servers are on west coast USA while I'm in Europe.

Either way, it shouldn't depend on time zones because if the tag exists then it should be used, regardless of time.

Here's another example: https://github.com/MCS-Lite/mcs-lite/pull/623
Another: https://github.com/klis87/redux-saga-requests/pull/110 (this one has the from as commit and not to)

**Comment by rarkins** [comment]
logs:
```
{"level":20,"repository":"schulzetenberg/data-collector","branch":"renovate/angular-cli-6.x","dependencies":["@angular/cli"],"args":{"manager":"npm","depType":"devDependencies","depName":"@angular/cli","fromVersion":"1.7.4","newVersion":"6.0.1"},"msg":"getChangeLogJSON(args)","time":"2018-05-13T13:35:47.821Z"}
{"level":20,"repository":"schulzetenberg/data-collector","branch":"renovate/angular-cli-6.x","dependencies":["@angular/cli"],"msg":"GET https://api.github.com/repos/angular/angular-cli/contents/ [retries=5]","time":"2018-05-13T13:35:47.822Z"}
{"level":20,"repository":"schulzetenberg/data-collector","branch":"renovate/angular-cli-6.x","dependencies":["@angular/cli"],"msg":"getReleaseNotes(angular/angular-cli, 6.0.1)","time":"2018-05-13T13:35:47.978Z"}
{"level":20,"repository":"schulzetenberg/data-collector","branch":"renovate/angular-cli-6.x","dependencies":["@angular/cli"],"msg":"getReleaseList()","time":"2018-05-13T13:35:47.978Z"}
{"level":20,"repository":"schulzetenberg/data-collector","branch":"renovate/angular-cli-6.x","dependencies":["@angular/cli"],"msg":"GET https://api.github.com/repos/angular/angular-cli/releases?per_page=100 [retries=5]","time":"2018-05-13T13:35:47.978Z"}
{"level":20,"repository":"schulzetenberg/data-collector","branch":"renovate/angular-cli-6.x","dependencies":["@angular/cli"],"msg":"getReleaseNotes(angular/angular-cli, 6.0.0)","time":"2018-05-13T13:35:48.338Z"}
{"level":20,"repository":"schulzetenberg/data-collector","branch":"renovate/angular-cli-6.x","dependencies":["@angular/cli"],"msg":"getReleaseList()","time":"2018-05-13T13:35:48.338Z"}
{"level":20,"repository":"schulzetenberg/data-collector","branch":"renovate/angular-cli-6.x","dependencies":["@angular/cli"],"msg":"Processing existing PR","time":"2018-05-13T13:35:48.362Z"}
```

The `fromVersion` looks wrong in the above, but what we see in the PR seems to be right.

**Comment by rarkins** [comment]
I also noticed a strange link here: https://github.com/spartha1995/Crud-Operation-Angular-2-/pull/59

For v6.0.0 the link is https://github.com/ReactiveX/RxJS/compare/6.0.0-uncanny-rc.7...6.0.0

I would have expected it to be 5.5.10...6.0.0

**Comment by kayoub5** [comment]
@rarkins is this still happening?

**Comment by rarkins** [comment]
Now fixed
