### ISSUE TITLE
changelog incorrectly uses unstable version in compare link

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1972]
Example/reproduction: https://github.com/renovate-tests/cl4/pull/2

The v6.0.0 "compare source" link is https://github.com/ReactiveX/RxJS/compare/6.0.0-uncanny-rc.7...6.0.0

**Comment by rarkins** [comment]
We can maybe defer this until after #1883

**Comment by kayoub5** [comment]
@rarkins is this still happening?
