### ISSUE TITLE
Question: How to commit a default renovate.json file in onboarding PR?

### ISSUE THREAD

**Issue by hi-larry** [renovateapp/renovate#1976]
_Using self-hosted service_

**What would you like Renovate to be able to do?**
At the moment, Renovate creates an onboarding PR with an empty `renovate.json` file. I'd like Renovate to commit a default `renovate.json` (by providing the path to the file) to this PR, otherwise I'd have 100+ repos to manually add a configuration file.

**Describe alternatives you've considered**
I tried adding the environment variable `RENOVATE_CONFIG_FILE` on repositories with and without Renovate configured. i.e. Running the renovate command on a repository that requires an onboarding PR (I guess it is expected that this doesn't work) and running it on a repository that already has a `renovate.json`. Are there any specifics to use for this environment variable to work?

Any help would be appreciated, thanks!

**Comment by rarkins** [comment]
Please raise config questions in https://github.com/renovatebot/config-help, thanks
