### ISSUE TITLE
Pricing confusion

### ISSUE THREAD

**Issue by danhaller** [renovateapp/renovate#1987]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Hi,

I'm attempting to pay for renovate via the marketplace app and I'm confused by the pricing. The marketplace says $39/year but when I go to pay it wants $468. I'm not sure if this is a renovate issue, a github issue, or I'm missing something.

Here's a screenshot:

![screenshot from 2018-05-17 16-57-35](https://user-images.githubusercontent.com/2386801/40190805-ab37af1e-59f7-11e8-9afb-cf41f323c8d6.png)

**To Reproduce**

Go to buy the app from the github market place

**Expected behavior**

Clear pricing

**Screenshots**

See above

**Comment by rarkins** [comment]
Looks like a GitHub bug but I’ll log in and double check soon. The unlimited plan is $39/month or 12x that per year. GitHub’s Marketplace has a limitation that if you pay for GitHub by year then you also need to pay for third party apps yearly too.

**Comment by rarkins** [comment]
It looks like at least 2 bugs there. Apart from it saying $39/year when it should be $39/month, it also charges the full year amount ($468) despite saying it's pro-rated. I'll raise a bug in the internal GitHub Marketplace forum.

**Comment by rarkins** [comment]
@danhaller that account is now whitelisted and should be back in service really soon now. I'll update this issue once I get a conclusive reply from GitHub.

By the way, if you're happy to pay direct instead of via GitHub and/or prefer to pay for Renovate monthly instead of annually, I can point you to a Stripe subscription link so you can do that instead.

**Comment by danhaller** [comment]
Thanks @rarkins. I'll speak to finance and see what works best for them.

**Comment by rarkins** [comment]
Hi @danhaller, I received a conclusive response from GitHub on this.

They confirmed it's a bug, here are the details:

- It affects only customers who pay by yearly invoice
- GitHub Marketplace actually *blocks* such customers from paying for third party apps anyway (I'm guessing if you kept clicking it would later fail)

Unfortunately there is (expectedly) no way an app developer like myself to check in advance which of their users are paying by invoice, so I hope GitHub make this clearer for users like yourself in future.

Anyway, the conclusion is that you will need to pay for Renovate directly, either via annual invoice/bank transfer, or via monthly via credit card. Could you or your finance email billing@renovatebot.com with your preference?

**Comment by rarkins** [comment]
@danhaller reminder if you or a colleague can please email me re: invoicing and payment
