### ISSUE TITLE
Renovate "updates" prerelease to some previous stable version

### ISSUE THREAD

**Issue by ajafff** [renovateapp/renovate#1990]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
I have `typescript@2.9.0-rc` as dependency. Renovate updated it to `typescript@2.0.0`.

**To Reproduce**
https://github.com/fimbullinter/wotan/commit/84145e4c9a217d60b474e5ff81f8c95d3bbe46ea

**Expected behavior**

One of the following
* Do nothing at all until `typescript@2.9.0` is released.
* Update to the latest stable release `typescript@2.8.3` (also not really desired, but at least that would make more sense than the current behavior)

**Additional context**
possibly related: https://github.com/renovateapp/renovate/issues/1988

**Comment by rarkins** [comment]
Sorry for the inconvenience @ajafff. I'll check the logs to try to work out the root cause

**Comment by rarkins** [comment]
The new version you should have been updated to was actually `2.9.1-insiders.20180516`. Renovate made the mistake of calculating that the appropriate range for that was `^2.0.0`. Now it would be `^2.9.1-insiders.20180516`.
