### ISSUE TITLE
Renovate does not pick private registry when using yarn

### ISSUE THREAD

**Issue by chambo-e** [renovateapp/renovate#2020]
**What Renovate type are you using?**
Renovate CLI `v12.30.19`

**Describe the bug**
Hello, I have a `registry` specified in a `.yarnrc` and when I use renovate to update my package it automatically defaults to `https://registry.yarnpkg.com/`

**To Reproduce**

1.  Create repository with some dependencies added with yarn
2.  Specify a custom registry in `.yarnrc`
3.  Use renovate cli to upgrade some packages
4.  There should be some `https://registry.yarnpkg.com/` in the `yarn.lock`

**Expected behavior**
Renovate to use the registry specified in `.yarnrc`

**Comment by rarkins** [comment]
Hosted app or self hosted?
Simple setup with yarn lock in root of repo and no workspaces?
Any authentication in use?

**Comment by chambo-e** [comment]
Self hosted, bare simple setup with no workspace and custom registry is public.

Renovate correctly detect we're using yarn

**Comment by rarkins** [comment]
Please run with CLI `--log-level=debug` or env `LOG_LEVEL=debug`. You may need to rename and close the existing (incorrect) PR otherwise Renovate won't try regenerating the PR and lockfile if there are no changes to the `package.json`. I also recommend redirecting to file, e.g. ` > debug1.log`. Then check the file for all mentions of `yarnrc`. In particular you *should* (if working) see a message starting with "Writing .yarnrc to".

**Comment by chambo-e** [comment]
I just tried and there is no mention of `.yarnrc`.

At the probe files stage I have 

```
DEBUG: getPackageFiles(npm) (repository=XXXXXX)
DEBUG: Using file match: (^|/)package.json$ for manager npm (repository=XXXXXX)
DEBUG: Matched 1 file(s) for manager npm (repository=XXXXXX)
       "matchedFiles": ["package.json"]
DEBUG: getFile(filePath=package.json, branchName=undefined) (repository=XXXXXX)
DEBUG: GET (repository=XXXXXX)
       "path": "projects/XXXXXX/repository/files/package.json?ref=develop"
DEBUG: npm.extractDependencies(package.json) (repository=XXXXXX)
DEBUG: getFile(filePath=yarn.lock, branchName=undefined) (repository=XXXXXX)
DEBUG: GET (repository=XXXXXX)
       "path": "projects/XXXXXX/repository/files/yarn.lock?ref=develop"
DEBUG: getFile(filePath=package-lock.json, branchName=undefined) (repository=XXXXXX)
DEBUG: getFile(filePath=npm-shrinkwrap.json, branchName=undefined) (repository=XXXXXX)
DEBUG: getFile(filePath=shrinkwrap.yaml, branchName=undefined) (repository=XXXXXX)
DEBUG: getFile(filePath=.npmrc, branchName=undefined) (repository=XXXXXX)
DEBUG: getFile(filePath=lerna.json, branchName=undefined) (repository=XXXXXX)
DEBUG: Detecting Lerna and Yarn Workspaces (repository=XXXXXX)
DEBUG: Finding locked versions (repository=XXXXXX)
DEBUG: Found yarnLock (repository=XXXXXX)
DEBUG: Retrieving/parsing yarn.lock (repository=XXXXXX)
DEBUG: getFile(filePath=yarn.lock, branchName=undefined) (repository=XXXXXX)
DEBUG: Returning cached result (repository=XXXXXX)
       "path": "projects/XXXXXX/repository/files/yarn.lock?ref=develop"
```

**Comment by rarkins** [comment]
Thanks, I did a code review and think the fix is pretty obvious. I have pushed a commit just now that will be released in a few minutes and hope it solves your problem. Please reopen if not, and thanks for reporting it.
