### ISSUE TITLE
ERROR: Error ensuring PR: Cannot read property 'project' of null

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/renovate#2023]
**What Renovate type are you using?**

Renovate CLI & Renovate GitHub App CLI (But is in Renovate, though I am using Renovate through Renovate GitHub App CLI).

**Describe the bug**

We are receiving the following error message:

```
ERROR: Error ensuring PR: Cannot read property 'project' of null
```

As a result, existing PRs associated with upgrading a dependency internal to our GHE instance, are not getting updated.

The error is caused by line 82 in the `changelog` code - https://github.com/renovateapp/renovate/blob/c2100ffc21fcddf34ade900985e0e7b2b160b96f/lib/workers/pr/changelog/index.js#L82

Line 71 is returning a `null` response - https://github.com/renovateapp/renovate/blob/c2100ffc21fcddf34ade900985e0e7b2b160b96f/lib/workers/pr/changelog/index.js#L71

A filtered version of the arguments passed to `getChangeLogJSON` are:

args:
```
{ manager: 'npm',
  depType: 'devDependencies',
  depName: '@scope/lint-standards',
  fromVersion: '7.0.7',
  newVersion: '9.0.1' }
```
pkg:
```
{ repositoryUrl: 'https://github.example.com/org/lint-standards',
  versions: [...]
}
```
opts:
```
{ githubBaseURL: 'https://github.com/' }
```

Even though the package is on an enterprise GitHub, as seen in the package repository URL, the `githubBaseURL` is still `github.com`.

That is because line 59 fails in our deployment scenario - https://github.com/renovateapp/renovate/blob/c2100ffc21fcddf34ade900985e0e7b2b160b96f/lib/workers/pr/changelog/index.js#L59

We deploy Renovate changes to a staging version of GHE, so our `GITHUB_ENDPOINT` environment variable equals `githubdev.example.com`, which does not match the repository URL domain.

**To Reproduce**

Create a package that contains a custom GHE URL, but setup Renovate with a `GITHUB_ENDPOINT` that doesn't match that repository URL.

**Expected behavior**

If Renovate fails to fetch a package's changelog, a warning should be logged, but PR updating should not fail. Instead, the changeglog step should simply be skipped over, allowing other PR update steps to proceed.

**Comment by rarkins** [comment]
@destroyerofbuilds thanks for the detailed bug report as always, and sorry for the inconvenience. I pushed a fix to check for `res` before `res.project` but also to wrap the whole block of code in a `catch` so that it wouldn't block PRs anyway, as you suggest.
