### ISSUE TITLE
Did not receive Onboarding PR

### ISSUE THREAD

**Issue by mindblender** [renovateapp/renovate#2054]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Added Renovate via the GitHub Application to the repo: https://github.com/apereo/cas and have not received the Onboarding PR.  

Note: I added Renovate to another repo and received the Onboarding PR in that repo, but not the one listed above.

**Comment by rarkins** [comment]
@mindblender sorry for the inconvenience. Renovate has been running on that repo but it is exiting with "Repository is a fork and not manually configured - skipping". I'll try to look into whether that is really the case (it does not seem to be a fork) but if you want to force it then you can manually add a `renovate.json` to the repo and it should start running after that.

**Comment by mindblender** [comment]
@rarkins Thanks for the prompt response.  We added a .renovaterc file (https://github.com/apereo/cas/commit/6ab601c186c88c5d37aab7010cb5c8d5e1e8cd25) and still did not get the PR nor any notifications that it found the package.json file.  I can re-add the renovate.json/.renovaterc file and try it again.

**Comment by rarkins** [comment]
Actually ignore the above - I clicked on the wrong log link and looked at another repo. You have a PR now: https://github.com/apereo/cas/pull/3343

**Comment by rarkins** [comment]
Also your last comment probably explains something else that was confusing me:
```
{"msg":"Found .renovaterc config file","time":"2018-05-31T06:00:18.915Z"}
{"msg":"GET repos/apereo/cas/contents/.renovaterc?ref=master [retries=5]","time":"2018-05-31T06:00:18.915Z"}
{"message":"Unexpected token : in JSON at position 10","msg":"Repository has unknown error","time":"2018-05-31T06:00:19.082Z"}
```

**Comment by mindblender** [comment]
Hmm . perhaps it was a malformed json file.  It appears to be working now though.  Thanks for the help!

**Comment by rarkins** [comment]
![image](https://user-images.githubusercontent.com/6311784/40801589-8fb1624a-6513-11e8-9686-a2dbb33f1602.png)

FYI in case you are adding the file manually in future, leave off the `"renovate": ` at the start so that the file begins with `{` and ends with `}`.

**Comment by rarkins** [comment]
Anyway, thanks for installing Renovate and sorry for the trouble! Closing now
