### ISSUE TITLE
Ignore engines that aren't in NPM

### ISSUE THREAD

**Issue by Arcanemagus** [renovateapp/renovate#2059]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Renovate is attempting to keep the `engines` field "updated" for values that aren't in NPM, leading to it filing PR's that remove parts of the range for some reason (https://github.com/ChristianMurphy/linter-selective/pull/29).

**To Reproduce**

1.  Create repository with an `engines` field that isn't in NPM (such as `atom`)
2.  Watch Renovate attempt to break the version range specified

**Expected behavior**
`engines` values that aren't in NPM should be ignored.

**Screenshots**
N/A.

**Additional context**
This functionality seems to be being requested in https://github.com/renovateapp/renovate/issues/320 and is partially implemented.

**Comment by rarkins** [comment]
There is a package `atom` on npmjs (atom@1.1.0) so isn't it technically "in NPM"?

Anyway, for now I will apply a whitelisting and only look at `node`, `npm`, and `yarn`.

**Comment by Arcanemagus** [comment]
> There is a package atom on npmjs (atom@1.1.0) so isn't it technically "in NPM"?

Oh wow, that does complicate things on your end!

**Comment by rarkins** [comment]
I decided to just whitelist npm, node and yarn fields in engines and skip the rest. I pushed a commit just now for that, so thanks for reporting the bug and sorry for the inconvenience caused!
