### ISSUE TITLE
`bumpVersion` Option Sets Version To `null`

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/renovate#2060]
**What Renovate type are you using?**

Renovate GitHub App

**Describe the bug**

When using Renovate with the `bumpVersion` option set to `minor`, pull requests are opened with the `version` field in `package.json` set to `null`.

**To Reproduce**

1.  Create repository with `yarn init -y`.
2. Add an outdated dependency, like `yarn add angular@1.5.0`.
3. Add `renovate.json` with the following content:

```json
{
  "extends": [
    "config:base"
  ],
  "bumpVersion": "minor"
}
```

4.  Install Renovate GitHub App on repository.

**Expected behavior**

Renovate should bump version from `1.0.0` (The default starting version of `yarn init -y`) to `1.1.0`.

**Screenshots**

![bumpversion](https://user-images.githubusercontent.com/10657293/40865625-e467c2e2-65be-11e8-8ea3-5aafe43f9106.png)

**Comment by rarkins** [comment]
@destroyerofbuilds thanks for the detailed bug report. I've fixed this and also made it a little more resilient so that it should "repair" any existing PRs with null version set on the next run.
