### ISSUE TITLE
Dependency update PR with conflicts not refreshed to resolve them

### ISSUE THREAD

**Issue by edmorley** [renovateapp/renovate#2080]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
A Renovate PR now has conflicts but hasn't been recreated from `master` to resolve them: mozilla/treeherder#3610

**To Reproduce**

1.  Have mozilla/treeherder#3610 be opened
2.  Merge the separate Renovate lockfile maintenance PR (mozilla/treeherder#3612) that happens to cause conflicts with the PR in (1)
3. Wait for mozilla/treeherder#3610 to be updated so you can merge it

**Expected behavior**
The mozilla/treeherder#3610 PR is updated so it no longer has conflicts and I can merge it. 

Ideally in the case of conflicts (and presuming no manual changes were made to the PR), the whole commit should be re-created from scratch by bumping the dependency from `master`'s copy of `package.json` / `yarn.lock`, rather than trying to handle conflicts at the Git level (which will fail in many cases).

**Comment by rarkins** [comment]
In theory we should always rebase/repair conflicting branches. In reality this is happening:
```
{"msg":"Found PR #3610","time":"2018-06-04T11:22:53.565Z"}
{"msg":"GET repos/mozilla/treeherder/pulls/3610 [retries=5]","time":"2018-06-04T11:22:53.565Z"}
{"msg":"PR state is dirty so unmergeable","time":"2018-06-04T11:22:53.845Z"}
{"msg":"Only 1 commit in PR so rebase is possible","time":"2018-06-04T11:22:53.845Z"}
{"msg":"Found existing branch PR","time":"2018-06-04T11:22:53.845Z"}
{"msg":"Checking schedule(, null)","time":"2018-06-04T11:22:53.845Z"}
{"msg":"No schedule defined","time":"2018-06-04T11:22:53.845Z"}
{"msg":"Skipping branch creation due to unpublishSafe + status checks","time":"2018-06-04T11:22:53.845Z"}
{"msg":"processBranch with 1 upgrades","time":"2018-06-04T11:22:53.845Z"}
```

i.e. it's detected as unmergeable but then apparently exits due to unpublishSafe + status checks.

However 3.12.0 was published 3 days ago.

**Comment by felixfbecker** [comment]
I have the same problem with a PR - it has merge conflicts now and is not being rebased

**Comment by rarkins** [comment]
@felixfbecker can you open a new issue with as many details as possible?

Also, you may wish to try https://renovatebot.com/dashboard to look at the latest and/or relevant log

**Comment by felixfbecker** [comment]
@rarkins what details do you need? It's a private repo so I can't link the PR or post the logs publicly

**Comment by rarkins** [comment]
For example: is it just taking too long to rebase, or does it seem stuck for hours or days? What do the logs say about that particular dependency/branch? (You can redact the repository name before copy/pasting). Has it always happened or it’s the first time?

**Comment by rarkins** [comment]
@felixfbecker did the PR resolve itself? Or still outstanding?

**Comment by felixfbecker** [comment]
Seems like it just took some time.

**Comment by rarkins** [comment]
Normally webhooks will catch the type of events that cause conflicts and enqueue a high priority job for the repo. Otherwise it’s caught in batch processing about once per hour. If you notice any pattern where such conflicts regularly take a long time to rebase, then please raise an issue so that I can work out which webhook combination it’s missing.
