### ISSUE TITLE
Support Python (PEP440) advanced specifiers/ranges

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#2085]
**What would you like Renovate to be able to do?**

Support specifiers like these:
```
~= 2.2
>= 2.2, == 2.*

~= 1.4.5
>= 1.4.5, == 1.4.*
```

**Describe the solution you'd like**
It should "just work" as each type becomes supported.

**Additional context**
Currently only specifiers of type `==x`, `===x.y` or `===x.y.z` are supported.

More here: https://www.python.org/dev/peps/pep-0440/#compatible-release

**Comment by kayoub5** [comment]
@rarkins the `===` should not be supported, since it's not meant for PEP440 versions, it's more of a hack to support legacy non PEP440 versions.

**Comment by rarkins** [comment]
OK. I think it is skipped out currently, so we just need to make sure it's not included by accident later
