### ISSUE TITLE
Include release notes in Node.js version bump PRs

### ISSUE THREAD

**Issue by edmorley** [renovateapp/renovate#2092]
**What would you like Renovate to be able to do?**
For PRs where Renovate is bumping the pinned version of node.js (eg mozilla/treeherder#3622), it would be great if there was a link to the changelog/release notes, or else if they were inlined in the PR description.

Example changelog link:
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.4.0

**Comment by kayoub5** [comment]
@rarkins this should be closed

**Comment by edmorley** [comment]
Many thanks!
