### ISSUE TITLE
PR's never opened

### ISSUE THREAD

**Issue by jonesmac** [renovateapp/renovate#2106]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
I have a private repository with renovate installed.  I was able to get the initial pull request (renovate/configure) but once I closed it, none of the work described in the description actually happened.  No additional pull request were opened, but it said 19 would be.  

**To Reproduce**

**Expected behavior**
New pr's should have opened.

**Screenshots**

**Additional context**
Since it is a private repo, I'm not sure the best way to get help?

**Comment by rarkins** [comment]
@jonesmac I don't see any logs at all under your username. Is it for a different account?

**Comment by jonesmac** [comment]
It is under jonesmac.  I opened the repo under a private org since its for a presentation I hope to give tomorrow.  I can send you more details in an email shortly.
