### ISSUE TITLE
Duplicate PR?

### ISSUE THREAD

**Issue by OmgImAlexis** [renovateapp/renovate#2111]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
I merged [a PR](https://github.com/agenda/agenda/pull/620) that renovate opened to pin our deps. For some reason it's opened another one but hasn't updated the deps instead it's trying to downgrade them.

Ref: https://github.com/agenda/agenda/pull/622

**Comment by rarkins** [comment]
@OmgImAlexis thanks for raising this bug report. There was actually a mistake in our "auto" pinning logic so *both* those PRs were in fact wrong. The correct one is now here: https://github.com/agenda/agenda/pull/622

FYI it is now correctly pinning devDependencies in `package.json` to be the same version as in your lock file.
