### ISSUE TITLE
Don't automatically update pre-release NuGet packages

### ISSUE THREAD

**Issue by tomkerkhove** [renovateapp/renovate#2126]
**What would you like Renovate to be able to do?**
Capability to configure that NuGet packages should not be automatically updated to new pre-release packages.

**Describe the solution you'd like**
Provide a configuration in the NuGet configuration where this can be turned on or off.

**Describe alternatives you've considered**
I've had this for [tomkerkhove/promitor](https://github.com/tomkerkhove/promitor/pull/73) but it's important to point out that it was already a pre-release package, not sure what happens if it was using a full package.

Relates to #2050

**Comment by rarkins** [comment]
By default Renovate only updates to pre-release packages if the existing version is pre-release. Wouldn't that be the best default to keep?

**Comment by tomkerkhove** [comment]
That makes sense and probably what I'm seeing. However, I'm wondering if it would make sense to have a feature flag that allows me to go from stable to preview if I want?

Anyway, clarifies my scenario so feel free to close if you want.

**Comment by rarkins** [comment]
The feature flag is called `ignoreUnstable` and defaults to true. Set it to `false` for any dependency and Renovate will always update to unstable versions even if the current is stable.
