### ISSUE TITLE
Discussion - NuGet packages only support .NET Core, not .NET Framework

### ISSUE THREAD

**Issue by tomkerkhove** [renovateapp/renovate#2127]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Current NuGet support introduced in #2050 only supports .NET Core which is using NuGet.
It doesn't support .NET Framework

**To Reproduce**

1.  Create repository with .NET Framework project
2.  Configure Renovate
3. Dependencies not detected

**Additional context**
I have no need for this and agree with @samneirinck that this should not be supported as it tends to be too complex and is a fair known limitation.

**Comment by tomkerkhove** [comment]
Basically NuGet supports packages for a variety of .NET flavors - .NET Core & Framework.

**Comment by samneirinck** [comment]
Thanks for the issue.

As a small side-note, you can still use it for .NET Framwork projects, as long as it uses the SDK-style .csproj's, as described [here](https://natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/).

**Comment by rarkins** [comment]
I think the best place for this description/caveat is in https://github.com/renovateapp/renovate/blob/master/website/docs/configuration-options.md#nuget

**Comment by tomkerkhove** [comment]
Well documented, thanks!
