### ISSUE TITLE
matchCurrentVersion never matches

### ISSUE THREAD

**Issue by gordlea** [renovateapp/renovate#2129]
**What Renovate type are you using?**
Renovate CLI 12.56.1

**Describe the bug**
Setting matchCurrentVersion in a packageRule causes that rule to never match. I'm setting this within a sharable config.

**To Reproduce**
In an existing app, in a packageRule, set `matchCurrentVersion: "<not latest semver>`. That packagerule will never match when you run the renovate cli.

**Expected behavior**
if the latest version of a package is 2.4.1, and I set `matchCurrentVersion': "< 2.4.1", it should match and have the rule applied.

**Additional context**
After doing some debugging, it appears that in the function [package-rules.js#applyPackageRules](https://github.com/renovateapp/renovate/blob/12.56.1/lib/util/package-rules.js#L10), the passed in config object always has `fromVersion === undefined`. This means that there will always be a negative match when [matchCurrentVersion is checked](https://github.com/renovateapp/renovate/blob/12.56.1/lib/util/package-rules.js#L96-L105).

Looking at where `applyPackageRules` is called from in ([lib/workers/repository/process/fetch.js](https://github.com/renovateapp/renovate/blob/12.56.1/lib/workers/repository/process/fetch.js#L23)), it happens before the code where I "think" fromVersion gets calculated (https://github.com/renovateapp/renovate/blob/12.56.1/lib/workers/repository/process/fetch.js#L44).

I may be misunderstanding how this works, please let me know if so.

**Comment by rarkins** [comment]
@gordlea thanks for the report. I'll take a look to see if it's working as intended.

**Comment by gordlea** [comment]
Thanks @rarkins, this would be really nice to have working. I want to be able to notify teams of required security updates like so in a shared config package.json: 

(assuming `some-npm-pkg` has a vulnerability fix in 3.9,4):

```json
{
  "name": "@myorg/renovate-config",
  "version": "1.0.23",
  "renovate-config": {
    "highPriorityUpdates": {
      "description": "Renovate preset for high-priority updates",
      "packageRules": [
        {
          "commitMessagePrefix": "HIGH PRIORITY:",
          "labels": [
            "bot",
            "high-priority"
          ],
          "packageNames": [
            "some-npm-pkg"
          ],
          "matchCurrentVersion": "< 3.9.4",
          "enabled": true,
          "prBody": "Required security update, see: https:<link to security team ticket>"
        }
      ]
    }
  }
}
```

Am I correctly understanding how the `matchCurrentVersion` setting should work?

Even nicer would be if there was also a setting in packageRule for an array of links/labels that would be put into the PR body.

**Comment by rarkins** [comment]
@gordlea that's an interesting approach and I think my fix should resolve it.

What do you mean by labels in the pr Body? do you mean in addition to the labels you attach to the PR already?

I actually aim to make improvements to both the areas you mention:

1. I'd like to have a semi-automated "database" of insecure release versions and allow Renovate to use these. e.g. some people may say "update dependencies monthly except if they're insecure"

2. I plan to redesign the PR body template to make it modular and hence more friendly to customise, e.g. letting you specify a custom paragraph or header without needing to copy/paste the entire thing

**Comment by gordlea** [comment]
> What do you mean by labels in the pr Body? do you mean in addition to the labels you attach to the PR already?

@rarkins I mean more of a prefix to the PR name, to get people to notice in the list. Labels are grey by default if they have not been configured to have a color, so it is easy for the eye to slide over it without noticing it. 

For our config, I have it now prefixing the PR name with "HIGH PRIORITY:" for any of the updates teams are required to make, to let teams know that it's not just a normal renovate suggested update.

I think idea 1 is a great idea. I wonder if you could use [`npm audit`](https://docs.npmjs.com/cli/audit) to do that. Then you wouldn't need your own list of insecure versions for the most part.

That being said, it wouldn't be quite enough for our organization, as we have internal libraries that npm audit wouldn't know about, so maybe a config where you can list other packages with vulnerabilities would be good as well.

Idea 2 would make things even nicer for us. 

Keep up the great work 👍  Renovate is a great project.

**Comment by rarkins** [comment]
@gordlea thanks for the feedback. I will keep it in mind to try to allow for a local override of package security status when implementing the feature
