### ISSUE TITLE
Docker Compose not in Language support & still mentioned as future feature in docs

### ISSUE THREAD

**Issue by tomkerkhove** [renovateapp/renovate#2164]
**Describe the bug**
The [Docker documentation](https://renovatebot.com/docs/docker/#future-features) mentions that Docker Compose is coming in a future release.

**Expected behavior**
Link to Docker Compose documentation.

I can help if you want.

**Comment by rarkins** [comment]
Thanks! It’s located in website/docs/* dir so you’re welcome to PR, otherwise I’ll update it on next few days

**Comment by tomkerkhove** [comment]
Feel free to assign to me, will do so this evening.

Should this be added to the "Language Support" list as well?

**Comment by rarkins** [comment]
GitHub won’t let me assign to outside collaborators but consider it yours :)

Generally I take a “language” and “package manager” approach but not everything falls neatly and sometimes there’s no point in having a language. In Docker case I’m considering “docker” as language and “dockerfile” and “docker-compose” as package managers and refactor a little in the code to make it match.
