### ISSUE TITLE
Renovate package.json > engines fields

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#320]
e.g. keep `node` and `npm` versions updated

**Comment by jbreckel** [comment]
also a new version for `yarn` would be nice

**Comment by rarkins** [comment]
@jbreckel thanks for the suggestion. I have some questions as I'm still trying to get my head around how this feature might work.

1. Do you currently specify an exact version or version range of yarn in your package.json>engines field?
2. Where/how do you use this field in practice? e.g. I know Heroku honours it, but I'm not aware of any other "automatic" use of it yet.

**Comment by jbreckel** [comment]
`yarn` fails to install your module if its version is newer.  
a range starting from the current version would allow us to install the tool.

**Comment by rarkins** [comment]
I think I misunderstood your comment to this issue. Do you mean that you need the version we have in our package.json to be updated or less restrictive as otherwise your yarn is rejecting it?

**Comment by jbreckel** [comment]
yes, the engines entry for `yarn` is too restrictive.  
sorry for the confusion

**Comment by rarkins** [comment]
I like what `yarn` is trying to achieve, but its versioning is a hot mess. e.g. it's "deterministic" .. but only if you and everyone on your dev team is using the exact same version of yarn. But then if you specify the yarn version in `package.json` like I did here, apparently that stops others like you with different yarn versions from installing the package. Clearly, it's not a good idea to pin yarn in the package.json so I've removed it now in https://github.com/singapore/renovate/pull/446 and will merge that if it hasn't broken CI (which also should have the same yarn version as dev).

**Comment by rarkins** [comment]
I've removed the yarn field from package.json engines in renovate 9.6.2. This issue will remain open as it was regarding whether to "renovate" these fields for other packages.

**Comment by Urigo** [comment]
I was wondering about `engines` support mostly for the use case of `node` version in apps.

I we discussed on email, there are a few questions to think about.
For example - updating to a major release might be too much.
if someone uses Node 4, maybe they want to get just one PR suggesting to update to Node 8. 
If they reject it, they would probably wouldn't want to keep getting updates every time there is a new minor or patch version to Node 8.

Some possible solutions:
1. Take into account `less than` on `engines`, for example: 
```
{ "engines" : { "node" : ">=4.10.3 <8" } }
```
Here we can keep getting updates on Node 4, 6 and 7 versions, but not on 8.
2. Some configurations on renovate.json
3. Internal logic to send just one PR for major version (basically just notifying that there is a new major version).

My personal opinion is that solution 1 is the best

**Comment by charlike** [comment]
I can't get the "idea" of this "feature". Why would one to update engines versions from time to time? I will have `node >= 6`, `npm >= 5` and `yarn >= 1` for all packages soon and i don't care what new version is out..

**Comment by Urigo** [comment]
@charlike one reason I can think of is that someone who uses babel or Typescript on the server, and when a new version of Node comes that supports ECMASCRIPT feature natively, he can insure everyone uses that release and remove transpiling for those features from the code.

Another is to make sure specific bug fixes from Node are being patches in all the instances of that app

**Comment by rarkins** [comment]
Is this the best place to get node engines list from? https://nodejs.org/en/download/releases/

**Comment by Urigo** [comment]
@rarkins looks like it but I'm not sure.
This might be also a good idea? https://github.com/nodejs/node/releases

**Comment by rarkins** [comment]
I'm interested in this feature but need some "real life" examples. Perhaps it only works if you somehow "pin" the engines, e.g. `<8` so that then you get an alert when  `8` is released or `10`.

**Comment by Urigo** [comment]
@rarkins I think there are few "real life" examples.

1. The server itself is dependent on features from that Engine, for example, using `async/await` without compilation.
2. Get important updates to your server, for example the latest security update that was released a few weeks ago.

People could use the `engines` field in their deployment scripts. For example referencing that in the `nvm` script

**Comment by Urigo** [comment]
I mean, I do want to get alerted when a new 8 is coming out.
but also when 10 is coming out....

**Comment by rarkins** [comment]
Sorry, I was unclear. I was thinking of "before and after" examples rather than so much why. I'm not sure if Renovate can necessarily "guess" what you'd want the semver updates to (eg simply add v8 or also drop v4?) but maybe most of the value would be alerting you that there's a new version available so you can decide what to do with it.

**Comment by rarkins** [comment]
This has also been requested by @vvo on Twitter: https://twitter.com/renovateapp/status/938004500798992384

He points to a `package.json` engines value of `"node": "^9.2.0"`:
https://github.com/algolia/community-project-boilerplate/blob/ce7f140a807f329eec2370d501098c25be670a6f/package.json#L23-L24

I guess their policy is to always upgrade to the *very latest* version? `9.2.0`, and next `9.2.1` or `9.3.0` I suppose?

**Comment by vvo** [comment]
> I guess their policy is to always upgrade to the very latest version? 9.2.0, and next 9.2.1 or 9.3.0 I suppose?

Yes that's how we do it, I think of it the same way I think of dependencies. Since nvm is very easy to use, we have an nvmrc field in every project then it just uses the value inside as a nodejs version.

**Comment by olstenlarck** [comment]
@vvo i was thinking about that strategy too. Sounds very good.

**Comment by destroyerofbuilds** [comment]
Some applications that I work with are configured with one of the following values for their `node` engine property:
* `^8.9.2`
* `^6.12.1`
* `^4.8.6`

Only LTS versions of Node are used.

With this month's [Node vulnerability advisory](https://nodejs.org/en/blog/vulnerability/december-2017-security-releases/), we proceeded to upgrade the version strings to one of:
* `^8.9.3`
* `^6.12.2`
* `^4.8.7`

By bumping the lower bound of the semantic version range, committing that change, and pushing the change to the application's repository, those application are re-deployed with a secure version of Node. (A good example of this is Heroku.)

It's a tedious, time-consuming, process to update the `node` property in each application.

**Comment by rarkins** [comment]
@destroyerofbuilds so would you be happy to update every time there’s a patch, or only when there’s a security patch?

**Comment by destroyerofbuilds** [comment]
> so would you be happy to update every time there’s a patch, or only when there’s a security patch?

I can see value in updating on every patch:
* Our applications uniformly consume performance enhancements introduced in Node.
* Our application development teams have uniform access to the same functionality (resulting from the introduction of enhancements, or bug fixes).

Those lead to a consistent improvement to our applications, and ensures a high degree of consistency between application runtime environments (which improves developer productivity when working across applications).

My example above merely highlights that raising the minimum version is a requirement, regardless of cost, for security reasons.

If the process is automated, and the `node` property updated on every Node release, we gain the aforementioned benefits.

One counter argument against updating on non-security releases is the increase _noise_ generated by additional pull requests.

However, a counter to that counter argument is that the version bump is not a major version, and so it could be automatically accepted assuming CI passes.

**Comment by rarkins** [comment]
@destroyerofbuilds thanks for the feedback. I think the easiest possible first step would be one where we pin to LTS (8.x.x) or current (9.x.x) and bump that every time there's a node.js release. So it's good if you think that fits in with your workflow.

**Comment by destroyerofbuilds** [comment]
> I think the easiest possible first step would be one where we pin to LTS (8.x.x) or current (9.x.x) and bump that every time there's a node.js release.

I believe that's fine.

The only drawback is that when Node 10 goes LTS next October, every project will receive a major version bump. Some teams may feel upgrading major Node versions to be a significant burden and elect to close the pull request.

I'm not sure what would happen in that case.

Will Renovate follow the existing major version workflow where it will accept the closed pull request as an indication that the team does not want to upgrade to that Node version, but still continue to auto-merge in patch upgrades for the current version of Node?

**Comment by rarkins** [comment]
> Will Renovate follow the existing major version workflow where it will accept the closed pull request as an indication that the team does not want to upgrade to that Node version, but still continue to auto-merge in patch upgrades for the current version of Node?

Yes, with a little bit of work that functionality/behaviour can be ported over from npm to node

**Comment by hbetts** [comment]
Coping a few comments I made in the Gitter channel to here.

---

A before/after example is here - https://github.com/renovateapp/renovate/issues/320#issuecomment-351767827

The benefits are documented in - https://github.com/renovateapp/renovate/issues/320#issuecomment-351767827

Those benefits are based on what is gained by Heroku-deployed Node services.

> I don't see the purpose of always bumping to the latest but retaining the caret range

For an application there is no benefit. Pinning is fine.

Further thought is required for what to do for Libraries.

I think Renovate's existing workflow of pinning and upgrading minor and patch, alongside major upgrades as a separate PR, works well with the example outlined in the aforementioned comments.

So right now, I would like if Renovate was automatically submitting PRs to keep bumping the patch and minor versions of Node 8 on my Node service, and in October I would expect a PR that bumps to the new major LTS, Node 10.

Since I already have automerge configured for minor and patch, I would just expect Renovate PRs to be merged into the master branch automatically on Node 8 releases

Again, for a Node service.

Node libraries would need to have the widest possible allowable range to prevent Yarn from failing on installs at the library consumer level because of Node version mismatches

**Comment by hbetts** [comment]
One downside that has come to mind is the fact that every developer on an application possessing a fixed Node version must all be using that version of Node.

Any attempt to execute `yarn install` with a Node in `$PATH` different than the version specified in the application's `engines` property will lead Yarn to fail.

For large single-application teams, it could be costly, and disruptive, to execute a `node` engine upgrade across the entire development team.

Furthermore, developers may contribute to more than one application, where each application is on a different fixed `node` version.

In the latter case mitigation is possible through the use of a Node version manager such as [`nvm`](https://github.com/creationix/nvm).

**Comment by rarkins** [comment]
@hbetts anything that `husky` could do? e.g. a script when you switch branches or pull it checks if `nvm` needs to be run

**Comment by rarkins** [comment]
Also, isn't the flip side of this discussion that, "Developers on the same team/project are running it with different versions of node"?

**Comment by hbetts** [comment]
> anything that husky could do

`husky` combined with `nvm` to run `nvm install` as part branch/pull operations would work.

> Also, isn't the flip side of this discussion that, "Developers on the same team/project are running it with different versions of node"?

Yes, that is _very_ common.

**Comment by rarkins** [comment]
This has now been partially implemented - node engines with exact ("pinned") version numbers are upgraded. Further work awaits receiving further before/after examples that use ranges.

**Comment by rarkins** [comment]
Two new issues created for `node` pinning and ranges respectively.

Versions of `npm` and `yarn` in `engines` can be done like regular npmjs packages because both `npm` and `yarn` are still available via npmjs. This issue will be closed when those are supported.

**Comment by destroyerofbuilds** [comment]
@rarkins are still tracking support for major version upgrades in this issue?

**Comment by rarkins** [comment]
@destroyerofbuilds can you give an example of before and after values you mean?

I was tempted to close this issue after splitting everything remaining into subissues, but there are quite a few participants who won't get notifications if so.

**Comment by destroyerofbuilds** [comment]
> can you give an example of before and after values you mean?

Yeah. I hadn't gotten to it earlier, though it has been on my todo list.

Taking over the `supportPolicy` option, I would like to set the following option in our group's shared configuration:

```json
{
  "supportPolicy": ["lts_latest"]
}
```

Now, let's assume my projects are pinned to the latest Node 8 release, `8.9.4`.

My projects are all getting deployed with Node `8.9.4`.

Then, in two months, Node 10 get's released.

My projects aren't upgraded because 10 isn't LTS.

Then, in October, when Node 10 releases its first LTS version, say `10.3.0`, I would like to see an upgrade pull request from Renovate upgrading the value of the `node` engines property from `8.9.4` to `10.3.0`.

Once accepted, I would not expect to see any upgrades for Node 8 releases because those would be older than _latest LTS_.

**Comment by rarkins** [comment]
@destroyerofbuilds that's a good use case.

> Once accepted, I would not expect to see any upgrades for Node 8 releases because those would be older than latest LTS.

Consider your case where you are on `8.9.4` and `10.3.0` reaches LTS status and you get a Renovate PR. Before accepting that PR, you'd still want a PR for `8.9.5` if it arrives, right?

**Comment by destroyerofbuilds** [comment]
I made the unstated assumption that [`separatemajorreleases`](https://renovateapp.com/docs/configuration-reference/configuration-options#separatemajorreleases) and [`separatepatchreleases`](https://renovateapp.com/docs/configuration-reference/configuration-options#separatepatchreleases) worked for `node` engine upgrades.

**Comment by rarkins** [comment]
This is now completed. There is still some improvement to be done to sync `node` versions with versionStrategy etc but hope to have that done by the time node@10 is LTS.
