### ISSUE TITLE
Bring changelog in-house

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#381]
Replace our existing use of [changelog](https://npmjs.com/package/changelog) with internal logic.

Confusingly, `changelog` doesn't actually download *changelog files* (e.g. `CHANGELOG.md`) but instead just downloads all the commits from a repo between the npm publish dates of the from and to version. The logic we have now to download `CHANGELOG.md` is already "in house" and will be combined with new in-house logic for commit retrieval.

This new "get commits" function will take an npm package name, a "from" version and a "to" version. It should then:

1. Identify the source repository for the package from the npm metadata. It often needs some "massaging" but we already have a package that helps with that

2. Decide how we will identify the exact from/to commits. I think most npm releases these days actually list the commit hash so that sounds ideal (e.g. start at the commit after hash A and include up to hash B). Otherwise, we may need to fall back to timestamps (all commits after timestamp A and before timestamp B) but I'm not sure how common that is

3. Retrieve the commits! Ideally this should be done intelligently. It will undoubtedly need pagination (Github limits to maximum 100 per query) but we don't want to retrieve *all of them* in the entire repo

4. Filter/massage them and cache them (like we do today). Commits between two hashes or two timestamps should never change, so we may as well save ourselves extra GitHub queries.

The goal is that `changelog` can be removed from project dependencies while PRs still look essentially the same.

Notes:

- For now, we are concerned only with GitHub.com source packages, however in future we will want to support "internal" GitHub Enterprise ones as well as ones from GitLab. Do not try to solve everything at once but just keep it in mind

- This code will probably be combined together with the existing `CHANGELOG.md` logic as there will be a bit of overlap

**Comment by rarkins** [comment]
For each release, we could use:

1. `gitHead` field:
```
"gitHead": "3ee4982ed00901f6aaa2c607d60d2b206a5fa1d0",
```
Maybe try this first, but could fail if anyone's done a force-push to the registry or has messy commit history?

2. Time of publish:
```
    "1.4.0": "2017-07-08T05:28:08.946Z"
```
Presumably a release could be pushed to `npm` minutes, hours or days after its head commit, and there could be many commits on github before that datetime. So this is not a particular accurate way to do it.

3. Release notes
Check GitHub for release notes matching the same version as the npm published version(s)

**Comment by rarkins** [comment]
How to deal with non-stable releases? 

- If from `4.0.0-rc1` to `4.0.0-rc3` then obviously they'd want to see commits and release notes for `4.0.0-rc2` and `4.0.0-rc3`
- If from `4.0.0-rc1` to `4.0.0` then it could be same commits as above but also `4.0.0`. However normally a `4.0.0` release would be expressed in terms of differences compared to the previous stable release, such as `3.5.2`
- If from `3.5.2` to `4.0.0-rc2` then release notes/commits for `4.0.0-rc1` and `4.0.0-rc2` would help

I think "filter out unstable versions unless from or to is unstable" should work pretty well and cover 99% of renovate updates. And as far as I can tell, that's how npm's semver checker works too. e.g.
![image](https://user-images.githubusercontent.com/6311784/27985915-9c83e684-63f5-11e7-82d1-2d99ff4c8c86.png)

The challenge might be finding the commits reliably if this version is being published from non-base branch, so Release Notes are important in such a case.

**Comment by rarkins** [comment]
Being able to retrieve release notes and commits from private repos that we have access to might be very useful. e.g. repo 'someuser/repo-a' depends on a private module that's built from 'someuser/repo-b' that we also have permissions to access.

**Comment by hbetts** [comment]
> However normally a 4.0.0 release would be expressed in terms of differences compared to the previous stable release, such as 3.5.2

That would be what I would expect, unless, as you noted, I was referencing a pre-release version, like `3.5.2-rc.1`, or something similar. In that case, maybe I would care about all the intermediate pre-releases before the `4.0.0`?

> gitHead

The `gitHead` field is not supported by Artifactory (semantic-release/semantic-release/issues/213). I do not know about the other binary repository platforms.

**Comment by rarkins** [comment]
> That would be what I would expect, unless, as you noted, I was referencing a pre-release version, like 3.5.2-rc.1, or something similar. In that case, maybe I would care about all the intermediate pre-releases before the 4.0.0?

If we are listing all the commits then yes. But if the project has made Release Notes for 4.0.0, the user is going to see "everything" since version 3 in those.

**Comment by rarkins** [comment]
How many repos actually *update* actual CHANGELOG files these days before publishing? And if they do, what are the chances we can parse it to extract the changes vs just linking to it?

**Comment by luftywiranda13** [comment]
> How many repos actually update actual CHANGELOG files these days before publishing? And if they do, what are the chances we can parse it to extract the changes vs just linking to it?

and what about if a repo update the *actual changelog.md* after tagging+publishing the new version? like CRA for example. 
I think it'll be better to refer to commit history+link to changelog (if any), or for a repo that doesn't have a `changelog.md` just show its commit history

**Comment by rarkins** [comment]
Here's an example of a library I use that makes use of changelog: https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md

**Comment by destroyerofbuilds** [comment]
It would be really nice if Renovate could incorporate the changelog posted to a project's GitHub or GitLab release page.

For example, there's a pull request against `renovate` for a `semantic-release` upgrade:

![confusing-changelog](https://user-images.githubusercontent.com/10657293/35359860-5a14a85a-0121-11e8-8af9-344549921b2a.png)

From the commit list, it's not apparent to me what commit introduced a breaking change, and what I need to do as a result.

On the other hand, `semantic-release` publishes GitHub release notes that are pretty comprehensive:

![good-changelog](https://user-images.githubusercontent.com/10657293/35359949-96bcb450-0121-11e8-98d4-e9a5aa061b74.png)

In my example above it's pretty easy to assume it's the `feat` commit that broke something, and to look at the commit on GitHub. However, this particular case is an exception, as most major version releases from upstream open source projects release 10+ changes at once, and non of the descriptions indicate a change in behavior.

**Comment by rarkins** [comment]
GitHub release notes are note incorporated.

**Comment by rarkins** [comment]
For changelog/commits, we have a "from" version, and a "to" version. We basically want commits for all versions that satisfy `>from <=to`. 
- Use semver to get all versions in that semver range.
- If `gitHead` is available, then use that per-Version to know the start/end commits
   * otherwise use the release's timestamp
- Find the timestamp of the "from" version and feed that to the `getCommits` function, i.e. keep paginating until passed that timestamp
- Cache commits per-version instead of per-range

**Comment by Haroenv** [comment]
If you're interested, in the Yarn website, we resolve the existing CHANGELOG file from GitHub/bitbucket/gitlab, [source](https://github.com/algolia/npm-search/blob/master/src/changelog.js). You can redo that logic, or if you want, I can give an API key to the index if you give a ballpark on how many requests would be done and maybe some way to show a "powered by algolia" if that makes sense.

**Comment by rarkins** [comment]
@Haroenv I think we need to implement it within this repository, because a lot of people run their own instances of Renovate and it's too messy to consider the need for keys in such a case. Thanks for the offer though.

**Comment by hulkish** [comment]
@rarkins I acknowledge this is not a direct goal for this task:
> For now, we are concerned only with GitHub.com source packages, however in future we will want to support "internal" GitHub Enterprise ones as well as ones from GitLab. Do not try to solve everything at once but just keep it in mind

But, in effort of keeping it in mind - how do foresee this configuration looking? Specifically, the private SSH key? I don't think storing an encrypted private key in renovate.json is an option (at least for my use of renovate).  I understand this only applies to non public github or private repos repos.

That said, back to "github only support". Maybe as a separate pr - I would like to make it possible to obtain both a changelog and/or the commits which apply to the package versions of private packages. What do u think?

**Comment by rarkins** [comment]
> But, in effort of keeping it in mind - how do foresee this configuration looking? Specifically, the private SSH key?

For GHE I foresee it using the same HTTP API token we already have, as that would be the most common use case for "internal" modules. We do not need to fetch anything over raw git (ssh).

>  I would like to make it possible to obtain both a changelog and/or the commits which apply to the package versions of private packages

Assuming you mean on npmjs.com/github.com ?

npmjs lookup should work already, because otherwise we wouldn't have an upgrade in the first place. Then assume it points to a private GitHub.com repo. In that case - if it's the app/bot - then it should work fine so long as the repo has been added to Renovate also. In the case of a GHE user like yourself, your github.com auth will be via a Personal Access Token, so if that github user has read access to the private github repo then it should also work.

**Comment by hulkish** [comment]
@rarkins Just leaving this here as potential strategy for handling "all" private repo cloning: https://github.com/nodegit/nodegit/blob/master/examples/clone.js

**Comment by rarkins** [comment]
Interesting!
