### ISSUE TITLE
Consider nsp integration

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#502]
https://www.npmjs.com/package/nsp

**Comment by hbetts** [comment]
For my projects I maintain a label called `security` that always get's prioritized in my queue.

So if `nsp` indicates that a dependency update includes changes to address security vulnerabilities, it would be nice if I could configure `renovate.json` to add the `security` label to those pull requests.

In the future I really hope [confidential merge requests](https://gitlab.com/gitlab-org/gitlab-ce/issues/14567) are a thing.

Also, another thought: Right now all my projects are setup to renovate their `yarn.lock` file on a given schedule. Perhaps `yarn.lock` updates should be trigger, regardless of a given schedule, if a vulnerability is detected in a dependency? For libraries, this probably doesn't matter. The lockfile is only used in development, which may not be considered a significant vulnerability. However, application lockfiles would be crucial in my opinion.

**Comment by rarkins** [comment]
> So if `nsp` indicates that a dependency update includes changes to address security vulnerabilities, it would be nice if I could configure `renovate.json` to add the `security` label to those pull requests.

One doubt I had was: is it likely that `nsp` will be able to flag updates before more people apply them anyway?

> Perhaps yarn.lock updates should be trigger, regardless of a given schedule, if a vulnerability is detected in a dependency? 

This is definitely possible in theory, as we wait until the last moment *not* to actually renovate the `yarn.lock`. i.e. we build up a list of updates/tasks and then don't apply any missing the schedule. It would be feasible to run the lock file maintenance regardless but only push it if we can detect something wrong.

Frankly I still need to understand `nsp` more and how timely and accurate it is before I can decide if and how to implement though.

**Comment by hbetts** [comment]
> It would be feasible to run the lock file maintenance regardless but only push it if we can detect something wrong

This sounds like it would cause `renovate` to take a performance penalty. Looks like `nsp` will get [offline yarn support](https://github.com/nodesecurity/nsp/issues/136) for detecting the use of vulnerable dependencies in a lockfile. Maybe that is sufficient?

> Frankly I still need to understand nsp more and how timely and accurate it is before I can decide if and how to implement though.

Well, `nsp`, is a good project to start with. Vulnerability data used by `nsp` is being moved into the [Node Security Working Group](https://nodejs.org/en/blog/announcements/nodejs-security-project/). So there's a lot of collaboration between the ^lift team (maintainers of `nsp`), and the Node foundation.
