### ISSUE TITLE
Test for write access early

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#509]
If you run renovate without write permissions on a public repository, the failure is really cryptic - the first error is when creating a blob. Renovate should test at initRepo time if it has write access and exit early.

e.g. for example you accidentally run it on: `yarn start rarkins/testrepo` instead of `yarn start your/testrepo`.

Note: the way to detect this will be different per-platform type, so it's ok to start with GitHub or GitLab only and split the issue. I think it can be detected inside `initRepo()` and an error thrown from there.

**Comment by kayoub5** [comment]
the [API](https://developer.github.com/v3/repos/collaborators/#check-if-a-user-is-a-collaborator) is available as preview, should we wait for it to be public, or use it anyway?

**Comment by rarkins** [comment]
I don’t think we need that one: “Tell me if x has write access”. We just need “tell me if I have write access”

**Comment by kayoub5** [comment]
GitHub API currently does not support "do I have write access", but it does support "does user 'me' have write access"

----

https://stackoverflow.com/questions/27883893
