### ISSUE TITLE
Consolidate Configuration Documentation

### ISSUE THREAD

**Issue by hbetts** [renovateapp/renovate#543]
Configuration documentation is now maintained in two locations.
* The `configuration.md` file - https://github.com/singapore/renovate/blob/master/docs/configuration.md
* The website - https://renovateapp.com/docs/configuration-reference/package#automerge

Having documentation in two locations leads to discrepancies in feature coverage.

For example, with the acceptance of 3c83075fb899332ae65361608ba4c9a004a3d75d, `automerge` includes `patch` documentation in the `configuration.md` file, but that feature is not documented on the website.

**Comment by rarkins** [comment]
Good point. My thoughts:

- Having two locations is fine but conditions must be met
- The ultimate *source* of configuration option names/values is ideally in the `renovate` source so that they can be updated at the same time as the code they describe
- The reasons for having docs on the renovateapp.com site is:
   * Users of a service will look there first
   * It is useful to filter out "admin"-only configuration that an end user should not be distracted or confused by. Admins should be fine to use the repository as source of truth so long as navigating that is easy
- If docs on the site remain, they *must* be in sync and the only sure way to manage that is to automate their inclusion in the renovateapp site

Therefore my conclusions would be:

- [ ] Add an additional boolean field called "admin" that indicates its only relevant to someone self-hosting/administrating renovate. This allows the renovateapp website to strip out any that are flagged as "true"
- [ ] Copy the markdown descriptions of fields I made for renovateapp.com back into the repository and source them from there. Hence repo and website retain exact same description for all non-admin fields
- [ ] Incorporate a check/test into renovateapp.com website build that makes sure the website is in sync before publishing

**Comment by rarkins** [comment]
I've started "porting" the detailed description of fields from the renovateapp.com source to this repository, but encountered a problem - it's getting very painful to embed the markdown necessary into javascript definitions file.

Are these detailed descriptions still best to locate in the `renovate` repository? Yes I think so.

But then if I separate these descriptions for readability, how best to do this and keep everything in sync?

I suppose it would be possible to write custom linting and syncing using https://github.com/wooorm/remark, but it's starting to get extra complicated.

So possible approach is:
- Keep config definitions js like it is, i.e. contains name, description, definitions and flags
- Keep a "flat" (no hierarchy) markdown file containing detailed descriptions for each setting
- Add a test that makes sure all options in the definitions js have an entry in the markdown

**Comment by hbetts** [comment]
> Having two locations is fine
That seems fine. I guess honestly it could be hundreds of places, so long, as you later state, there's a _single source of truth_ that maintains the authoritative documentation, and from which all other documentation portals pull from (and hopefully in an automated way :-) )

> ideally in the renovate source

Yes please. I've seen a few orgs attempt to maintain a separate `website` repository with a duplication of their CLI documentation, and configuration drift always becomes a pervasive issue.

For example, and because I'm familiar with the issue because of my use, the Yarn `website` repository has become a [laundry list of undocumented features](https://github.com/yarnpkg/website/issues). The lack of consistent documentation was brought up (yarnpkg/yarn/issues/2891, but there has been no movement on the request.

> The reasons for having docs on the renovateapp.com site is:

I agree, and I hope you keep the site around. I've been pointing people there as well for various things.

> it's getting very painful to embed the markdown necessary into the javascript definitions file.

Is that possible? I thought the definitions were used for the `renovate` help menu. Would that cause markdown to be dumped to the terminal?

**Comment by rarkins** [comment]
> > it's getting very painful to embed the markdown necessary into the javascript definitions file.

> Is that possible? I thought the definitions were used for the `renovate` help menu. Would that cause markdown to be dumped to the terminal?

The `renovate` repository currently has `name` and `description` fields. Meanwhile I typed out more in-depth descriptions on the `renovateapp.com` site so I tried copy/pasting those into an additional field `details` inside the `renovate` repo (using backtick strings) but it just becomes difficult and a mess.

**Comment by rarkins** [comment]
A half-crazy idea: convert the entire definitions file (currently in js) to structured markdown. Ie documentation as code. List of options and types would parsed from the file, h nice impossible for doc to be out of date..

Ideally would have explicit lint of the file but our current tests my already achieve most of that by accident.

**Comment by ikatyang** [comment]
@rarkins 

- [`markdown-magic`](https://github.com/DavidWells/markdown-magic) might be useful? 
- `separatePatchReleases` and `unpublishSafe` option are missing in [docs](https://renovateapp.com/docs/configuration-reference/package).
- it'd be better to have an `extends` option linked to [Shareable Config Presets](https://renovateapp.com/docs/deep-dives/config-presets).
- the order of options looks not consistent, they're neither alphabetical order nor category order (maybe it is? but I didn't see the category anywhere)

**Comment by rarkins** [comment]
> the order of options looks not consistent

Do you mean on the renovateapp.com site, or in the docs/ folder of the repo?

**Comment by ikatyang** [comment]
It's renovateapp.com.

![image](https://user-images.githubusercontent.com/8341033/29494670-eff2f8c4-85e1-11e7-9fdb-47a3554cac27.png)

**Comment by rarkins** [comment]
Thanks. it's updated now: https://renovateapp.com/docs/configuration-reference/package

**Comment by rarkins** [comment]
User-facing documentation will live at renovateapp.com, while anything for self-hosted will be only in the repo. I aim to push as much as possible of this documentation into this repo however, and have the renovateapp.com repo use it as a dependency and read from it.
