### ISSUE TITLE
Advanced scheduling requirements 

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#551]
Request from @charlike to discuss this

**Comment by rarkins** [comment]
Schedules are designed to "slow down" renovate (eg to less than hourly) and not "speed up" (eg attempting to run every 10 minutes).

When setting up a repository in particular it can be easy to get frustrated waiting for the next cycle to see changes though. 

Once Renovate has stabilised the reality is that you don't even need hourly - npm modules can be unpublished within first 24 hours of release so I don't recommend merging before then anyway unless it's an urgent fix.

**Comment by rarkins** [comment]
Also, schedule/frequency/responsiveness is essentially an admin problem. If you have enough boxes you can run every repository over and over until you exhaust GitHub limits. 

Webhooks are the missing link for "instant" gratification (eg creating Configure Renovate the second a user installs) but I think they're out of scope for this CLI tool. I plan to solve it another way (simple webhook -> logic -> run tool again if necessary).

**Comment by rarkins** [comment]
Things that can/should trigger a new run for a repository:

- Changes to Renovate branches or master branch 
   * potentially some of these changes wouldn't actually make any difference to Renovate but it's probably easiest to just run anyway
- Updates to any npm package that the repository depends on
- Scheduled updates cross their start time

If these are supported - and resilient/reliable - then you don't need to worry so much about the frequency of the base schedule.

**Comment by charlike** [comment]
All I was just talking about is "testing", meaning while you are newcomer to Renovate and just want to check if  the behaviors of the options are aligned with your expectations. Then, of course i'll lower it like "every day at the night", so it will be per around 24 hours for few ours only.

**Comment by rarkins** [comment]
>  i just saying that i think it would be good to have some way to trigger run for given repo.
 
Yes, I agree. That's perhaps the first functionality to be added to any web dashboard/interface once I make it, but if I'm being realistic I think it's not going to be done soon because it's like writing a whole other app instead of the ease of adding/enhancing capabilities currently.

Anyway that's why I'm looking into using webhooks to know when to run an "out of band" renovation for any repo that needs it. If that works then it's an even better solution than faster schedules or manual retries, and it's probably easier to implement.

**Comment by charlike** [comment]
Yes, i mentioned that that you suggestions sounds good if it is implemented with webhooks that listens on created issues, then in few minutes can work with the new config (actually, when you fill the empty PR as you suggesting).
