### ISSUE TITLE
Proposal: new option for Signed-off-by / DCO or `commitBody`

### ISSUE THREAD

**Issue by olstenlarck** [renovateapp/renovate#777]
Hi!

I'm willing to add [DCO](https://github.com/probot/dco) required check for the @tunnckoCore repos, and so, probably Renovate won't work well with that.

I'm looking for current options, but the only one that i think may be worked around is `commitMessage`? For example adding new line and manual `Signed-off-by:` tag? I'm almost sure it will work. But it would be good to have separate option for that, for example, `signoff: true`, so it will add that tag line itself.

Or probably adding `commitBody` option would work too.

**Comment by rarkins** [comment]
You should be able to work around this by customising the `commitMessage`. It's just a string so should be fine with some line returns and extra text added

**Comment by charlike** [comment]
Ye, i'm trying it now. We'll see after few hours.

**Comment by rarkins** [comment]
I don't mind adding a commitBody field soon though

**Comment by charlike** [comment]
Anyway, i'm more for `signoff` option. It will do that, instead everyone to do that manually through the `commitMessage`. And it will be easier for bigger projects to integrate Renovate without thinking how both things could work.

**Comment by rarkins** [comment]
I preferred commitBody as it seemed more generic. Isn't this DCO essentially still "proprietary" or is it truly and one and only "standard" for signing off commits?

**Comment by rarkins** [comment]
I see that the `-s` option (short for `--signoff`) is indeed "standardised" as part of git CLI, so a `commitSignoff` in Renovate sounds OK.

**Comment by charlike** [comment]
So, yea, problem with using the `commitMessage` option. Because it lowercases the whole message, but the tag needs to be with capital "S" in `Singed-off-by`

See https://github.com/tunnckoCore/parse-function/pull/49 message.

**Comment by charlike** [comment]
opened and issue at Probot's DCO app https://github.com/probot/dco/issues/29#issuecomment-327868970 , so lowercasing the message may not be a problem.

**Comment by rarkins** [comment]
We can fix it at this end too. The lowercasing is because that's the correct way for semantic commits. However we only should need to lowercase the first line and leave the rest as they are.

**Comment by charlike** [comment]
Absolutely. Great, i'll wait a bit.

**Comment by rarkins** [comment]
@olstenlarck I'm revisiting this one. Should the renovate bot sign off on commits as "itself"?

perhaps:
- Configure `commitSignOffMessage` message on server (bot owner needs to configure it, it's blank by default or set to some "alert")
- Users like yourself flip `commitSignOff` from `false` to `true` in renovate.json ?

**Comment by olstenlarck** [comment]
> Should the renovate bot sign off on commits as "itself"?

Mmm. Probably, it's okey for me and for the idea of DCO required. But also should be configurable, cuz Renovate is bot, owned by someone ;d

**Comment by rarkins** [comment]
So the signoff message
- should have a default value
- should be configurable by bot admin
- should be able to be overridden by the repo owner?

And is there any way Renovate could "detect" DCO use in a repo?

**Comment by olstenlarck** [comment]
Yup.

> And is there any way Renovate could "detect" DCO use in a repo?

Something similar of how detecting semantic commits, like `str.includes('Signed-off-by:')`?

**Comment by rarkins** [comment]
OK, so I'll do like semantic commits then. Default will be "null" which means autodetect. If we see any of the last 10 (?) commits use DCO then we'll enable it. That way users can also choose to (a) configure it always-on, or (b) configure it always-off. Do you have an example public repo I can use when testing?

**Comment by olstenlarck** [comment]
Sounds good, yea. Probably this one is good [tunnckoCore/rollup-config-tunnckocore](https://github.com/tunnckoCore/rollup-config-tunnckocore/commits/master).

**Comment by rarkins** [comment]
@olstenlarck this is now implemented using a preset. You can add the preset `":gitSignOff"` to your config's `extends` array to have the `Signed-off-by` git signoff added. It will add the `"gitAuthor"` value, which for the GitHub App is set to "Renovate Bot <bot@renovateapp.com>".

**Comment by olstenlarck** [comment]
Sweeet! Okey, I will update my preset :)
