### ISSUE TITLE
Errors when adding requested reviewers (GitHub)

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#782]
There seems to be a problem when adding reviewers on GitHub. The bot receives a "422 Unprocessable Entity" error and fails to add the reviewer(s).

Public repo examples:
```
        "url": "https://api.github.com/repos/apollographql/apollo-client/pulls/2129/requested_reviewers",
        "statusCode": 422,
        "statusMessage": "Unprocessable Entity",
```
Has configuration:
```
  "reviewers": [
    "@jbaxleyiii"
  ]
```

and 

```
        "url": "https://api.github.com/repos/uzh-bf/klicker-react/pulls/70/requested_reviewers",
        "statusCode": 422,
        "statusMessage": "Unprocessable Entity",
```
This one has `  "reviewers": ["rschlaefli"],`

**Comment by rarkins** [comment]
Adding the same user as assigned works:

![image](https://user-images.githubusercontent.com/6311784/30202362-7e0cf8c6-947e-11e7-89b8-2d476779f7a3.png)

Also, I found that adding an assignee fails *silently* if that user is not a collaborator.

**Comment by rarkins** [comment]
Now when I added myself as a collaborator to the test repo, both assignee and reviewer works:
![image](https://user-images.githubusercontent.com/6311784/30202639-61b7632c-947f-11e7-9f04-fbe5dd39230b.png)

**Comment by rarkins** [comment]
Example repo: https://github.com/apollographql/react-apollo/pulls

Assignees: usually works, but never errors if it fails
Reviewers: never works, sometimes raises and error

100% of those impacted are Organizations, which is probably not a coincidence

**Comment by rarkins** [comment]
Now testing using a test organization

**Comment by rarkins** [comment]
I realised that some of the above problems with assignees and reviewers are not really problems. Whenever PR automerge is configured, it is our deliberate behaviour to *ignore* assignees and reviewers because otherwise they're just going to get needless notifications.

**Comment by edmorley** [comment]
Our `renovate.json` includes:
```
  "reviewers": [
    "@mozilla/treeherder-admins"
  ],
```

...however the reviewer hasn't been set on any of:
https://github.com/mozilla/treeherder/pulls/app/renovate

**Comment by rarkins** [comment]
Yes, I believe it's a GitHub API bug. Reference: https://platform.github.community/t/support-for-review-requests-endpoints/2527

**Comment by rarkins** [comment]
GitHub claims to have now enabled this "missing" endpoint: https://developer.github.com/changes/2018-04-17-additional-endpoints-for-github-apps/

However it is still failing. I have posted it to the Apps forum here: https://platform.github.community/t/failing-to-add-pull-request-reviewers/5648

**Comment by rarkins** [comment]
This is now fixed by GitHub

**Comment by edmorley** [comment]
Renovate just opened mozilla-neutrino/neutrino-dev#841, however no reviewer was set?

Our config is:
https://github.com/mozilla-neutrino/neutrino-dev/blob/a75b56daad90415dab927569133b0131cacdf3fa/renovate.json#L9-L11

Which should map to:
https://github.com/orgs/mozilla-neutrino/teams/core-contributors

Any ideas? :-)

**Comment by rarkins** [comment]
It's possible that team reviewers is still not working. Can you raise a separate issue to track it?

**Comment by edmorley** [comment]
Certainly :-)
#1908
