### ISSUE TITLE
Support custom Docker registry

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#797]
Currently Docker registry lookups are hardcoded to the public docker registry. If someone uses a non-Docker registry then we need to modify code to detect and allow this.

**Comment by evilebottnawi** [comment]
@rarkins What is status? Maybe i can help?

**Comment by rarkins** [comment]
@evilebottnawi that would be great. I assume you are in need of this use case? If so, can you describe it in just enough detail for me to understand?

e.g. 

1. is your alternate registry fully specified within the `Dockerfile` already? Or would Renovate need to read from something other than the `Dockerfile` to know where to look up?
2. Does your registry require authentication?

**Comment by evilebottnawi** [comment]
@rarkins yes:
* Use `gitlab` and `gitlab-ci`
* We use default docker registry (registry.docker.io)
* We need auth
* Gitlab already support auth in CI, look https://docs.gitlab.com/ce/ci/docker/using_docker_images.html#define-an-image-from-a-private-container-registry

For us all works fine except when we need auth, i think better solution check env variables if they present. Maybe for gitlab check `DOCKER_AUTH_CONFIG`, but this is not necessary, it would be enough to indicate through the env variables `login`, `password` and `registry` (for future). Thanks for quick reply!

**Comment by rarkins** [comment]
@evilebottnawi in that case I think we're discussing in the "wrong" issue. Let's move to #798

**Comment by evilebottnawi** [comment]
@rarkins oh, yes thanks for ref

**Comment by rarkins** [comment]
I'm labelling this as `needs-requirements` for now. If anyone needs this support, please comment here describing your use case.

**Comment by mxey** [comment]
My use case would be: The Dockerfile FROM line does specify the used registry, like `gcr.io/google-containers/debian-iptables-amd64:v10`. Renovate just needs to extract the URL from that.

**Comment by rarkins** [comment]
Self hosted or GitHub app? Any auth necessary?

**Comment by mxey** [comment]
Renovate would be running self-hosted. Authentication would be necessary for our own registry.

**Comment by rarkins** [comment]
To clarify, I was meaning docker authentication (a feature also on the roadmap). Can you clarify:

- Your custom docker host would be Google Container Registry?
- You require auth for GCR?
- Which auth type(s) are possible? e.g. username/password, token, etc?

**Comment by rarkins** [comment]
In order to break the issue smaller, it would be good if we can start with an open/public registry example. Does anyone have any examples from something like GCR or Quay.io that we can test with?

**Comment by rarkins** [comment]
Although all container registries "just work" with the `docker` engine, it seems like they have different APIs for the lookups we need. 

Currently we need (a) a list of tags, and (b) to be able to retrieve the digest hash for any tag (but not all).

Docker's registry can give us a list of tags but we need to look up each tag's digest hash one by one.

Quay's registry can give us a list of tags and their digest hashes in one query.

Docker requires auth, even if anonymous/public, while Quay does not.

**Comment by mxey** [comment]
> Your custom docker host would be Google Container Registry?

Sorry for the confusion. I used GCR as an example for a public registry because I thought there was a standard API and Renovate just needed to support different API domains ;)

We use the Gitlab Registry for hosting our own images, but of course, the image we originate from might be from another registry.

> You require auth for GCR?

No, but Gitlab will require authentication. 

> Which auth type(s) are possible? e.g. username/password, token, etc?

Username/password, since even when tokens are used, those tokens are the “password” part of a username/password combination: https://docs.gitlab.com/ce/user/project/container_registry.html#using-with-private-projects

**Comment by rarkins** [comment]
It turns out that Docker registry APIs *are* mostly the same like I'd originally thought. The big difference is in how they authenticate. Custom registries will be supported initially without auth and auth types added one by one after that.
