### ISSUE TITLE
Support .NET

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#935]
This issue is for building up (a) support (please +1 if you would like to see .NET support) and (b) requirements, e.g. helping suggest what scope is required and what APIs can be used.

**Comment by samneirinck** [comment]
I'm willing to take this up. I've started experimenting already, and current status/onboarding PR can be found on https://github.com/samneirinck-test/Nancy/pull/1.

Still a lot of work to be done though.

Limitations:
- SDK style .csproj files only
- Only nuget.org support
- Not many packages fill in release notes, and not many packages have a nice link to the github repo, so it might be hard to get a lot of details for package upgrades

**Comment by rarkins** [comment]
@samneirinck that's really awesome. let me know if you'd like my help getting it to an initial version that can be merged into master.

Re: release notes/package mappings, maybe we might need to start a community-sourced repo for mapping that type of thing, if it would help.

**Comment by tomkerkhove** [comment]
As mentioned in the PR, it's currently off by default - If you want to use this you'll have to enable it in the config:
```json
{
  "extends": [
    "config:base"
  ],
  "nuget": {
    "enabled": true
   }
}
```
